### ISSUE TITLE
Missinformative error message when reading SSV 

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#1000]
### Description
If a SSM file is used to map parameters expressed in a SSV to a composite model, then the user is prompted with an error message if the parameter name in the SSV file does not exist in the FMU or there is not a mapping available in the SSM. Should this not be a warning instead? The simulation progressess with the default parameter values in such a case.

Mvh
Robert

@arun3688

**Comment by arun3688** [comment]
@robha67 that is true, if a parameter name in the `ssv` file does not have any mapping in the `ssm` file, then according to the specification the default value is applied and we are currently doing that, But the problem with SAAB test cases are the `ssv` file contains name that does not belong to any system or component in the ssp, and in such cases we could not apply the default values and that is why errors are reported and it is correct i guess, So according to the specification you should remove names from `ssv` files that does not belong to any `system` or `component`

**Comment by arun3688** [comment]
@robha67  adding to my previous comment, let us say we do not have the mapping (i.e) `ssm` file and we only have the `ssv` file then for the names present in the `ssv` file that do not belong to any system or component , we report errors, but we could also generate warning instead @lochel  can you comment on this
