### ISSUE TITLE
Discrepancy between result csv and mat files

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#1003]
### Description
Parameters seem to be missing from result files when stored as csv.

### Steps to reproduce the behavior

Simulate the "Saab Embrace use-case" in the test-suite. First, save the results in mat file format and then in csv file format. 
Look for the parameter model.root.ECS_SW.PID.k in both result files. If in line with our observations, it is only included in the mat file.

version = oms_getVersion(v2.1.1.post59_g0165678-linux)
print(version)

@lochel

**Comment by arun3688** [comment]
@robha67 the parameters are not exported by default to csv file, we have to use the flag `addParametersToCSV = true` something like below

`oms.setCommandLineOption("--suppressPath=true --skipCSVHeader=true --addParametersToCSV=true")
`

**Comment by lochel** [comment]
@arun3688 is right, csv files do not include parameters by default, because it blows up the result file size unproportional. If you really want to have parameters in the csv file, you can use the flag mentioned by Arun. @robha67, please reopen this issue if it doesn't work for you.
