### ISSUE TITLE
SImulation fails with Dassl, but succeeds with imprungekutta

### ISSUE THREAD

**Issue by AHaumer** [OpenModelica/OMSimulator#1004]
Version 1.17 64 bit on Windows 10 64 bit.
During my lectures, I'm working on an averaging model of an H-bridge. Seems to work fine, but:
If you set the enable-input = true during the simulation, the simulation fails with solver = Dassl,
but with solver = imprungekutta you get a plausible result.
I've enclosed an example for your convenience.

[BugReport.zip](https://github.com/OpenModelica/OMSimulator/files/6292765/BugReport.zip)

**Comment by lochel** [comment]
I moved the issue to the OpenModelica (omc) project. This is the OMSimulator repository for FMI and SSP-based simulations.
