### ISSUE TITLE
Renaming SSP crashes OMEdit

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OMSimulator#1008]
### Steps to reproduce the behavior
- Load test1
- right-click on  Gru_Test3 and choose rename
- try to rename into Gru
- => OMEdit crashes

### Version and OS
Tested on 1,18,0-dev 224 64 bit 
Win 10

- Version: 
- OS: [e.g. Win10, 64bit]

Test file:
[Test1.zip](https://github.com/OpenModelica/OMSimulator/files/6328716/Test1.zip)

**Comment by lochel** [comment]
Thanks for the report together with an example. I don't quite know why it fails, but it might be related to the connectors in the Root system. Renaming works fine if I first remove those. I will investigate more later today.

**Comment by lochel** [comment]
The problem is connected to the internal data management within OMSimulator. It has nothing to do with OMEdit. The following lua script can be used for debugging:

```lua
oms_setCommandLineOption("--suppressPath=true")
oms_setTempDirectory("./Test1/")

model = oms_importFile("Test1.ssp")
print(model)

oms_rename(model, "Gru")

src = oms_exportSnapshot("Gru")
--print(src)
```

**Comment by arun3688** [comment]
@max-privato The issue is fixed with this commit https://github.com/OpenModelica/OMSimulator/pull/1009, you can verify it

**Comment by max-privato** [comment]
I tested with 1.18.0-dev-239 win 64 bit (24 April) and I still had a crash

**Comment by arun3688** [comment]
@max-privato The fix is not merged with OpenModelica master yet, so you have to wait a little bit more

**Comment by lochel** [comment]
Sorry for the delay. We will merge it within a few days and let you know.

**Comment by lochel** [comment]
@max-privato this issue has been fixed as far as I can tell. Can you confirm, please?

**Comment by max-privato** [comment]
Yes it is fixed!
Thanks a lot for fixing this (and the many tickets I'm opening on SSP...)
