### ISSUE TITLE
Connecting integer outputs (in modelica connector class) to enum input 

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#1011]
### Description

OMsimulator reports the folowing error when a integer output on the form "<connectorName>.<signalName>" is connected to an enum:

"Type mismatch in connection:..."

### Steps to reproduce the behavior
Checkout "Embrace_trunk\WP3\D3.0\Saab\IntToEnumExample" from the embrace repository.
Run the file "SSP_Export.py" available in the folder mentioned above. 

### Version and OS

Linux, CentOS 7.4 VS. OMSimulator v2.1.1.post59-g0165678-linux

@lochel @arun3688

**Comment by robha67** [comment]
It seems like the connection works if i change the order of the signals i.e
addConnection("model.root.AdaptionUnit.sWsignals.Aircraft_State","model.root.ECS_SW.Input.Aircraft_State"): this works
addConnection("model.root.ECS_SW.Input.Aircraft_State","model.root.AdaptionUnit.sWsignals.Aircraft_State"): this produces the error above

The order does not matter for reals that are connected in the same way

**Comment by lochel** [comment]
@robha67 thanks for the example. I was now able to make a minimal example for debugging, see OpenModelica/OpenModelica#7404.

**Comment by lochel** [comment]
This is fixed with #1012.
