### ISSUE TITLE
Renaming an FMU makes an SSP unusable

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OMSimulator#1014]
### Description

I just wanted to change a the
 name of a model inside an SSP. The model, presioudly working, now stops with an error

### Steps to reproduce the behavior
**1) load TestSSP.ssp in OMEdit**
**2) run it: it simulates well**
log: 
python F:/AllOMs/OM1.18.0-dev-239-64bit/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/Massimo/AppData/Local/Temp/OpenModelica/OMEdit//TestSSP.ssp --endpoint-pub=tcp://127.0.0.1:65201 --logLevel=0 --option "--suppressPath=true"
server:  OMS Server 2.1.1.post64
server:  ZMQ 4.2.3
server:  PUB socket connected to tcp://127.0.0.1:65201
warning: turbina (): fmi2SetupExperiment: tolerance control not supported for fmuType fmi2ModelExchange, setting toleranceDefined to fmi2False
info:    maximum step size for 'TestSSP.Root': 0.100000
info:    Result file: TestTurbina_res.mat (bufferSize=10)
info:    Final Statistics for 'TestSSP.Root':
         NumSteps = 211 NumRhsEvals  = 218 NumLinSolvSetups = 16
         NumNonlinSolvIters = 217 NumNonlinSolvConvFails = 0 NumErrTestFails = 0
info:    1 warnings
info:    0 errors
Simulation process finished successfully.

**3) double-click on testTurbina and rename it to test**

**4) run the ssp again. Now the following error is issued:**
python F:/AllOMs/OM1.18.0-dev-239-64bit/share/OMSimulator/scripts/OMSimulatorServer.py --model=C:/Users/Massimo/AppData/Local/Temp/OpenModelica/OMEdit//TestSSP.ssp --endpoint-pub=tcp://127.0.0.1:65125 --logLevel=0 --option "--suppressPath=true"
server:  OMS Server 2.1.1.post64
server:  ZMQ 4.2.3
server:  PUB socket connected to tcp://127.0.0.1:65125
warning: turbina (): fmi2SetupExperiment: tolerance control not supported for fmuType fmi2ModelExchange, setting toleranceDefined to fmi2False
error:   [setReal] Unknown signal "TestSSP.Root.test.y_start"
error:   [instantiate] Failed to set start value for test.y_start
Traceback (most recent call last):
  File "F:/AllOMs/OM1.18.0-dev-239-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 177, in <module>
    _main()
  File "F:/AllOMs/OM1.18.0-dev-239-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 174, in _main
    server.run()
  File "F:/AllOMs/OM1.18.0-dev-239-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 134, in run
    self._model.instantiate()
  File "F:\AllOMs\OM1.18.0-dev-239-64bit\lib\OMSimulator\Model.py", line 27, in instantiate
    raise Exception('error {}'.format(Types.Status(status)))
Exception: error Status.ERROR
error:   [terminate] Model "TestSSP" is in wrong model state
warning: temp directory "F:/OM_Work\TestSSP-wetx2ewy" couldn't be removed
         boost::filesystem::remove: Accesso negato: "F:/OM_Work\TestSSP-wetx2ewy\temp\0013_turbina\binaries\win64\Gru_0TERmc_Sottosistemi_Turbina.dll"
info:    2 warnings
info:    3 errors
Simulation process failed. Exited with code 0x00000001.

### Version and OS

OM 1.18.0-dev239 Windows 10 64 bit

FILE:
[TestSSP.zip](https://github.com/OpenModelica/OMSimulator/files/6384438/TestSSP.zip)

**Comment by adeas31** [comment]
@lochel and @arun3688 is this another rename bug or is something to do with OMEdit export of ssp before simulation?

**Comment by arun3688** [comment]
@adeas31 I tested it it does not crash in OMEdit, I think submodule `OMSimulator` needs to be updated with OpenModelica to get these fixes

**Comment by lochel** [comment]
I just updated the OMSimulator submodule in the OpenModelica super-project.

**Comment by lochel** [comment]
@max-privato is this issue fixed?

**Comment by max-privato** [comment]
> @max-privato is this issue fixed?

I checked today with 1.18.0-dev-242.

The message has changed into the following one:

fmi2ModelExchange, setting toleranceDefined to fmi2False
error:   [initialize] TestSSP.Root.turbina: nominal[0]=0.000000 not greater than zero.
error:   [initialize] TestSSP.Root.turbina: nominal[1]=0.000000 not greater than zero.
error:   [initialize] TestSSP.Root.turbina: nominal[2]=0.000000 not greater than zero.
error:   [initialize] Initialization of system "TestSSP.Root" failed
Traceback (most recent call last):
  File "F:/AllOMs/OM1.18.0-dev-242-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 177, in <module>
    _main()
  File "F:/AllOMs/OM1.18.0-dev-242-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 174, in _main
    server.run()
  File "F:/AllOMs/OM1.18.0-dev-242-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 135, in run
    self._model.initialize()
  File "F:\AllOMs\OM1.18.0-dev-242-64bit\lib\OMSimulator\Model.py", line 32, in initialize
    raise Exception('error {}'.format(Types.Status(status)))
Exception: error Status.ERROR
info:    1 warnings
info:    4 errors
Simulation process failed. Exited with code 0x00000001.

The first four error lines have appeared because of the simultaneous fixing of ticket #1007.
The others are traceback seemingly related to the first four error lines.
So I suppose this ticket can be closed, but better for me to wait for the developers to do this.

**Comment by max-privato** [comment]
The issue is still there, but I've found a much simpler example to show it. Therefore I'm closing this ticket and opening a new one.
