### ISSUE TITLE
Infinite loop and crashes

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OMSimulator#1015]
### Description
There is already a ticket showing an infinite loop: #1007.
Despite it has been closed, the infinite loop is still there.
This ticket is a bit different from 1007, since in this case stopping the simulation causes an OMEdit crash.

### Steps to reproduce the behavior
1) load in OMEdit LoopAndCrash.ssp
2) run the ssp: an infinite message loop occurs
3) try to stop the simulation clicking on "Cancel simulation" => OMEdit crashes.

### Version and OS
1.8.0-dev239 Win 10 64 bit

[LoopAndCrash.zip](https://github.com/OpenModelica/OMSimulator/files/6376814/LoopAndCrash.zip)

**Comment by lochel** [comment]
This should be fixed. Please wait for the next nightly build and test it again 😃

**Comment by max-privato** [comment]
Yes, with dev-242 the infinite loop and crash  are gone.
