### ISSUE TITLE
String connector - Issue when tables are involved

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OMSimulator#1017]
### Description

When I create an fmu with OM, and then insert it into a brand new ssp, I should not have errors. I created a MWE involving tables which, instead, shows an error. I cannot be sure if it is an FMU creating or importing issue.

### Steps to reproduce the behavior
1. Load TestTable.mo in OMEdit
2. create an FMU from it
3. load the just-created FMU in a new ssp (Model-exchange)
4. The following messages are displayed (the latest two are errors):

[1] 07:47:53 Scripting Notification
Automatically loaded package Complex 3.2.3 due to uses annotation.
[2] 07:47:53 Scripting Notification
Automatically loaded package ModelicaServices 3.2.3 due to uses annotation.
[3] 07:48:14 Scripting Notification
The FMU is generated at D:/University of Pisa/ING-IND 33 - Terna-FMI/Da Ceraolo/GRU/OM_FMU32/TestTable.fmu.
[4] 07:48:43 Scripting Error
[NewConnector] Failed to import connector "table.fileName" with type "String"
[5] 07:48:43 Scripting Error
[NewConnector] Failed to import connector "table.tableName" with type "String"

The messages mention string import, but the string in the table are not used since tableOnFile is false.

The following zip contains mo, fmu and ssp:
[TestTable.zip](https://github.com/OpenModelica/OMSimulator/files/6382183/TestTable.zip)

### Expected behavior
Creating an FMU from OM and re-loading it from OMSimulator should cause no errors

### Version and OS

OM 1.18.0-dev 239 64 bit Win 10 64 bit

**Comment by lochel** [comment]
Thanks for the report. The FMU looks fine. `Modelica.Blocks.Tables.CombiTable1D` exposes the two parameters of type string (fileName and tableName) even if they are not used.
OMSimulator doesn't support string signals yet. Therefore, we give the error messages and ignore those connectors. The model should work fine as long as you do not want to excess those connectors.

We can keep this issue open until we fixed string connectors.

**Comment by max-privato** [comment]
what is strange is that the message mentions Error and writes it in red. 
I was induced to think that the SSP was not correctly loaded and executed.
Maybe it can be changed into a warning saying something similar to what you said, e.g. that the connections are ignored and the model should work as long as these strings are not used?

**Comment by max-privato** [comment]
I have checked this this morning with OM 1.18.0-dev-247 and the issue seems to have gone.
Have you fixed this? 
For me the ticket can be closed.
Thanks!

**Comment by lochel** [comment]
No, I didn't fix it and I don't think it actually is. We'll keep it open and fix it properly :)
