### ISSUE TITLE
Renaming an FMU inside an SSP messes things up

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OMSimulator#1020]
### Description

I hve an SSP with two FMUS, which runs well. If I rename one of the two FMUs it does not rune anymore.
### Steps to reproduce the behavior
1) load TestTurbine.ssp in OMEdit
2) Run it : OK
3) Double-click on Turb and change its name into Turbine
4) Run again: error
(requires --zeroNominal=true with 1.18.0-dev larger than 239)

### Expected behavior
Renaming should not change the behaviour

### Version and OS

This can replicated with 1.18.0-dev-247 (--zeroNominal=true required). 
OS: WIn10 64 bit

[TestTurbine.zip](https://github.com/OpenModelica/OMSimulator/files/6393589/TestTurbine.zip)

**Comment by arun3688** [comment]
@max-privato I tested your example and everything works for me, I cannot reproduce the error, I renamed the component several times and it works for me.  See the screenshot below

### Initial screenshot without name change
![image](https://user-images.githubusercontent.com/6870949/116450017-169fe500-a85b-11eb-96ef-0bae98e13a08.png)

### After changing the component name Turb to Turbine_1 
![image](https://user-images.githubusercontent.com/6870949/116450209-4fd85500-a85b-11eb-99a7-23b1127ad0e5.png)

### Simulation and plotting results  
![image](https://user-images.githubusercontent.com/6870949/116450486-a47bd000-a85b-11eb-9aac-c33b3c75f7ad.png)

### Again changed Turbine_1 to Turbine_6 and simulated and plotted the results
![image](https://user-images.githubusercontent.com/6870949/116450726-ec9af280-a85b-11eb-97dd-2054f9d73df5.png)

**Comment by max-privato** [comment]
Wierd. I confirm my outcome with 1.18.0-dev-247, win10. I enclose a video. and the latest screen

https://user-images.githubusercontent.com/37046832/116748316-936bc400-a9ff-11eb-979a-cfeaca9a96f4.mp4

![Img](https://user-images.githubusercontent.com/37046832/116748489-d4fc6f00-a9ff-11eb-8bd6-c8d1593ecbda.png)

**Comment by arun3688** [comment]
@adeas31 Can you test the above ssp file, I cannot reproduce the error in my machine

**Comment by adeas31** [comment]
I got the same error message as reported by @max-privato 

![image](https://user-images.githubusercontent.com/4007231/116868015-4dd11600-ac0e-11eb-8e16-349edeec502d.png)

**Comment by arun3688** [comment]
@max-privato Hi massimo, I confirm that i can reproduce the error and we found the bug and fixed it. The above PR #1023 should fix the issue and we will let you know once this is merged with OpenModelica master and you can test it.

**Comment by arun3688** [comment]
@max-privato The fix is pushed to OpenModelica master, You can test it from OpenModelica nightly builds from tomorrow.

**Comment by max-privato** [comment]
Thanks you!
Tomorrow I'll try.

**Comment by max-privato** [comment]
Just checked, and works fine.
Thank you!

**Comment by max-privato** [comment]
Just checked, and works fine.
Thank you!
