### ISSUE TITLE
Unclear issue with SSP

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OMSimulator#1021]
### Description

OMEdit reports an unclear error message with a simpleSSP

### Steps to reproduce the behavior
1) load TestTurbina.ssp
2) run it in OMEdit.

the following errors are shown:
error:   [setReal] Unknown signal "TestTurbina.Root.Turbina.Turbina."
error:   [instantiate] Failed to set start value for Turbina.
which I cannot understand.

I must add that I got this yesterday, and saved the ssp; unfortunately cannot now replicate it from scratch, i.e. starting from mos, creating FMUs, and then creating the ssp again. So the issue can now be replicated only from the enclosed ssp.

I report just in case for the developers is easy to envisage what's going on.

### Version and OS

OM 1.18.0-dev247; win 10 64 bit.
[TestTurbina.zip](https://github.com/OpenModelica/OMSimulator/files/6396856/TestTurbina.zip)

**Comment by arun3688** [comment]
@max-privato I tested your above attachment and  it works for me, I cannot reproduce the error. From the error message i find that there is no such variable `Turbina` in the `Fmu` .  But you are getting that error for some unknown reason. See the screenshot below

![image](https://user-images.githubusercontent.com/6870949/116518251-4d641280-a8d0-11eb-869e-5c92dc601c07.png)

**Comment by max-privato** [comment]
That's wierd. Maybe we didn't use exactly the same version? I confirm mine is OM 1.18.0-dev247; win 10 64 bit.
There are not many options for SSP. I  enclose the one I used these evening, that sould be the default ones (Screen2.png)
I enclose also the error message (screen1.png).
However, this ticket is not critical for me. I reported it mainly to contribute to the program development and debug. In case it is too tricky to fix, it is probably better to put it aside.
![screeen1](https://user-images.githubusercontent.com/37046832/116602930-9ea1ef80-a92c-11eb-8b8b-b44dc5be0ea5.png)
![screeen2](https://user-images.githubusercontent.com/37046832/116602960-a95c8480-a92c-11eb-83ad-1147e922d73d.png)

**Comment by arun3688** [comment]
@max-privato, the issue is related with the previous issue you reported #1020, when you renamed the fmu from "turb" to "tubina" the parameter set in the ssp got garbage value `Turbina.` which is not part of the fmu something like below

```
<ssv:Parameter name="Turbina.">
     <ssv:Real value="0" />
</ssv:Parameter>
```
So if you remove this parameter in the ssp it would work again, But the other PR #1023 should fix this bug, i have attached the corrected ssp.  You can test it

[TestTurbina.zip](https://github.com/OpenModelica/OMSimulator/files/6420691/TestTurbina.zip)

**Comment by max-privato** [comment]
Ok, thank you.
Tomorrow I'll try this and #1020. 
I hope to close both!

**Comment by max-privato** [comment]
Aha!
Now everything is clear. I'm going to close this as well.
Thank you.
