### ISSUE TITLE
Moving a model changes connections in a very bad way

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OMSimulator#1022]
### Description

In this example, if I move a model, connections are updated in a very bad way.

### Steps to reproduce the behavior
Load TestConnections.ssp (from the enclosed zip) and open TestConnections. The visual aspect of the ssp is as in screen1.png
Click on the "right" model and move it up with one up-arrow click. The picture is now as in screen2.png. As you can see, the connections are changed in a very bad way.
They are now misleading, since they seem to start from the wrong source pins

### Expected behavior

I expected that visual modification of connections will keep showing where connections get out from and go to. 

### Screenshots
Included in the enclosed zip file, which contains also the ssp needed to reproduce the behaviour
[TestConnections.zip](https://github.com/OpenModelica/OMSimulator/files/6413089/TestConnections.zip)

### Version and OS
OM 1.18.0-dev-247, WIn 10 64 bit

- Version: [`OMSimulator --version`]
- OS: [e.g. Win10, 64bit]

**Comment by lochel** [comment]
Thanks for providing your feedback. The instructions are clear and I can reproduce the issue. @adeas31 can you have a look at this, as the problem actually comes from within OMEdit.
