### ISSUE TITLE
OM 32 bit crashes with 32 bit SSP

### ISSUE THREAD

**Issue by max-privato** [OpenModelica/OMSimulator#1024]
### Description

I have a simpleSSP created composing two FMUs created with OM 1.18.0-dev247-32 bit. Therefore it is a 32 bit application.

With OM 1.18.0-dev247-64 bit
it says, rather correctly (but I think the message should be improved saying explicitly that a 64-bit OM cannot run 32-bit FMUs):

pk0070xl\temp\0004_Turb\binaries\win64\
error:   [fmiLogger] module FMILIB: The FMU contains no binary for this platform.
error:   [instantiate] Could not load "resources/0004_Turb.fmu" which is associated with "TestTurbOM32.Root.Turb"; it may be corrupted or may not support your platform

It crashes with OM 1.18.0-dev247-32 bit

In the enclosed zip the ssp and the two fmus.

I need to use 32 bit, because I must produce for a contract 32 bit FMUs, and, obviously, I have to test them in several ways.
### Steps to reproduce the behavior

open OMEdit
load the enclosed ssp
click on "Simulate" button
=> the program crashes.

### Version and OS

- OS: Win10, 64bit
[TestSSP.zip](https://github.com/OpenModelica/OMSimulator/files/6423195/TestSSP.zip)

**Comment by lochel** [comment]
I run your example with OMSimulator-mingw32-v2.1.1.post100-g788a7d4 and got the following error message:
![image](https://user-images.githubusercontent.com/8457302/125197099-ad761e00-e25c-11eb-9218-95c113fefe00.png)

**Comment by adrpo** [comment]
That dll should be delivered with OMSimulator as it depends on it, no?

```
adrpo33@ida-0030 MINGW64 /c/home/adrpo33/dev/OpenModelica/build/bin
# ntldd OMSimulator
        libstdc++-6.dll (0x00000000012b0000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x0000000000640000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x0000000000640000)
        libwinpthread-1.dll (0x00000000001f0000)
        SHLWAPI.dll => C:\WINDOWS\SYSTEM32\SHLWAPI.dll (0x0000000000620000)
        WSOCK32.dll => C:\WINDOWS\SYSTEM32\WSOCK32.dll (0x00000000001f0000)
        libomtlmsimulator.dll (0x0000000001660000)

```

**Comment by lochel** [comment]
Yes 👍 they must be included and I think @arun3688 is working ont it.

**Comment by adrpo** [comment]
I guess you could also compile OMSimulator statically on Windows to remove any dll dependency (well besides the libomtlmsimulator.dll).

**Comment by arun3688** [comment]
I guess the `libstdc++6.dll ` is not needed for `mingw32` versions

```
arupa54@win00085 MINGW32 /c/OPENMODELICAGIT/TestSSP
# ntldd C:/OPENMODELICAGIT/OMSimulator-mingw32-v2.1.1.post100-g788a7d4/bin/OMSimulator.exe
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x007d0000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x007d0000)
        SHLWAPI.dll => C:\WINDOWS\SYSTEM32\SHLWAPI.dll (0x007d0000)
        WSOCK32.DLL => C:\WINDOWS\SYSTEM32\WSOCK32.DLL (0x007d0000)
        libomtlmsimulator.dll => C:\OPENMODELICAGIT\OMSimulator-mingw32-v2.1.1.post100-g788a7d4\bin\libomtlmsimulator.dll (0x016a0000)
```

**Comment by lochel** [comment]
@max-privato Sorry that it took us so long, but I think it is fixed now. Please reopen the issue if you still have problems.
