### ISSUE TITLE
Crash after adding submodel using OMSimulator on API Qt

### ISSUE THREAD

**Issue by AlanHascoet-Hack** [OpenModelica/OMSimulator#1031]
### Description

When adding an FMU submodel of Dymola / modelica in the Qt API, the program crashes without any errors or indications. I opened the debugger and it says: "Unauthorized exception at 0x000007feccb3040 in Project_type_FMU.exe: 0xC0000005: Access violation while reading location 0xffffffffffffffff"

The same program with other FMUs works fine so I don't see where the problem comes from and I don't understand the error except that it comes from the dll (OMSimulator).

### ScreenShots

![Capture](https://user-images.githubusercontent.com/63499659/121499251-80281d00-c9dd-11eb-8c60-5024462d09ca.PNG)
After that the application crashes without any information or warning message.

### Version and OS

- Version: [OMSimulator v2.1.0-dev-173-g39d81c6-win]
- OS: [Win7, 64bit]

**Comment by adeas31** [comment]
As you mentioned the program works fine with other FMUs so this is something related to a specific FMU. In that case please attach the FMU so we can debug more.
