### ISSUE TITLE
Reupload FMI Cross Check results for OMSimulator v2.1.1

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#1041]
### Description

Because of https://github.com/OpenModelica/OMSimulator/issues/789 and very long path names in the FMI-Cross-Check [a lot of FMUs](https://github.com/modelica/fmi-cross-check/tree/master/results/2.0/me/win64/OMSimulator/v2.1.1) could not be simulated with the current test script. By changing the script a bit to use shorter FMU names we should get a more realistic result for OMSimulator v2.1.1.

By copying the FMU to e.g. `D:/`, simulating it there and copying the results back we should get around this issue for now.

### Version and OS

- Version: OMSimulator v2.1.1
- OS: Windows 10

**Comment by lochel** [comment]
All the failures due to too long file names are gone. Now it is just a matter of re-generating the results for the old version 2.1.1.
