### ISSUE TITLE
New unnecessary dependency breaks most builds

### ISSUE THREAD

**Issue by sjoelund** [OpenModelica/OMSimulator#109]
084d18f75a500b1581890c54228bd6bf583acd37 introduced a dependency on libxml2-dev, but the 3rdParty sources already include an XML parser: PugiXML. I would strongly suggest changing the code to use PugiXML everywhere, or ifdef the code so that either can be used. It is currently the only dependency that is not included in the project itself and might not be available for static linking on the build machine. Currently, the ARM builds are broken; as are the OM library coverage jobs.

**Comment by lochel** [comment]
@robbr48 What is the status of this issue? I think you pushed some PR related to libxml2, right?

**Comment by robbr48** [comment]
Yes, libxml2 is alraedy compiled on Linux in 3rdParty repository. I believe only correct include path is missing.  I just created a PR for this.
