### ISSUE TITLE
Add *.ssm file as newResource to existing SSP

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#1095]
I have tried to use the python API function "oms.newResources("newResources.root:root.ssv")" to add a new ssm file. I get the following error when I try to add the file

"file extension for....must be ".ssv", no other formats are supported"

Is there some other API function for adding ssm files or is this a feature that needs to be added?

OMSimulator version: "v2.1.1.post125-g0a8710d-linux"

@arun3688 @lochel

**Comment by arun3688** [comment]
@robha67 , Currently we support only adding ".ssv" files using `oms_newResources` API,  We do not support adding ".ssm" files using `oms_newResources`, But you can use  `oms_addResources` API to add an external `.ssv or .ssm` files to an existing SSP something like below 

`oms_addResources("addExternalResources", "../../resources/externalRoot.ssv")
`

**Comment by robha67** [comment]
That works perfectly. Thank you.
