### ISSUE TITLE
SSM reference does not appear in SSD when using the oms.referenceResources API command

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#1096]
I have added SSV and SSM files to an existing SSP via the following

oms.addResources("model.root","Conf1.ssv")
oms.addResources("model.root","Model_Conf1.ssm")

I then try to "activate" the ssv and ssm files using 

oms.referenceResources("model.root:Conf1.ssv", "Model_Conf1.ssm")

This appears as succesfull as I have gotten no Error messages. I then export a new SSP using

oms.export("model","*.ssp")

However, when inspecting the ssd file I see no pointer to the ssm file. The ssv file is however referenced.

@lochel @arun3688

**Comment by arun3688** [comment]
@robha67 can you send the python script, so that i can see the problem

**Comment by robha67** [comment]
@arun3688 I will email you the python script. Thanks

**Comment by arun3688** [comment]
@robha67 I could able to reproduce the issue with the test case you provided and it was a small bug in the code. This PR #1098 should fix the issue. Thanks @robha67  for testing and reporting the issue

**Comment by arun3688** [comment]
@robha67 The PR is merged into master, You can start testing

**Comment by robha67** [comment]
Perfect. I will test the functionality as soon as possible

**Comment by robha67** [comment]
The functionality works perfectly on my use-case. Thank you!
