### ISSUE TITLE
String parameter support

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#1114]
Functionality enabling the specification of string parameters in FMUs

**Comment by lochel** [comment]
Thanks for the request, @robha67. Just to clarify: you want have support for `fmi2SetString`, right?

**Comment by robha67** [comment]
Yes, I believe that that is what I want :) I do not have such an FMU yet but I am working on it

**Comment by lochel** [comment]
@robha67 It is now implemented. This is an example of how to get/set string parameters: [str_hello_world.py](https://github.com/OpenModelica/OMSimulator/blob/master/testsuite/simulation/str_hello_world.py)
