### ISSUE TITLE
Python object-oriented API lacks Model.stepUntil()

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OMSimulator#1126]
### Description
According to the [docs](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/omsimulator.html#omsimulatorpython), OMSimulatorPython offers also an object-oriented API. This is great because it feels a _little_ more pythonic to use.

The methods in the `Model` class has simulation control methods that mirror [these](https://github.com/OpenModelica/OMSimulator/blob/d92d4ff075cdff76ac154186c87eead8d3b027ad/src/OMSimulatorLib/Model.h#L99-L105), [with the exception of](https://github.com/OpenModelica/OMSimulator/blob/d92d4ff075cdff76ac154186c87eead8d3b027ad/src/OMSimulatorPython/Model.py#L24-L52) `stepUntil(stopTime)`, which apparently has been overlooked.

### Steps to reproduce the behavior

Follow the Python OO API example slightly below the link above, only instead of `model.simulate()`, use `model.stepUntil(0.1)`, which should be equivalent.
Instead, you encounter `AttributeError: 'Model' object has no attribute 'stepUntil'`

### Expected behavior

Simulation runs until time 0.1.

*NB: I know about the workaround of falling back to the other kind of API, but this mixes APIs which I don't consider a good practice. (`oms.OMSimulator().stepUntil('model', 0.1)`)*

### Version and OS

- Version: omsimulator 2.1.1.post125 from PyPI
- OS: e.g. Win10, 64bit

**Comment by lochel** [comment]
This is fixed and there is now a new pypi package with version number 2.1.1.post146 available.

**Comment by bilderbuchi** [comment]
Wow, thanks for the quick fix!
