### ISSUE TITLE
Cannot update variable start value in instantiated state

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OMSimulator#1138]
### Description
It does not seem to be possible to set the value of a state variable in an instantiated fmu.

The [docstring ](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/omsimulator.html#id143)of `setReal` (Python API) says: 
> Sets the value of a given real signal.
>
> status = oms.setReal(cref, value)
>
> This function can be called in different model states:
>
 >   Before instantiation: setReal can be used to set start values or to define initial unknowns (e.g. parameters, states). The values are not immediately applied to the simulation unit, since it isn't actually instantiated.
>
>    After instantiation and before initialization: Same as before instantiation, but the values are applied immediately to the simulation unit.
>
>    After initialization: Can be used to force external inputs, which might cause discrete changes of continuous signals.

It seems that contrary to that, in the state after instantiation and before initialization, this is currently broken, as I can't seem to set values.  
Also contrary to the docstring, if applied before instantiation, the value seems to be _in fact immediately applied_.

### Steps to reproduce the behavior

```modelica
model Issue_FMU_update_vars
  Real var;
  Real var_with_start_nonfixed(start=2.2, fixed=false);
  Real var_with_start_fixed(start=4.4, fixed=true);
  Real var_with_start_param(start=startparameter, fixed=true);
  parameter Real startparameter = 6.6;
equation
  der(var) = 1.0;
  der(var_with_start_nonfixed) = 2.0;
  der(var_with_start_fixed) = 4.0;
  der(var_with_start_param) = 6.0;
end Issue_FMU_update_vars;
```
(Variables beside `var` were just used for exploring the issue)

```python
import OMSimulator as oms

fmu_location = 'Issue_FMU_update_vars.fmu'
model = oms.newModel("model")
root = model.addSystem('root', oms.Types.System.SC)
fmu = root.addSubModel('fmu', fmu_location)
print(f'Model state: {model.modelState}')
print(f'Initial value: {fmu.getReal("var")}')
fmu.setReal('var', 11.0)
print(f'After setReal: {fmu.getReal("var")} - works but wasteful to always destroy a model for repeated runs')

model.instantiate()
print(f'Model state: {model.modelState}')
print(f'After instantiate: {fmu.getReal("var")}')
fmu.setReal('var', 22.0)
print(f'After setReal: {fmu.getReal("var")} - value did not "take" in instantiated state')

model.initialize()
print(f'Model state: {model.modelState}')
print(f'After initialisation: {fmu.getReal("var")}')
fmu.setReal('var', 33.0)
print(f'After setReal: {fmu.getReal("var")} - works but could cause consistency issues')
```
Output: 
```
Model state: ModelState.VIRGIN
Initial value: 0.0
After setReal: 11.0 - works but wasteful to always destroy a model for repeated runs
Model state: ModelState.INSTANTIATED
After instantiate: 11.0
After setReal: 11.0 - value did not "take" in instantiated state
info:    maximum step size for 'model.root': 0.001000
info:    Result file: model_res.mat (bufferSize=10)
Model state: ModelState.SIMULATION
After initialisation: 11.0
After setReal: 33.0 - works but could cause consistency issues
...
```
### Expected behavior
In state INSTANTIATED, setting variables actually updates their value. 
Curiously, this works in VIRGIN and SIMULATION, just not in INSTANTIATED.

I know it works if I use a parameter to set the start value, but that is not always feasible. Also, even OMEdit lets me adjust the value & resimulate without a parameter, so I think this should work as expected.

### Version and OS

- Version: 2.1.1.post146
- OS: Win10, 64bit

**Comment by lochel** [comment]
Thanks @bilderbuchi, I can reproduce the issue and will now look into it.

**Comment by arun3688** [comment]
@bilderbuchi, the problem is not related with `OMSimulator`, but rather related to `OpenModelica `fmi-export, we did some testing and found that OMSimulator works correctly on Dymola generated fmus where we can do `setReal` on state vars. We will now investigate our `OpenModelica` fmi-export.

**Comment by bilderbuchi** [comment]
Thanks for the update!

**Comment by arun3688** [comment]
@bilderbuchi the issue is fixed with this PR https://github.com/OpenModelica/OpenModelica/pull/8696, You can test it from the nightly builds tomorrow(16-03-2022)

**Comment by bilderbuchi** [comment]
Thanks, I will!

**Comment by bilderbuchi** [comment]
Confirmed fixed, thank you!
