### ISSUE TITLE
Variable names in results file, gets an whitespace added

### ISSUE THREAD

**Issue by Fredrik1Haider** [OpenModelica/OMSimulator#1153]
### Steps to reproduce the behavior

Reading the results file (an .csv) with python pandas.read_csv, the variable names contain an additional whitespace and quotation marks in front on the name, comes out as:

`'" model.root.anVariable"'`

Thus, requiring "filtering" to make it consistent with naming in ssm etc.

### Expected behavior

Comes out as:
`'model.root.anVariable'`

### Version and OS

- Version: [`OMSimulator --version`]
- Python: [v3.6]
- OS: [Linux 64bit]

**Comment by arun3688** [comment]
@Fredrik1Haider the issue is fixed with this commit https://github.com/OpenModelica/OMSimulator/commit/86bee651f7eebbc1db55a0f6521edcc34478ee21, please test it

**Comment by Fredrik1Haider** [comment]
@arun3688 tested and works as requested, thank you!
