### ISSUE TITLE
Logfile not closed after terminating simulation?

### ISSUE THREAD

**Issue by Fredrik1Haider** [OpenModelica/OMSimulator#1184]
### Description

When appending data to the logfile generated by `OMS.setLogFile`, the appended text gets cutoff suggesting the file has not been closed properly after terminating the simulation, i.e. the file writing buffer is still open. 

### Steps to reproduce the behavior

```
additional_info = ["Very important to know", "Where am I?", "How did I end up here?"]

OMS.setLogFile('log.txt')
OMS.simulate...
OMS.terminate...

with open(log.txt, 'a') as logfile:
      logfile.write("\n".join(additional_info))
```

in resulting file parts of `additional_info` is missing.

### Version and OS

- Version: [`OMSimulator from 2022-05-09`]
- Python 3.6.6, CentOS7

**Comment by lochel** [comment]
Thank you for reporting this, @Fredrik1Haider. The log file in OMSimulator is not specific to a particular model or simulation instance; it applies to the entire OMSimulator session. However, you can explicitly close the log file by setting a new log file name. Setting it to an empty string will redirect all output back to stdout/stderr. Here's an updated version of your example:

```python
import OMSimulator

OMS = OMSimulator.OMSimulator()

OMS.setLogFile('log.txt')
OMS.newModel("model")
OMS.simulate("model")
OMS.terminate("model")

OMS.setLogFile('')  # Close log file and redirct future messages to stdout/stderr

additional_info = ["Very important to know", "Where am I?", "How did I end up here?"]
with open('log.txt', 'a') as logfile:
  logfile.write("\n".join(additional_info))
```

I hope this clarifies how to manage the log file. Let me know if you have any further questions!
