### ISSUE TITLE
Report default values of parameters in OMSimulator --help output

### ISSUE THREAD

**Issue by casella** [OpenModelica/OMSimulator#1265]
OMSimulator has [many flags](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omsimulator.html#omsimulator-flags), which are output by calling `OMSimulator --help`. These flags all have default values, set by [oms::Flags::setDefaults()](https://github.com/OpenModelica/OMSimulator/blob/c920c759070def9ee61449dc2eb4b944bdaea328/src/OMSimulatorLib/Flags.cpp#L64), which are however not visible from the documentation.

We should make sure that `OMSimulator --help` calls `[oms::Flags::setDefaults()` and then displays the actual default values in the on-screen documentation. Then, we should updated the [online documentation](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omsimulator.html#omsimulator-flags) accordingly.

**Comment by lochel** [comment]
This is addressed by #1394.
