### ISSUE TITLE
CVODE should not be reset after each time step in OMSimulator, unless events were triggered

### ISSUE THREAD

**Issue by casella** [OpenModelica/OMSimulator#1270]
When simulating ME-FMUs with OMSimulator using CVODE, the timestepping mechanism is reset at each time step, restarting from a very small value. This only makes sense if an event was triggered, otherwise the simulation should restart with the same time step it used previously.

**Comment by lochel** [comment]
@casella I believe this has been resolved with the new implementation of event handling. Could you share how you originally identified the issue and suggest a way to verify that the behavior now meets expectations?

**Comment by casella** [comment]
Unfortunately I can't remember what triggered this observation. Ticket #10745 probably contains some useful information about that.

The point here is to compare native OMEdit/OMC simulations using CVODE with the simulations ran by OMSimulator on exported FMI-ME FMUs. The number of variable step-size solver steps and ultimately the simulation time should be comparable. 

It is also essential to set up OMSimulator so that the same communication interval is used, otherwise a very small default communication interval may lead to humongous simulation times and result file sizes.

@lochel, based on the comments in 10745, l I would suggest you to take `Buildings.Airflow.Multizone.Examples.CO2TransportStep` as a test case for that. Please check if you can now get similar performance when using CVODE in OMC and when simulating the FMU-ME with OMSimulator and the same tolerance and reporting interval settings.

Thanks!

**Comment by lochel** [comment]
OpenModelica
```
solver: cvode
    656 steps taken
    741 calls of functionODE
    17 evaluations of jacobian
    4 error test failures
    0 convergence test failures
```

OMSimulator
```
> OMSimulator CO2TransportStep.fmu --stopTime=86400 --intervals=500
info:    maximum step size for 'model.root': 172.800000
info:    Result file: model_res.mat (bufferSize=10)
info:    Variable model.root.CO2TransportStep.CO2SenEas.substanceName will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.CO2TransportStep.CO2SenTop.substanceName will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.CO2TransportStep.CO2SenWes.substanceName will not be stored in the result file, because the signal type is not supported
info:    Variable model.root.CO2TransportStep.sou.substanceName will not be stored in the result file, because the signal type is not supported
info:    Final Statistics for 'model.root':
         NumSteps = 505 NumRhsEvals  = 515 NumLinSolvSetups = 36
         NumNonlinSolvIters = 514 NumNonlinSolvConvFails = 0 NumErrTestFails = 1
```

**Comment by lochel** [comment]
And here is a randomly picked signal for comparing the OpenModelica simulation to OMSimulator:

![image](https://github.com/user-attachments/assets/8975b1d4-daca-4ff8-ab14-71b08a2ce372)
