### ISSUE TITLE
FMU not working in OMSimulator with python interface

### ISSUE THREAD

**Issue by Primkins** [OpenModelica/OMSimulator#1283]
### Description

OMSimulator(V2.1.1) with python interface is having issues in reading the FMU created in Openmodelica(V1.23.0) on windows 11 system.
### Steps to reproduce the behavior

Create a Step block FMU in Openmodelica (V1.23.0), and try to run in  OMSimulator (V2.1.1)  with python interface. it fails.
Create a Step block FMU in Openmodelica (V1.14.0), and try to run in  OMSimulator (V2.1.1)  with python interface. it runs.
```python
error: [fmiLogger] module FMICAPI: Could not load the FMU binary: The specified module could not be found.
```

### Screenshots

![image](https://github.com/OpenModelica/OMSimulator/assets/162120981/e3d8ff98-492e-4d86-8db6-d06aee21f5eb)

### Version and OS

- Version: [`OMSimulator --2.1.1`]
- Version: [`Openmodelica --1.23.0`]
- OS: [`Win11, 64bit`]

**Comment by Primkins** [comment]
Pip fails on installing the OMSimulator-V2.1.1.post248 with this URL
https://[build.openmodelica.org/omsimulator/nightly/win-msvc64/OMSimulator-win64-v2.1.1.post248-gf7c50c9.zip]. Please share the URL
.

**Comment by arun3688** [comment]
@Primkins ok i see that you are using pip package, the pip package is not updated yet, I will make a new release in pip today

**Comment by Primkins** [comment]
Is this updated??

**Comment by arun3688** [comment]
no not yet, unfortunately I am little bit busy with some works, I will try to fix this week

**Comment by arun3688** [comment]
@Primkins but if you are using OpenModelica you can use the latest OMSimulator from there

**Comment by Primkins** [comment]
I require OMSimulator for running the FMU from python.

**Comment by Primkins** [comment]
https://[openmodelica.org](https://openmodelica.org/)/ site is down.

**Comment by arun3688** [comment]
@Primkins yes it is down, i guess some server issue, it will be fixed soon

**Comment by arun3688** [comment]
@Primkins the site is back online https://openmodelica.org/

**Comment by Primkins** [comment]
Thank you

**Comment by Primkins** [comment]
Has this been updated?

**Comment by arun3688** [comment]
@Primkins No I am little busy with other works, I will be free in the middle of this week and see if i can fix it, it seems the zip files are not uploaded to server and that is the issue, i need to look into it

**Comment by Primkins** [comment]
OK. Thank you

**Comment by adrpo** [comment]
Ah, it might also be that Windows 11 has changed the way it searches for dlls. I think @AnHeuermann has looked into it and fixed it in the fmi4c library but we will need to port that change to OMSimulator.

**Comment by Primkins** [comment]
OK. Thank you. I will check.

**Comment by arun3688** [comment]
> Ah, it might also be that Windows 11 has changed the way it searches for dlls. I think @AnHeuermann has looked into it and fixed it in the fmi4c library but we will need to port that change to OMSimulator.

Yes i will update the submodule

**Comment by Primkins** [comment]
Installed the OpenModelica-V1.23 nightly build version (OpenModelica-v1.23.0-dev-376-g4df9b45477-64bit.exe) and created the BouncingBall.fmu
Copied the OMSimulator folder under python installed location (C:\Python38\Lib\site-packages).

Upon running the bouncing ball fmu from python, below error is displayed

status:  [correct] ok
status:  [correct] ok
error:   [validateFMU] could not load the ssd schema file: C:/Python38/share/OMSimulator/schema/fmi2/fmi2ModelDescription.xsd
error:   [terminate] Model "test" is in wrong model state
status:  [correct] ok
Loading DLL failed: D:\TestFMU\test_tmp\test-qc3mkx2u\temp\0001_A\binaries\win64\BouncingBall.dll
Failed to load functions for FMI 2.info:    fmi2Instantiate() failed
Function "fmi2FreeInstance" is not provided by this FMU.
info:    0 warnings
info:    2 errors

**Comment by arun3688** [comment]
@Primkins Submodule `OMSimulator` is not pushed to OpenModelica master yet, This PR https://github.com/OpenModelica/OMSimulator/pull/1284 got stuck for some unknown reason, Hopefullly this will be fixed by today

**Comment by arun3688** [comment]
@Primkins the pip package is fixed now and the latest `OMSimulator` version is published to pip https://pypi.org/project/OMSimulator/2.1.1.post257/, please update your `omsimulator`  pip package and test it and also download the latest openmodelica nightly builds from tomorrow and export the fmu's and hopefully everything should work, I did some testing and it works from my side

**Comment by Primkins** [comment]
The issue has been resolved. Thanks
