### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#1296]
### Description

The links to the documentation from the [README](https://github.com/OpenModelica/OMSimulator?tab=readme-ov-file#documentation) are broken.

**Comment by adeas31** [comment]
Here are the correct links [pdf](https://openmodelica.org/doc/OMSimulator/master/OMSimulator/UsersGuide/pdf/OMSimulator.pdf), [html](https://openmodelica.org/doc/OMSimulator/master/OMSimulator/UsersGuide/html/) and [doxygen](https://openmodelica.org/doc/OMSimulator/master/OMSimulator/doxygen/html/index.html).

**Comment by arun3688** [comment]
@adeas31 thanks adeel i wil fix it

**Comment by arun3688** [comment]
@AnHeuermann the issue is fixed with this https://github.com/OpenModelica/OMSimulator/pull/1297
