### ISSUE TITLE
Version packaged with OMEdit has wrong paths on some systems

### ISSUE THREAD

**Issue by bilderbuchi** [OpenModelica/OMSimulator#1306]
I am running OMSimulator from within OMEdit v1.24.0-dev-230-g20a061263e (64-bit), and on simulating an ssp, I get
```
Traceback (most recent call last):
  File "C:/OpenModelica1.24.0-dev-64bit/share/OMSimulator/scripts/OMSimulatorServer.py", line 11, in <module>
    import OMSimulator as oms
  File "C:\OpenModelica1.24.0-dev-64bit\lib\omc\OMSimulator\__init__.py", line 17, in <module>
    Scope._init()
  File "C:\OpenModelica1.24.0-dev-64bit\lib\omc\OMSimulator\Scope.py", line 5, in _init
    _capi = capi()
            ^^^^^^
  File "C:\OpenModelica1.24.0-dev-64bit\lib\omc\OMSimulator\capi.py", line 16, in __init__
    dllDir = os.add_dll_directory(os.path.dirname(omslib))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 1119, in add_dll_directory
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\OpenModelica1.24.0-dev-64bit\\lib\\omc\\OMSimulator\\../../bin'
Simulation process failed. Exited with code 0x00000001.
```
It looks like that path is off by one level, there is one `/..` missing, as the logged path resolves to `C:/OpenModelica1.24.0-dev-64bit/lib/bin'` (which does not exist), not to `C:/OpenModelica1.24.0-dev-64bit/bin'`, which is the intention AFAICT.

This was working in OM 1.23.1

_Originally posted by @bilderbuchi in https://github.com/OpenModelica/OMSimulator/issues/1285#issuecomment-2298682514_

**Comment by bilderbuchi** [comment]
The underlying reason seems that `OPENMODELICA_NEW_CMAKE_BUILD ` is not set when packaging OMEdit, because it supposedly uses the make, not CMake build approach. (https://github.com/OpenModelica/OMSimulator/pull/1285#issuecomment-2298763497)
cc @arun3688

**Comment by arun3688** [comment]
@bilderbuchi the issue is fixed with this commit https://github.com/OpenModelica/OpenModelica/commit/37d54ce0e34e4cdcad57953282405d3d33049f64, please test it from nightly builds tomorrow

**Comment by bilderbuchi** [comment]
Nightly build seem to have failed or been delayed tonight ([current nightly ](https://build.openmodelica.org/omc/builds/windows/nightly-builds/64bit/)is from yesterday). I'll retry another time.

**Comment by bilderbuchi** [comment]
I confirmed that this is fixed, now.
