### ISSUE TITLE
Incorrect error message "FMU "XX" doesn't support co-simulation mode." even thought "model exchange" is the mode that is missing.

### ISSUE THREAD

**Issue by GorbadPS3** [OpenModelica/OMSimulator#1314]
### Description

When I attempt to run an SSP model that looks like this:

![image](https://github.com/user-attachments/assets/9986ddd6-db09-4eca-ad3d-573c420c3599)

It works correctly, as long as the highlighted "Modelica_Blocks..." FMU's modelDescription.xml contains both ModelExchange and CoSimulation definitions.

However, if I remove "ModelExchange" definition from the modelDescription.xml, I am seeing the following error:

_Wed Oct 02 15:40:05 2024 | info:    Initializing logging (OMSimulator v2.1.2.post6-g637a1c9-win-notlm)_
_Wed Oct 02 15:40:05 2024 | error:   [NewComponent] FMU "Modelica_Blocks_Sources_Trapezoid" doesn't support co-simulation mode._

If I remove the "CoSimulation" definition from the modelDescription.xml, then I am not seeing an error.

This suggests that the error message is incorrect. Looking at the class "ComponentFMUME.cpp", it looks like the error message might be wrong there.

### Steps to reproduce the behavior

Try running an FMU model in OMSimulator without ModelExchange, when OMSimulator wants to use ModelExchange.

### Expected behavior

Expected error message to mention that ModelExchange is missing.

### Version and OS

- Version: v2.1.2.post6-g637a1c9-win-notlm
- OS: Win11, 64bit

**Comment by lochel** [comment]
@GorbadPS3 Thanks for the report.
