### ISSUE TITLE
OMSimulator does not export some variables listed in resources/signalFilter.xml

### ISSUE THREAD

**Issue by rruusu** [OpenModelica/OMSimulator#1320]
### Description

Some variables with non-alphanumeric characters, such as square brackets or parentheses, are not exported to the result file, even when explicitly listed in the _resources/signalFilter.xml_ file in the SSP.

### Steps to reproduce the behavior

1. Create an SSP with variables containing square brackets, listen in _signalFilter.xml_.
2. Simulate SSP in OMSimulator.
3. Observe the result file contents.
4. Note missing variables with special characters.

### Expected behavior

All variables listed in _signalFilter.xml_ should be present in the result file.

### Version and OS

- Version: OMSimulator v2.1.2.post6-g637a1c9-win-notlm-debug
  - current HEAD,
- OS: Windows 11, 64-bit

**Comment by rruusu** [comment]
The cause is fairly evident in method [`oms::Model::importSignalFilter`](https://github.com/OpenModelica/OMSimulator/blob/637a1c94a08699b1cf6366a725c14b66d127b72e/src/OMSimulatorLib/Model.cpp#L1573), which sends the `name` attribute of the `oms:Variable` unquoted to a function that expects a regular expression argument.

Thus a name like `"x[1]"` does not actually match the name `"x[1]"`, when interpreted as a regular expression, as it only matches the name `"x1"`.

Luckily, the dots used as separators in the names match with any character, including a dot.

**Comment by lochel** [comment]
I consider this issue resolved. @rruusu, please feel free to reopen if you encounter the same issue again.
