### ISSUE TITLE
RHS function for CVODE calls fmi2SetTime() with wrong time value before calculating state derivatives

### ISSUE THREAD

**Issue by rruusu** [OpenModelica/OMSimulator#1325]
### Description

When simulating a strongly coupled model, the RHS function that is provided to CVODE calls `fmi2SetTime` with the wrong time value before reading the state derivative values.

All evaluations performed by CVODE are made using the end of the previous time step as the time value, which creates strange effects when state derivatives have a direct dependence on the simulation time, for example via an input from a signal source.

### Steps to reproduce the behavior

1. Create a model with state derivatives that depend directly on time
2. Log FMI calls
3. Observe that `fmi2SetTime` is always called with time value that matches one used before previous call to `fmi2CompletedIntegratorStep`

### Expected behavior

The time value provided to [`oms::cvode_rhs`](https://github.com/OpenModelica/OMSimulator/blob/f48ed62ded2514b242cd85898043247d08973e1b/src/OMSimulatorLib/SystemSC.cpp#L43) should be passed to the FMUs using `fmi2SetTime` before the calls to `fmi2GetDerivatives`, but the `fmi2SetTime` calls performed by [`oms::SystemSC::updateInputs`](https://github.com/OpenModelica/OMSimulator/blob/f48ed62ded2514b242cd85898043247d08973e1b/src/OMSimulatorLib/SystemSC.cpp#L670) are made using the field `oms::System::time`, which still has the value of the last completed integrator step.

### Version and OS

- Version: OMSimulator v2.1.2.post5-gce342b6-mingw-notlm-debug
- OS: Windows 11, 64-bit

**Comment by rruusu** [comment]
I have a fix for this that I will push shortly to my fork.

**Comment by lochel** [comment]
@rruusu, thank you for reporting this issue. Since your initial look, the CVODE integration has undergone significant changes, and my recent pull request has further updated how simulation time is managed in strongly connected systems. I encourage you to review the latest changes and share any additional concerns or suggestions for improvement. Let me know if there's anything else that needs attention. Thanks for your help!

**Comment by rruusu** [comment]
This issue seems to still be present in the maintenance/v2.1 branch. Although there is now an `fmi2_setTime` call in [`oms::cvode_rhs`](https://github.com/OpenModelica/OMSimulator/blob/46fa40fcf72dad3513e029bfb34aebf8a4d99e10/src/OMSimulatorLib/SystemSC.cpp#L55) using the correct time value, it is overridden by the later call in [`SytemSC::updateInputs`](https://github.com/OpenModelica/OMSimulator/blob/46fa40fcf72dad3513e029bfb34aebf8a4d99e10/src/OMSimulatorLib/SystemSC.cpp#L956).

**Comment by rruusu** [comment]
I was earlier trying to merge my changes to the master branch, but I had to abandon that as too costly, but now that I am aware that changes there are scheduled for 3.0.0, I will try to put out some pull requests for the maintenance branch.
