### ISSUE TITLE
APIs for getting the start and stop time

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OMSimulator#151]
The exisitng APIs `oms2_setStartTime` and `oms2_setStopTime` creates a following section,

`<ssd:DefaultExperiment startTime="0.000000" stopTime="1.000000" />`

So APIs `oms2_getStartTime` and `oms2_getStopTime` are needed to read these values back.

**Comment by adeas31** [comment]
Fixed in #191

**Comment by lochel** [comment]
Right now only the C API is implemented. We should also add bindings to the Python and Lua interface.
