### ISSUE TITLE
OMSimulator-Windows build

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#153]
Crashes after completed simulation

**Comment by lochel** [comment]
Can share a script to reproduce the crash?

**Comment by robha67** [comment]
Hi again!

The DemonstratorM27_v4 in the OpenCPS trunk OpenCPS_trunk\WP6_Industrial Demonstrators\T6.3 Aircraft vehicle systems demonstrator\DemonstratorM27_v4 crashes once the simulation is finished. I have also tried various other examples with the same results. I get the error in the screenshot below whenever a lua script is finished, regardless if I simulate the model or not. However,  since the tool successfully completes a simulation, it is not that big of an issue.

[cid:image001.jpg@01D3E796.7ECCD4A0]

Best regards
Robert

Från: Lennart Ochel <notifications@github.com>
Skickat: den 9 maj 2018 12:52
Till: OpenModelica/OMSimulator <OMSimulator@noreply.github.com>
Kopia: Robert Hällqvist <robert.hallqvist@liu.se>; Author <author@noreply.github.com>
Ämne: Re: [OpenModelica/OMSimulator] OMSimulator-Windows build (#153)


Can share a script to reproduce the crash?

**Comment by lochel** [comment]
The issue was actually inside the test script.
