### ISSUE TITLE
Merge oms2_terminate and oms2_unloadModel

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#154]
It seems to be unnecessary to have to explicitly call both functions sequentially. My proposal is to merge `oms2_terminate` into `oms2_unloadModel`.

@adeas31 @bernhard-thiele What do you think?

Possible call sequence: `oms2_initialize` -> (`oms2_simulate` | `oms2_simulate_asynchronous`) -> [`oms2_reset` -> `oms2_initialize` -> (`oms2_simulate` | `oms2_simulate_asynchronous`)] -> `oms2_unloadModel`

**Comment by adeas31** [comment]
Sounds good to me.
