### ISSUE TITLE
Oscillations in FMI co-simulation

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#157]
Oacillating behavior for native FMI-based (not TLM) co-simulation of aricraft use-cases. Might be related to issue #18 "Coupling stability".

**Comment by meek1** [comment]
@lochel, aslo oms3 shows oscillations for the aircraft demo. However not exactly the same for 32- and 64-bit.

![image](https://user-images.githubusercontent.com/31110788/48678081-d8c50f80-eb7e-11e8-91bb-15243d93ac4a.png)

**Comment by lochel** [comment]
It seems that this issues can finally be closed. The following three signals were produced without input extrapolation (blue, tol=1e-3), with input extrapolation (red, tol=1e-3), with extrapolation and tighter tolerances (green, tol=1e-6).

![image](https://user-images.githubusercontent.com/8457302/55630171-59467e80-57b5-11e9-8f60-a1105603e556.png)
