### ISSUE TITLE
Allow to specify constant values as FMU input

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#171]
supported in FMI simulator, needs to be implemented in GUI

**Comment by meek1** [comment]
And in TLM simulator?

**Comment by lochel** [comment]
The TLM simulator uses the FMI composite models as building blocks. Therefore, it is also available inside the TLM simulator. @robbr48 I am not sure if there is something like a constant physical connection or if it even makes sense.

**Comment by robbr48** [comment]
No, a delayed constant signal makes no sense. This can be solved using the functionality in FMI composite models. This only works for FMUs of course, so for external tool connections it may need to be implemented in the future.

**Comment by meek1** [comment]
Isn’t this already implemented in the GUI? Maybe not for boolean and integer?

**Comment by lochel** [comment]
It should be kept open.

**Comment by lochel** [comment]
I think it can be closed. The GUI supports it already, and #499 is still open to keep track of the missing SSP support.
