### ISSUE TITLE
Lookup table support

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#172]
Needs to integrate existing FMISimulator implementation. Needs to finalize functionalities like interpolation, configuration, etc.

**Comment by lochel** [comment]
@robha67 What is actually needed? Basic lookup table support is already available using constant interpolation.

**Comment by robha67** [comment]
Hmm,

I think what you implemented is what we need. I guess constant extrapolation is a bit coarse, mayby linear interpolation would be better for performance etc. but I have not tried the functionality yet so I do not really know.

Best regards
Robert

Från: Lennart Ochel <notifications@github.com>
Skickat: den 23 maj 2018 14:49
Till: OpenModelica/OMSimulator <OMSimulator@noreply.github.com>
Kopia: Robert Hällqvist <robert.hallqvist@liu.se>; Mention <mention@noreply.github.com>
Ämne: Re: [OpenModelica/OMSimulator] Lookup table support (#172)


@robha67<https://github.com/robha67> What is actually needed? Basic lookup table support is already available using constant interpolation.

**Comment by meek1** [comment]
Can this one be closed?

**Comment by meek1** [comment]
@lochel, @robha67: Linear interpolation is needed. And preferably constant extrapolation after the last row.

**Comment by lochel** [comment]
@meek1 I planned to implement it for oms3. Is that sufficient?

**Comment by lochel** [comment]
Support for lookup tables with linear interpolation is implemented for oms3 in #449.
