### ISSUE TITLE
Model Exchange mode for FMI simulator

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#173]

**Comment by meek1** [comment]
What is covered by #156 and #161, and what is left? Is this support for wrapping individual FMU-ME into FMU-CS or for running a group of connected FMU-ME with a common solver, or both? Mix of ME and CS FMUs supported?

**Comment by lochel** [comment]
The grouping of FMU-ME units is still missing. Wrapping individual FMU-ME works and can be combined with other FMU-ME and FMU-CS units.

**Comment by lochel** [comment]
This is now available. Please note the new API to utilize this feature:


```Lua
-- instantiate FMUs
oms2_addFMU("DualMassOscillator", "../FMUs/DualMassOscillator.System1_me.fmu", "System1")
oms2_addFMU("DualMassOscillator", "../FMUs/DualMassOscillator.System2_me.fmu", "System2")

-- instantiate solvers
oms2_addSolver("DualMassOscillator", "solver1", "cvode")

-- connect solvers
oms2_connectSolver("DualMassOscillator", "System1", "solver1")
oms2_connectSolver("DualMassOscillator", "System2", "solver1")
```
