### ISSUE TITLE
Coupling stability

### ISSUE THREAD

**Issue by hyumo** [OpenModelica/OMSimulator#18]
I was trying to co-simulate two coupled FMUs from the FMITest library with OMSimulator.  
- FMITest.VirtualLoops.MassSpringDamper.FMUModels.SpringDamper
- FMITest.VirtualLoops.MassSpringDamper.FMUModels.MassWithGravity

It was found that the co-simulation results are quite different comparing to the original Modelica reference model. OMSimulator handles initialization correctly, however, the results seem to be incorrect. I guess it might because inputs are not interpolated in OMSimulator, and I wonder if there are any plans to improve the coupling stability (similar to PyFMI maybe)? Thanks.

**Comment by sjoelund** [comment]
OpenModelica FMI for co-simulation uses forward Euler as the only possible solver. Use model exchange if you want numerically sane results (I assume this would lead to better results anyway; didn't check the actual models).

**Comment by hyumo** [comment]
@sjoelund I see. Thanks for the clarification.
