### ISSUE TITLE
OMSimulator MinGW

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#186]
I get the following error message sporadically when I try to add TLM interfaces.

```
FATAL ERROR: lua_pcall() failed: .\DemonstratorFineGrained.lua:395: attempt to call a number value (global 'input')
```

Sometimes the error message is followed by the following:
```
terminate called after throwing an instance of 'std::length_error'
  what():  deque::_M_new_elements_at_front
```

**Comment by lochel** [comment]
@robbr48 It looks for me like a bug inside the TLM implementation.

**Comment by robbr48** [comment]
The first error message is generated by Lua. It could be a problem when converting the arguments to C and then C++. It uses an array buffer which is converted to a vector.

**Comment by lochel** [comment]
It is related to `input` which is defined as global constant for the TLM lua bindings, right?

**Comment by robbr48** [comment]
Yes, that's true.

@robha67 What does line 395 in your script look like?

**Comment by robha67** [comment]
Hi!

The line is
oms2_addTLMInterface("Demonstrator_FineGrained_fg", "Cockpit", "Cockpit_Inlet.xs", 1, input "Signal", "fmu:Cockpit_Inlet.xs")

This error has showed up sporadically at different places in the composite model description before. However, now it seems to get stuck on this line and if I comment it, I do not have any errors.

/Robert H

Från: robbr48 <notifications@github.com>
Skickat: den 24 maj 2018 12:00
Till: OpenModelica/OMSimulator <OMSimulator@noreply.github.com>
Kopia: Robert Hällqvist <robert.hallqvist@liu.se>; Mention <mention@noreply.github.com>
Ämne: Re: [OpenModelica/OMSimulator] OMSimulator MinGW (#186)


Yes, that's true.

@robha67<https://github.com/robha67> What does line 395 in your script look like?

**Comment by robbr48** [comment]
I think you are missing a comma after the input constant:
input "Signal" -> input, "Signal"

**Comment by robha67** [comment]
Ahhh, give me a break!! That did it, thank you!!

/Robert

Från: robbr48 <notifications@github.com>
Skickat: den 24 maj 2018 14:13
Till: OpenModelica/OMSimulator <OMSimulator@noreply.github.com>
Kopia: Robert Hällqvist <robert.hallqvist@liu.se>; Mention <mention@noreply.github.com>
Ämne: Re: [OpenModelica/OMSimulator] OMSimulator MinGW (#186)


I think you are missing a comma after the input constant:
input "Signal" -> input, "Signal"
