### ISSUE TITLE
Automatic composite model lua script generation

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#187]
Adding TLM connections to FMI models in OMSimulator (via the LUA API) is extremely time consuming for industry grade models.

One solution is to mimic the automatic generation of "fmi.config" files that was used in the previous TLM simulator version. A function that reads extracts the I/O:s from the Model description files and automatically writes the corresponding "oms2_addTLMInterface" statement to a lua file which then can be used as template for the composite model. The parameters that are availble for specification via the API could also be automatically generated and commented in the resulting lua script, i.e --"oms2_setRealParameter(...)"

**Comment by lochel** [comment]
Can we close this issue? I think the GUI helps a lot and can even be combined with the scripting interface by using the SSP import/export.

**Comment by robha67** [comment]
I think IT would be a nice feature but still but for sure not top priority once the gui functions as it should. Mayby a user would like to model without involving OMEdit
