### ISSUE TITLE
Simulation progress info

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#188]
Basic progress info during simulation would be nice, and possibility to store a master CPUtime variable for plotting.

**Comment by lochel** [comment]
There is a progress bar when using graphical clients, i.e. OMEdit. We could add a simple progress bar to stdout when running synchronous simulations from the scripting API.

**Comment by meek1** [comment]
Yes, a simple progress bar for Lua and Python script-based simulations would be good. Also basic profiling info would be nice, e.g. time consumption for simulation, results logging etc. for each fmu (but that is maybe already available by some setting?).

**Comment by meek1** [comment]
@adeas31, maybe this is already available  in the GUI for FMI + TLM?

**Comment by lochel** [comment]
Simulation progress info is now also available in the command line: #535
