### ISSUE TITLE
Min/max limited connections

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#203]
Occasionally FMUs deliver irrelevant outputs due to e.g. poor start values or initialization/stability problems. This may cause problems in downstream FMUs, e.g. that downstream cannot simulate. In some cases a min/max limit on inputs (or outputs) would solve this problem. I.e. downstream FMUs are running on limited inputs until upstream FMUs are stabilized and provides output within expected range.

The min/max limits could be an optional input argument to oms2_addConnection, e.g.:

oms2_addConnection("FMICompositeModel","FMU_A:u1","FMU_B:y1", [min max]).

FMU_A.u1 is then limited to be within the range [min max]. I guess this is only applicable for connections with Real input/output signals.

The user should be provided a warning that indicates which min/max limits have been active during simulation and for which time periods.

**Comment by lochel** [comment]
I agree, this might be a useful functionality. However, this can be realised using special FMUs that do exactly what you described.

**Comment by meek1** [comment]
Yes, true, but similar to #202, it would be more user friendly to provide this support in the master.

**Comment by meek1** [comment]
I try to use a simple limiter-FMU to protect FMU_A:u1 from getting irrelevant very large (>1e300) input from FMU_B:y1 during the first steps of a simulation. The behaviour of the limiter-FMU is not as expected - it is stuck on the lower limit (-100) during the complete simulation.

**Comment by lochel** [comment]
Do you think this is a problem with the limiter-FMU or OMSimulator? Can you provide the testcase for further analysis, including FMUs and test script?

**Comment by meek1** [comment]
Works as expected in a simple test case with a source-FMU and a limiter-FMU, also for very large numbers from the source. But not in the real test case. Maybe it has to do with the numerical handling of ”+/-inf” in the master or in the sending or recieving FMU. What happens if a FMU output is +inf? Max for results plotting seem to be 1e300 but the actual value in the simulation is probably something else. I can provide a test case tomorrow.

**Comment by meek1** [comment]
* limiter_test_simple: Simple test case working as expected.
* limiter_test: "real" rest case not working.

For both test cases - run and plot limiter.u and limiter.y (can also plot limiter.limiter.uMin, limiter.limiter.uMax). Origin to the problem may be poor start values or strange behavior of individual FMUs, however in practial situations this happens and a solution to limit signals like "cp_cpm_out" in the test case is needed in OMSimulator.

[limiter_test_simple.zip](https://github.com/OpenModelica/OMSimulator/files/2079079/limiter_test_simple.zip)
[limiter_test.zip](https://github.com/OpenModelica/OMSimulator/files/2079080/limiter_test.zip)
