### ISSUE TITLE
Smoothing of inputs

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#204]
To reduce the number of internal steps required in variable step CS FMUs and in some cases enhance numerical stability, the master should provide functionalities for smoothing of FMU inputs.

Several approaches can be considered, e.g. various low pass filters but also use of directional derivatives when such are available. See e.g. Section 6.3 in http://ctr.maths.lu.se/na/staff/chria/phdthesis.pdf

**Comment by meek1** [comment]
@lochel, this would be really nice, related to current work of using derivatives. Question - would also be really good to be able to extract info on number on internal steps per master step for e.g. FMU-CS with Cvode. Is this possible with current FMUs and solvers?

**Comment by lochel** [comment]
It should be kept open.

**Comment by meek1** [comment]
@robbr48 maybe you should have this feature in mind when designing IVA? Smoothing and other derivative related master features should be possible both with and without IVA.

**Comment by robbr48** [comment]
With the current proposal, the internal solver should not be forced to do anything. The FMU simply pauses the execution while the master tool reads/writes intermediate variables. How this is implemented internally in the FMU is up to the exporting tool to decide.

**Comment by meek1** [comment]
Should be kept open. @lochel, @robbr48: Any plans for this inte? Maybe a student summer job, project, or master thesis to develop and benchmark various smoothing techniques?

**Comment by lochel** [comment]
That would be great. All issues marked as `stale` are part of the backlog and this particular one is even rather high on my list. It will be reopened once someone is actually working on it.

**Comment by meek1** [comment]
@lochel, @robbr48 now is a good time to formulate thesis works. Maybe a project or two at LiU to enhance OMSimulator? Eg smoothing.
