### ISSUE TITLE
Turning off FMIlogging

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#205]
When the logging of any of the FMI submodels included in a TLM composite model is turned off using
oms2_setResultFile("ConsumerA_FMI",""),  then the lua script is executed without producing any simulation results or log files. No error messages are communicated.

**Comment by lochel** [comment]
I think this is a bug that was fixed with #236. @robha67 Can you please verify if it works now for you?

It is now also possible to “subsample” the result file using the new API `oms2_setLoggingInterval(“model”, loggingInterval)`. See #169 for more information.

**Comment by lochel** [comment]
@robha67 Is it now working for you?
