### ISSUE TITLE
Cannot access FMU top level parameters

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#206]
The top level parameter P in FMU signal_modifyer cannot be accessed in OMSimulator and is not stored in the result file. However, when importing the FMU in other tools then P is seen and can be modified.

oms2_setRealParameter("AVSDemo.signal_modifyer:P",3) gives error: No such parameter: P

[log_and_FMU.zip](https://github.com/OpenModelica/OMSimulator/files/2059993/log_and_FMU.zip)

**Desktop (please complete the following information):**
 - OS: Win7
 - Version: OMSimulator` v0.1.0-429-gbd514e7

**Comment by adeas31** [comment]
Yeah because the parameter is an `Integer` not `Real` so use `oms2_setIntegerParameter`.

**Comment by meek1** [comment]
Oops, thanks! :)

**Comment by adeas31** [comment]
Ahhh because there is no lua binding for `oms2_setIntegerParameter` API.

**Comment by adeas31** [comment]
PR #210 allows setting the integer parameters. However, I get the error,
> Parameter signal_modifyer.P will not be stored in the result file, because the signal type is not supported

@lochel is there a reason for not storing the integer parameters to the result file?

**Comment by lochel** [comment]
This is only implemented for type real right now. But there is no good reason to skip the other types actually.

**Comment by adeas31** [comment]
See #216 and #217.
