### ISSUE TITLE
Modification of modelDescription.xml has no effect

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#208]
Unzipping an FMU and modifying parameter values in modelDescription.xml has no effect when the updated FMU is added and used OMSimulator.

1) Unzip FMU
2) Open modelDescription.xml and modify a parameter value (seems to be the same for input start values but this has to be confirmed)
3) Zip again and rename file extension to .fmu
4) Add updated FMU to an FMI composite model and simulate

**Comment by meek1** [comment]
Is this covered by #215 update?

**Comment by lochel** [comment]
I did some testing myself and can confirm that the start values given inside the modelDescription.xml are not used in all cases. Anyway, I will close this, since it seems to be an issue of the implementation of the FMUs itself.
