### ISSUE TITLE
Split result files corrupt

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#220]
When I try to run several simulations in sequence in a Lua script, the simulations seem to run properly but the second result file cannot be opened. My interpretation of #169 is that this should already be working. Lua example below, probably something I did wrong here? Files result_4.mat, result_5.mat, and log attached.

[result_files_and_log.zip](https://github.com/OpenModelica/OMSimulator/files/2073853/result_files_and_log.zip)

```Lua
--simulationsettings
-- *** 1s run ***
oms2_setResultFile("AVSDemo","result_4.mat")
oms2_setStopTime("AVSDemo",0.02)
oms2_initialize("AVSDemo")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)
oms2_setCommunicationInterval("AVSDemo", 1e-2)
oms2_simulate("AVSDemo")

-- *** 2nd run ***
oms2_setResultFile("AVSDemo","result_5.mat")
oms2_setStopTime("AVSDemo",0.02)
--oms2_initialize("AVSDemo")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)
oms2_setCommunicationInterval("AVSDemo", 1e-3)
oms2_simulate("AVSDemo")

-- *** End ***
oms2_terminate("AVSDemo")
oms2_unloadModel("AVSDemo")
```

**Comment by lochel** [comment]
I guess the second simulation result is empty, because the simulation runs from startTime=0.02 to stopTime=0.02. You can call `oms2_terminate` and `oms2_initialize` between the two simulations.

**Comment by meek1** [comment]
Tried some variants but results in:

****
Tue Jun 05 22:37:50 2018 | info:    Initializing logging (OMSimulator v0.1.0-458-gd55c977)
Tue Jun 05 22:37:50 2018 | info:    New temp directory: "C:/OpenCPS\work\DemonstratorFITS_M30_v4_FMI\AVSDemo_tmp"
Tue Jun 05 22:37:52 2018 | info:    Result file: result_1.mat
Tue Jun 05 22:37:52 2018 | info:    oms2::FMICompositeModel::stepUntil: Using master algorithm 'standard'
Tue Jun 05 22:37:54 2018 | info:    oms2::FMICompositeModel::stepUntil: Using master algorithm 'standard'
Tue Jun 05 22:38:07 2018 | info:    Simulation finished.
Tue Jun 05 22:38:07 2018 | warning: AVSDemo.bC (): fmi2SetTime: not allowed in this state
Tue Jun 05 22:38:07 2018 | warning: AVSDemo.bC (): model cannot be initialized in current state(7)
Tue Jun 05 22:38:07 2018 | error:   fmi2_import_enter_initialization_mode failed
Tue Jun 05 22:38:07 2018 | error:   [oms2::FMICompositeModel::initialize] failed
Tue Jun 05 22:38:07 2018 | error:   [oms2::Model::stepUntil] Model cannot be simulated, because it isn't initialized.
Tue Jun 05 22:38:07 2018 | error:   [oms2::Model::simulate] Model cannot be simulated, because it isn't initialized.
Tue Jun 05 22:38:07 2018 | warning: AVSDemo.bC (): fmi2Terminate: already terminated, ignoring call
Tue Jun 05 22:38:07 2018 | error:   fmi2_import_terminate failed
Tue Jun 05 22:38:07 2018 | warning: AVSDemo.cockpit (): fmi2Terminate: already terminated, ignoring call
Tue Jun 05 22:38:07 2018 | error:   fmi2_import_terminate failed
****
E.g.
-- *** 1s run ***
oms2_setResultFile("AVSDemo","result_1.mat")
oms2_setStopTime("AVSDemo",0.02)
oms2_initialize("AVSDemo")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)
oms2_setCommunicationInterval("AVSDemo", 0.5e-2)
oms2_simulate("AVSDemo")
oms2_terminate("AVSDemo")

-- *** 2nd run ***
oms2_initialize("AVSDemo")
oms2_setResultFile("AVSDemo","result_2.mat")
oms2_setStopTime("AVSDemo",0.02)
--oms2_initialize("AVSDemo")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)
oms2_setCommunicationInterval("AVSDemo", 1e-2)
oms2_simulate("AVSDemo")
oms2_terminate("AVSDemo")

**Comment by lochel** [comment]
Okay, I expected that to work actually. I'll test it myself and see what's wrong.

**Comment by meek1** [comment]
@lochel, now the example below works. Two result files are generated and can be opened. I only call initialize and terminate once. Did you figure out why above example didn't work?

***
oms2_setResultFile("AVSDemo","result_part1.mat")
oms2_setStopTime("AVSDemo",1)
oms2_initialize("AVSDemo")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)
oms2_setCommunicationInterval("AVSDemo", 1e-3)
oms2_stepUntil("AVSDemo", 1e-2)
oms2_setResultFile("AVSDemo","result_part2.mat")
oms2_setCommunicationInterval("AVSDemo", 8e-3)
oms2_simulate("AVSDemo")
***

**Comment by lochel** [comment]
I think one has to use the `oms2_reset()` function in the first scenario. However, I had no time yet to test it myself.

**Comment by lochel** [comment]
This should work:

```Lua
-- *** setup model ***
[...]

-- *** 1st run ***
oms2_setResultFile("AVSDemo","result_1.mat")
oms2_setStopTime("AVSDemo",0.02)
oms2_initialize("AVSDemo")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)
oms2_setCommunicationInterval("AVSDemo", 0.5e-2)
oms2_simulate("AVSDemo")

-- *** reset simulation ***
oms2_reset("AVSDemo")

-- *** 2nd run ***
oms2_setResultFile("AVSDemo","result_2.mat")
oms2_setStopTime("AVSDemo",0.02)
oms2_initialize("AVSDemo")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)
oms2_setCommunicationInterval("AVSDemo", 1e-2)
oms2_simulate("AVSDemo")

-- *** terminate simulation ***
oms2_terminate("AVSDemo")
oms2_unloadModel("AVSDemo")
```

**Comment by lochel** [comment]
Please reopen this issue if there is still a problem.
