### ISSUE TITLE
Should the oms2 prefix be removed?

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#223]
The new API is using the prefix `oms2_`. This is not really needed, because the old API is removed completly. Should we remove the `oms2_` prefix before doing the release? I think it would make things slightly nicer.

**Comment by lochel** [comment]
@adeas31 @adrpo @robbr48 @meek1 @robha67 Any opinions?

**Comment by meek1** [comment]
Agree, I think it’s a good idea to remove it, if not too much work. Does this mean that no prefix will be used or will it be oms_?

**Comment by lochel** [comment]
I would propose to use `oms_` as a prefix for the C API and no prefix for the Python and Lua interface.

**Comment by adeas31** [comment]
+1 from side.

**Comment by bernhard-thiele** [comment]
I'm not so sure whether one should go without prefix for the Lua API. There are some quite generic API functions like `oms2_rename` or `oms2_reset` that might conflict with other names in the scope if the prefix is dropped...

**Comment by lochel** [comment]
Good point actually. I think we could use something like a namespace "OMSimulator" instead: https://stackoverflow.com/questions/4394303/how-to-make-namespace-in-lua
