### ISSUE TITLE
Limit size of log file

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#227]
When warnings and errors during simulation, the log file grows rapidly (and unlimited?). Suggest to limit file size to xx Mb (or number of messages/lines, etc.), so it can be opened in text editors and doesn't fill the harddrive.

**Comment by meek1** [comment]
Is it possible to turn off logging? What are the options for oms2_setLoggingLevel?

**Comment by lochel** [comment]
The options are:
* 0: default
* 1: default+debug
* 2: default+debug+trace

It is not possible to disable it, but to redirect it to stdout (`oms2_setLogFile("")`), which means no log file is created.

I will add an option to limit the logging output to a given number of messages.

**Comment by sjoelund** [comment]
I guess we would need more log levels, so you can reduce the messages compared to the default, with 0 being disabled or so. Or some option to disable a category of messages

**Comment by lochel** [comment]
Not sure if that is needed right now. But we can open a new issue to discuss it.

**Comment by lochel** [comment]
This was a bug in the logging module. The log files shouldn't grow that much anymore.
