### ISSUE TITLE
Result file resolution specification, TLM connections

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#228]
Long simulations will result in very large result files if variables are stored at each communication point. Expanding the Lua API to such that the result file resolution can be specified is essential. This is important for all logging but this issue particulalry concerns the top level composite model logging conducted via TLM connections

**Comment by lochel** [comment]
All the FMI related issues are addressed in #169. @robbr48 What about the TLM result file?

**Comment by robbr48** [comment]
It is possible to control either number of log samples or logging interval. @robha67 Is this enough, or do we need more advanced features?

**Comment by robha67** [comment]
This is enough from my point of view at least

/Robert H

Från: robbr48 <notifications@github.com>
Skickat: den 14 juni 2018 12:54
Till: OpenModelica/OMSimulator <OMSimulator@noreply.github.com>
Kopia: Robert Hällqvist <robert.hallqvist@liu.se>; Mention <mention@noreply.github.com>
Ämne: Re: [OpenModelica/OMSimulator] Result file resolution specification, TLM connections (#228)


It is possible to control either number of log samples or logging interval. @robha67<https://github.com/robha67> Is this enough, or do we need more advanced features?
