### ISSUE TITLE
Lua function for selecting number of log samples in OMTLMSimulator

### ISSUE THREAD

**Issue by robbr48** [OpenModelica/OMSimulator#231]
**Is your feature request related to a problem? Please describe.**
Result files after TLM simulations can grow very large. User should be able to control number of samples from Lua scripts.

**Describe the solution you'd like**
Add an setTLMLogSamples() function to Lua API.

**Comment by meek1** [comment]
@robbr48, @lochel: please coordinate on #169. We need similar functionality (same API functions?) for both FMI and TLM parts, i.e. on OMSimulator level.

**Comment by lochel** [comment]
We have now `oms2_setLoggingInterval()" that works for TLM and FMI models. In case of TLM it is propagated to all FMI sub-models.

And then we have also `setTLMLogSamples()` which only works for TLM models (and doesn't propagate to FMI sub-models). 

I think this needs to be unified and simplified. Any proposals?

**Comment by robbr48** [comment]
OMTLMSimulator API supports specifying both logging interval and number of log samples. Default is to use 1000 log samples. If a non-zero logging interval is specified, it overrides the log samples setting.

Is it possible to use add an oms2_setLoggingSamples() as well, and then use the same function for TLM and FMI composite models?

**Comment by lochel** [comment]
Yes, we can do that. I want to have as much of the API in common for both TLM and FMI as possible. You can add this to the API and implement the TLM part, I will then do the FMI implementation.
