### ISSUE TITLE
Lua function for specifcying OMTLMSimulator log level

### ISSUE THREAD

**Issue by robbr48** [OpenModelica/OMSimulator#233]
**Is your feature request related to a problem? Please describe.**
User is not able to control log levels. Currently only fatal errors are printed.

**Describe the solution you'd like**
Add a setTLMLoggingLevel() function, which calls the omtlm_setLogLevel() function in OMTLMSimulator API.

**Describe alternatives you've considered**
It could be possible to use the logging level specified for OMSimulator.

**Additional context**
Logging levels available in OMTLMSimulator:
0 = Logging Disabled
1 = Fatal
2 = Fatal & Warning
3 = Fatal, Warning & Info
4 = Fatal, Warning, Info & Debug

**Comment by lochel** [comment]
Why not using the same log level for OMSimulator and OMTLMSimulator?

**Comment by lochel** [comment]
We could merge the log levels and use the same API for both, FMI and TLM:
0 = Logging Disabled
1 = Errors only
2 = Errors & Warnings
3 = Errors , Warnings & Info
4 = Errors, Warnings, Info & Debug
5 = Errors, Warnings, Info, Debug & Trace

**Comment by robbr48** [comment]
Yes, in the long run this would be best. It is a little complicated however, since TLM setting is applied separately for each model. Technically you can have two TLM models with different logging settings. I will implement a separate function for TLM now, since it is urgently needed by a user. Then we can think this over and change it later.

**Comment by lochel** [comment]
I think it would be good to have the log level also inside the models for the OMSimulator.
