### ISSUE TITLE
setTolerance() inside TLMCompositeModel.cpp

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#240]
@robbr48 Is line 380  correct?

https://github.com/OpenModelica/OMSimulator/blob/42998bbd54d2c9bf0e98a8070b555abd7074b12d/src/OMSimulatorLib/TLMCompositeModel.cpp#L371-L387

It doesn't seem to do anything useful. And the argument `tolerance` of the method isn't used at all.

**Comment by robbr48** [comment]
@lochel That is wrong. It should of course be pModel->setTolerance(tolerance). I will fix it.

**Comment by lochel** [comment]
I am not sure if this is a good idea. This would override the individual tolerances specified for the FMI composite models, right? I think each sub-model should just use its own tolerance, which is actually the current behaviour. So just removing line 380 is probably the best idea.

**Comment by robbr48** [comment]
That's true, we should use the existing one in pModel. 

Is the intention to add a setTolerance() function to the API? Right now it seems like all tolerances are hard-coded to 1e-4.

**Comment by lochel** [comment]
Yes, we need that API.

**Comment by robbr48** [comment]
@lochel I believe we can close this now. That particular line no longer exists.
