### ISSUE TITLE
setStopTime affecting stability

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#246]
The simulation stability of a TLM composite model depends on the specified stop time in oms2_setStopTime("Demonstrator_FineGrained_fg", XXXX).  A stop time of 1300s makes the model run into stability problems prior to 1s of execution; however, a stop time of 10s renders a fully stable simulation

**Comment by robha67** [comment]
Preliminary testing shows that the simulation remains stable for the large simulation stop time on a different and more powerful computer. Issue related to memory allocation? If so, a warning in the cmd or TLMlog file is necessary

**Comment by lochel** [comment]
As far as I know, the TLM simulator uses the number of intervals to calculate step sizes. That might affect the stability when changing the stop time.

**Comment by robbr48** [comment]
@lochel That is only for logging, which does not affect the actual simulation. The communication intervals are fixed and depend only on the TLM parameters. My guess is that this is related to memory or disk usage.

**Comment by lochel** [comment]
@robbr48 Why does the stopTime affect memory or disk usage?
