### ISSUE TITLE
error while loading shared libraries: libomtlmsimulator.so

### ISSUE THREAD

**Issue by RiteshIAR** [OpenModelica/OMSimulator#249]
I am trying to run OpenModelica generated FMU on a Embedian SBC-SMART-BEE single board computer. Processor is TI Sitara AM3354 running arago yocto linux OS.
While executing the OMSimulator-Linux-ARM executable downloaded from https://test.openmodelica.org/hudson/job/OMSimulator-Linux-ARM/ I got following error:
root@smarct335x:~/testModel# ./OMSimulator
./OMSimulator: error while loading shared libraries: libomtlmsimulator.so: cannot open shared object file: No such file or directory. 
Please suggest how to solve this error and also suggest correct method to use OMSimulator-Linux-ARM executable with FMU.

**Comment by sjoelund** [comment]
As a workaround, OMSimulator now builds without TLM. You can get it from your link above, or a copy from https://dev.openmodelica.org/~marsj/OMSimulator/OMSimulator.v0.1.0-486-g2d80b48-linux.arm-notlm (in case Hudson breaks again).
