### ISSUE TITLE
Simulation configuration information log

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#253]
For traceability and to know what was actually simulated, a configuration log file should be generated (or info included in the standard log file). If separate log file, the file name may be the same as the result file but with e.g. "_config.log". This should include all available info on which FMUs were included in the simulation, solver settings, etc. Extract as much info as possible from modelDescription.xml for each FMU regardning e.g.:
* FMU name
* FMU generation date/time
* Generation tool
* Internal solver and tolerance (or solver and tolerence defined using setTolerance, if any).

In addition, OMSimulator level info should be included, e.g.:
* Master algorithm
* Communication step size(s)
* Central tolerance setting?
* Flags and other relevant settings affecting the simulation

Should work for single FMI composite models and for the case of connecting several FMI composite models using TLM.

**Comment by lochel** [comment]
This is certainly a good issue. Since we are now supporting SSP and using vendor specific annotations for all settings not supported by SSP itself, all these information are basically available from the ssd file. Is that sufficient?

**Comment by lochel** [comment]
I'll close this because the ssp file is basically the configuration log.
