### ISSUE TITLE
Empty pdf files from oms2_exportDependencyGraphs

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#254]
oms2_exportDependencyGraphs generates dot files with content but corresponding pdf files are blank:

oms2_initialize("AVSDemo")
oms2_exportDependencyGraphs("AVSDemo", "AVSDemo_initialUnknowns.dot", "AVSDemo_outputs.dot")
os.execute("gvpr -c \"N[$.degree==0]{delete(root, $)}\" AVSDemo_initialUnknowns.dot | dot -Tpdf -o AVSDemo_initialUnknowns.pdf")
os.execute("gvpr -c \"N[$.degree==0]{delete(root, $)}\" AVSDemo_outputs.dot | dot -Tpdf -o AVSDemo_outputs.pdf")

Prior to oms2_initialize I use exportCompositeStructure which works fine:
oms2_exportCompositeStructure("AVSDemo","AVSDemo.dot") -- generate composite model structure graph
os.execute("dot -Gsplines=none AVSDemo.dot | neato -n -Gsplines=ortho -Tpdf -oAVSDemo.pdf")

**Comment by lochel** [comment]
I cannot reproduce the issue. I tested it with `Demonstrator_20180620/AVSDemo_combi_20180620.lua`.

**Comment by meek1** [comment]
This can be closed.
