### ISSUE TITLE
oms2_setLoggingInterval/oms2_setFlags not working

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#255]
@lochel, in latest build the simulation get stuck without warning/error when using oms2_setLoggingInterval. After the simulation is stuck, the result file is corrupt and cannot be opened. I've tried different combinations of oms2_setFlags (+/-fetchAllVars) at different locations.

Please see complete test case in OpenCPS repo: T6.3\Demonstrator_20180620\AVSDemo_combi_20180620.lua (toggle commenting on lines 176, 190, and 192).

**Comment by lochel** [comment]
I think there is problem with the engine model as well. The simulation works fine for me when using the following:

```Lua
print("*** initialization ***")
oms2_initialize("AVSDemo")
oms2_setLoggingInterval("AVSDemo", 0.5)
oms2_setFlags("AVSDemo.eCS_Generic_Export", "+fetchAllVars")
oms2_setFlags("AVSDemo.engine", "+fetchAllVars")

print("*** simulatation -> 1e-4 ***")
oms2_setCommunicationInterval("AVSDemo", 1e-5)
oms2_stepUntil("AVSDemo", 1e-4)

print("*** simulatation -> 1e-1 ***")
oms2_setCommunicationInterval("AVSDemo", 1e-4)
oms2_stepUntil("AVSDemo", 1e-1)

print("*** simulatation -> stopTime ***")
oms2_setCommunicationInterval("AVSDemo", 1e-3)
oms2_simulate("AVSDemo")
```

It works also without `oms2_setLoggingInterval`.

**Comment by meek1** [comment]
Which stopTime to you use? Try the example in 6.3\Demonstrator_20180620\AVSDemo_combi_20180620.lua

Using this example, the simulation is stuck at file size 4841KB if I use setLoggingInterval (even with +fetchAllVars also for the engine model).

If not using setLoggingInterval, the simulation runs. However, the result file still cannot be opened(!).

**Comment by meek1** [comment]
Tried again with today's build. Now when using setLoggingInterval the result file size is actually increasing slowly from 4841KB, so it seems like it's simulating. However, the result file cannot be opened (using Dymola).

Now with today's build, if not using setLoggingInterval, the simulation runs and the result file can be opened.

**Comment by meek1** [comment]
@lochel, seems now like the result files (.mat) cannot be opened during simulation, only after?

**Comment by lochel** [comment]
I noticed the same behaviour, but I don't know why. It should actually be possible to read it at all time.

**Comment by meek1** [comment]
* During simulation: Cannot open result file
* After manually aborting a normal (working) simulation (Crtl+C -> Y in prompt): Result file OK
* After manually aborting a simulation with error messages (Crtl+C -> Y in prompt): Cannot open result file

**Comment by meek1** [comment]
Regarding setLoggingInterval and setFlags: Results are a bit confusing, see figures. oms2_setLoggingInterval("AVS_test_case", 1) used for all cases except the red marked.

![warning_mess](https://user-images.githubusercontent.com/31110788/41874445-3c88579a-78c8-11e8-91b3-b462bd0e16fa.png)
![warning_mess2](https://user-images.githubusercontent.com/31110788/41874446-3ca28214-78c8-11e8-93e2-3fc6d21c72d4.png)

**Comment by lochel** [comment]
I tested this again using the reimplemented version of OMSimulator. Everything works now smoothly. The only thing which is not yet available is an option to disable `--fetchAllVars` again.

However, for test purpose I’ve implemented that option, and apparently it makes the simulation extremely slow and also the simulation results are slightly different. It might be a good idea to use a later version of Dymola to generate the FMUs.
