### ISSUE TITLE
OMSimulator process on Mac not finishing

### ISSUE THREAD

**Issue by fran-jo** [OpenModelica/OMSimulator#262]
### Description

The process, when executing in Mac (OS 10.13.5), does not finish. The simulation works fine but the process stands by

### Steps to reproduce the behavior
$ ../install/mac/bin/OMSimulator oms2_multidomaingrid_cs.lua 
#### some log messages
info:    New temp directory: "/Users/fran_jo/Desktop/OMSimulator/OMSimulator/testkth/workingTemp"
info:    Result file: new_multidomain_cs.mat (bufferSize=1)
info:    Simulation finished.

#### OMSimulator does not terminate. Ctrl+C doesn't kill the process neither

- Version: [OMSimulator v2.0.0-dev-497-g76904d9-mac]
- OS: [Mac OSX OS 10.13.5 High Sierra]

**Comment by lochel** [comment]
Can you provide us the lua script ` oms2_multidomaingrid_cs.lua` and the FMUs?

**Comment by fran-jo** [comment]
Here they go! (Hope it works)
[luaScript&FMUs.zip](https://github.com/OpenModelica/OMSimulator/files/2190096/luaScript.FMUs.zip)

**Comment by lochel** [comment]
The entire oms2 implementation has now been replaced. Please open a new issue if the issue still exists for you.

**Comment by meek1** [comment]
@lochel related to #538?
