### ISSUE TITLE
AircraftVehicleDemonstrator.log takes up 55GB

### ISSUE THREAD

**Issue by sjoelund** [OpenModelica/OMSimulator#266]
### Description

Running the testsuite on Hudson using MSVC64 makes AircraftVehicleDemonstrator produce a log-file large enough to consume all disk space.

### Steps to reproduce the behavior

Run a pull request...

### Expected behavior

It needs to be possible to limit the size of log-files.

**Comment by adeas31** [comment]
I think there are couple of API just recently added by @lochel to handle such cases.

**Comment by lochel** [comment]
see #227

**Comment by lochel** [comment]
This was a bug in the logging module. The log files shouldn't grow that much anymore.
