### ISSUE TITLE
Add TLM support in the GUI

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OMSimulator#296]
**Is your feature request related to a problem? Please describe.**
TLM composite model support is missing in the GUI.

**Describe the solution you'd like**
- [x] Implement the TLM composite modeling in the GUI.

**Comment by meek1** [comment]
When I add a FMI composite model A to a TLM model, is A referenced or copied into the TLM model? How is the workflow for editing A (e.g. adding or replacing an individual FMU in A) after it is added to the TLM model?

**Comment by adeas31** [comment]
It is copied. I remember we talked about referencing as well but right now there is not support for referencing.

**Comment by adeas31** [comment]
TLM support is available in the GUI.
