### ISSUE TITLE
Make connection creation easy

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OMSimulator#297]
**Is your feature request related to a problem? Please describe.**
Creating a connection from a FMU with several inputs or outputs is a mess.

**Describe the solution you'd like**
- [x] Implement a dialog which lists all the FMUs with inputs and outputs and allows user an easy way to make connections.

**Comment by meek1** [comment]
Does this feature cover both FMI composite modeling as well as connections in top level TLM composite models?
