### ISSUE TITLE
TLM implementation for oms2::Scope::exists

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#305]
### Description

1) It seems that the TLM composite model doesn't check if a cref is unique. So it might be possible to have both an external model and a fmi composite model with the same name.

2) And then also the implement of the TLM case for `oms2::Scope::exists` is missing, which basically requires just the same auxiliary functions than (1).

**Comment by lochel** [comment]
@robbr48 Is there still something missing or can we close this one?

**Comment by robbr48** [comment]
@lochel I think we can close it. I don't think anything is missing.
