### ISSUE TITLE
SSD export for TLM models

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OMSimulator#312]
**Is your feature request related to a problem? Please describe.**
The SSD export for TLM composite models is not implemented yet.

**Describe the solution you'd like**
Use the same structure that is used for FMI composite models.

**Comment by robbr48** [comment]
@adeas31 This issue is outdated and can be closed, since we have the new implementation in oms3.

**Comment by adeas31** [comment]
I agree.
