### ISSUE TITLE
Update the results during simulation

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OMSimulator#346]
**Is your feature request related to a problem? Please describe.**
For longer simulations the user has to manually load the result file several times to see the updated results. The GUI should automatically update based on some time interval.

**Describe the solution you'd like**
Show the result file variables as soon as they are available then GUI should check if results files are updated e.g. every second or every 5 seconds, then plot new results data.

**Comment by meek1** [comment]
Same functionality for FMI composite models and top level result files would be great.

**Comment by adeas31** [comment]
The result file is invalid during the simulation. I tried to access it after `oms3_initialize` since the I can see that at least the file is created on the disk after the call but unfortunately I can't read it since its corrupt. I even tried to read it after `oms3_simulate_asynchronous` but its still invalid. It becomes valid after some time in the simulation but its not clear to me when.

**Comment by lochel** [comment]
Is it connected to the internal buffering of the result file?

**Comment by adeas31** [comment]
I think there is always buffering on Windows. But you can forcefully flush the file after writing the header information i.e., the output signals.

**Comment by lochel** [comment]
I added flushing the buffer for the csv result files. However, it haven't tested the changes using OMEdit yet.

**Comment by adeas31** [comment]
AFAIR this is not implemented in OMEdit yet.

**Comment by lochel** [comment]
This is addressed by the new simulation server. The next step will be to provide live results while simulating.

**Comment by lochel** [comment]
Still work in progress: The simulation results are received in OMEdit, but not automatically updated.

**Comment by lochel** [comment]
I believe this issue is addressed by OpenModelica/OpenModelica#7477, which unfortunately is stale due to limited resources. However, since OMSimulator already supports this functionality, I will close this issue. If there’s anything missing in OMSimulator, please feel free to reopen it or open a new issue.
