### ISSUE TITLE
Results filtrering in GUI

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#347]
Results filtrering and downsampling corresponding to functionality in lua API for FMI + TLM composite models should be available in the GUI.

**Comment by lochel** [comment]
#505 adds support for `oms3_setLoggingInterval`, `oms3_addSignalsToResults`, and `oms3_removeSignalsFromResults`.

**Comment by adeas31** [comment]
Now you can set the logging interval via GUI but I am not sure how to handle the signals filters. In my opinion we should have just on API `oms3_setSignalsFilter` considering everything is always part of the result and then one can filter using the regex.

What we have now is that everything is stored in the result file and then user can call `oms3_removeSignalsFromResults("model", ".*")` to remove all signals and then later on use `oms3_addSignalsToResults("model", regex)` to add the signals required. This is very inconvenient.

**Comment by lochel** [comment]
I agree. I will add such a function: `oms3_setSignalFiler(model, regex)`

**Comment by adeas31** [comment]
It is possible to filter results from the GUI now.
