### ISSUE TITLE
Correct/improve FMU-ME functionality

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#371]
Currently, it seems like the selected communication interval affects internal communication inside a FMU-ME cluster. The communication interval should only affect communication between clusters (or separate FMU-CS).

Improved functionality needed for the OpenCPS joint energy demonstrator. Test case will be uploaded to repo ASAP, but probably this can be investigated and improved by using simpler examples?

**Comment by lochel** [comment]
The step sizes of WC systems and SC systems shouldn't interfere each other any longer. @meek1 can you please confirm if it works now as expected?
