### ISSUE TITLE
Initialization using oms2_setTLMInitialValues

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#375]
### Description
The function oms2_setTLMInitialValues has effect on setting effort variable for hydraulic TLM connections even though there is a small discrepancy between the specified initial value and the second sample of the simulated output. 
@The effect on initial flow value is however most unclear. The function has very little effect on the second sample of the simulated data (sign or value change) and the presented value is far from the specified. However, a very poorly selected intial value affects the simulation stability, see the appended figues 
[InitializationTests_HydraulicConnection.docx](https://github.com/OpenModelica/OMSimulator/files/2413957/InitializationTests_HydraulicConnection.docx)

**Comment by lochel** [comment]
I think we can have a meeting anytime soon to discuss the initialization if necessary. However, we shouldn't worry about oms2 and focus on oms3 instead.

**Comment by lochel** [comment]
This is already fixed long ago.
