### ISSUE TITLE
Logging of simulation time

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#389]
The ability to append the execution time, as function of the simulation time, to the top level result file via a  flag (possibly in oms2_simulate or oms2_setTLMLoggingLevel?).

**Comment by lochel** [comment]
@robha67 Fmi composite models do now always contain a variable `wallTime`. We will probably use a flag for this in the new oms3 implementation.

@robbr48 Do we want to have something similar for TLM models?

**Comment by robha67** [comment]
If it is available for all FMI models in a TLM model then is it not indirectly available for the top level TLM model and no additional TLM implementation would be needed?

**Comment by robbr48** [comment]
TLM log files are handled separately, so I guess we should add it also for the top-level TLM monitor.

**Comment by robbr48** [comment]
@lochel This can now be closed I think.
