### ISSUE TITLE
Mix of 64 and 32bit FMUs

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#399]
Support composite models consisting of both 32 and 64bit FMU's

**Comment by lochel** [comment]
I guess we could achieve this using TLM connections.

**Comment by robha67** [comment]
Does this mean we could mix 32 and 64bit?

**Comment by robbr48** [comment]
It should work, but I have not tried it. We need to compile a 32-bit version of FMIWrapper, so it does not work with the current version of OMSimulator.

**Comment by robha67** [comment]
To further complicate things. There needs to be a way to differentiate between the 32bit and 64 bit wrappers then correct? If we want to mix 32 and 64bit fmus that is.

**Comment by robbr48** [comment]
Yes, but they will be implemented as external models and can then have different start scripts.

**Comment by robha67** [comment]
Ok, so OMSimulator would read the model description, se that it is a 32bit FMU, and use a 32bit FMIWrapper?

**Comment by robbr48** [comment]
No, you will need to manually choose the start script that starts the 32-bit version of FMIWrapper. OMSimulator will not load the FMU at all, it will all be handled by the FMIWrapper executable. The 64-bit FMUs can still be loaded by OMSimulator though.

**Comment by robha67** [comment]
Oh, ok. Doing this automatically could however be quite a nice feature. Would not checking the modeldescription be an option?

**Comment by meek1** [comment]
@robbr48, can you compile a 32-bit version of FMIWrapper and test provide a simple composite model example with a mix of 64- and 32-bit FMUs?

**Comment by lochel** [comment]
@robbr48, did you have time to look into it?

**Comment by robha67** [comment]
Me and Robert are going to try to integratorn 32bit FMU into the Saab demonstrator tomorrow.

**Comment by meek1** [comment]
@robha67 Is this working now and can be closed?
