### ISSUE TITLE
Discrete connections

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#415]
Connections between discrete signals are currently not supported, but highly requested.

**Comment by meek1** [comment]
@lochel, @robbr48, this is needed for both native FMI and delayed (TLM) connections. An FMU can have real, boolean, and integer in/outputs, so OMSimulator have to support it. Accoring to the FMI standard, also string in/output is allowed, but I'm not sure how we can handle that. Prioritize boolean and integer.

**Comment by meek1** [comment]
OK, but OMSimulator should not force model developers to use real only, an FMU can have booleans and integers on the interface. If conversion internally in OMSimulator is necessary, this should not require any user input. Simple examples for both native FMI and TLM are available in the OpenCPS repo: arcsim_FMI.lua and arcsim_FMI_TLM.lua found under T2.2.

**Comment by lochel** [comment]
This has low priority according to the discussion from today's meeting.

**Comment by lochel** [comment]
I implemented now everything for WC/SC systems. @robbr48, what is the status of the TLM systems?

**Comment by robbr48** [comment]
This is low priority for me at the moment, since I have too much else to do. It would require quite extensive additions to the TLMSimulator code, since all message types, data containers and interpolation functions are hard-coded for certain interface types.
