### ISSUE TITLE
Missing dll's

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#451]
I get the following error when I try to run OMSimulator.exe (v2.0.0-dev-556-ge8a2eda-mingw)

Missing libwinpthread-1.dll
Missing libgcc_s_seh-1.dll

**Comment by lochel** [comment]
Those dll's are part of OMDev (tools/msys/mingw64/bin).

**Comment by meek1** [comment]
I cannot use OMSimulator-GCC because "libwinpthread-1.dll" is missing. Works with OMSimulator-MSVC.

**Comment by lochel** [comment]
This is addressed in #452.

**Comment by adrpo** [comment]
@lochel: more or less, I removed the dependecies from the TLM lib but there are still some dependencies that I don't know where they come from, I guess form some 3rdParty libraries. Anyhow, I fixed the Hudson job so add the needed dlls in the zip file.

**Comment by lochel** [comment]
Thanks, @adrpo.
@robha67, can you please check if the zip package works now as expected?

**Comment by robha67** [comment]
I tried the new package and it seems to work, thank you!
