### ISSUE TITLE
tool support for adding connectors and connections to a system

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#477]
For FMUs with many inputs and outputs it is very tedious, and error prone, to manually add all the connector that are needed. Once a submodel (FMU) is added to a system, double clicking the FMU the inputs are listed (why not also the outputs?). A second column  where the user can create connector, with the same name, for I/Os via a check box, would be very beneficial. At the same time, the corresponding connection could be created
@adeas31

**Comment by adeas31** [comment]
I don't know if I understand this fully but for sure the outputs of the FMU are also listed. Do you have a use case where I can debug that?

**Comment by robha67** [comment]
Its not a bug but a feature request. If I have understood the oms3 API correctly, you need to connect the FMU I/Os to a system connectors if you want to pass/recieve data to/from another system. Currently, if you double click the submodel(FMU) a dialog box appears which displays the FMU inputs. Alot of work would be saved if connectors and the corresponding connections could be generated without having to manually add every single connector and connection.

**Comment by adeas31** [comment]
This should be kept open.

**Comment by lochel** [comment]
@adeas31 It is "only" about GUI support, right? Do you need any additional functionality from OMSimulator to implement it?

**Comment by adeas31** [comment]
I don't think so. It is purely GUI thing.
