### ISSUE TITLE
Load OMSimulator Model

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#495]
I am currently working on converting the Saab demonstrator to oms3 and I am at the point where I have defined all system connectors and the corresponding connections to the FMUs. When I load this model in OMEdit, the connectors or the connections do not appear. They should be visible correct?
The SSP and Lua files are in the repository at OpenCPS_trunk\WP6_Industrial Demonstrators\T6.3 Aircraft vehicle systems demonstrator\Demonstrator_FITS_FS\TLM_oms3

**Comment by adeas31** [comment]
I can't load the ssp file with latest OMEdit version. The ssd contains a connection,
```<ssd:Connection startElement="Meas_PACK_TEMP_V_POS_OPEN" startConnector="" endElement="ECS_SW" endConnector="Meas_PACK_TEMP_V_POS_OPEN" />```

which should be,

```<ssd:Connection startElement="" startConnector="Meas_PACK_TEMP_V_POS_OPEN" endElement="ECS_SW" endConnector="Meas_PACK_TEMP_V_POS_OPEN" />```

This issue is already fixed last week. Use the latest version to export and import.

**Comment by lochel** [comment]
@robha67 Can we close this one? Or do you still have problems with the latest version?
