### ISSUE TITLE
SSP export/import of parameter values

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#499]
SSP export/import of parameter values

**Comment by adeas31** [comment]
Should we also include `inputs`?

**Comment by meek1** [comment]
This is already implemented right?

**Comment by lochel** [comment]
It should be kept open.

**Comment by meek1** [comment]
What is this issue about? SSP import/export is available and working, right?

**Comment by adeas31** [comment]
Yes but it doesn't include parameters.

**Comment by meek1** [comment]
OK, should be in scope to fully implement SSP v1.0

**Comment by lochel** [comment]
We are lacking resources to fully implement SSP v1.0 right now. However, this is high on the todo list.

**Comment by lochel** [comment]
I've now removed the `stale` label. As far as I can tell, all related issues are actually solved. I just want to make sure with @arun3688 and @adeas31 before closing this issue finally.

**Comment by arun3688** [comment]
@lochel  The functionality is fully available
