### ISSUE TITLE
setLoggingInterval duplicated data points

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#509]
setLogginInterval seem to store duplicated data points, see plot. Proposal: store only one data point for each time.

![image](https://user-images.githubusercontent.com/31110788/48676327-84616600-eb65-11e8-8d84-c0571d44fd5a.png)

**Comment by meek1** [comment]
![image](https://user-images.githubusercontent.com/31110788/48676566-c17b2780-eb68-11e8-8b22-84b86d5ed543.png)

**Comment by lochel** [comment]
Okay, I will change it to only store the first data point.

**Comment by lochel** [comment]
Please test if the new builds work as expected.

**Comment by meek1** [comment]
Almost works. Duplicated points removed but first data point (t=0) missing.

![image](https://user-images.githubusercontent.com/31110788/48692110-2bc9b180-ebd5-11e8-805b-e2f7fdec35f1.png)

**Comment by lochel** [comment]
New build are available.
