### ISSUE TITLE
Cannot open result file during simulation

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#511]
Need to check results during simulation, but result files cannot be opened during simulation. Works when simulation is finished. I use bufferzise 100 and can see that the size of the result file grows stepwise. This is simulation with native FMI only.

oms3_setStartTime("S", 0.0)
oms3_setStopTime("S", 10)
oms3_setFixedStepSize("S.SS_A", 1e-3)
oms3_setResultFile("S", "S.mat", 100)
oms3_setLoggingInterval("S", 0.01)

**Comment by lochel** [comment]
It works for me (tested on Linux).

**Comment by meek1** [comment]
Please test on Windows.

**Comment by lochel** [comment]
I have also problems to open (and even write?) result files on Windows. I need to investigate the issues a bit more.

**Comment by lochel** [comment]
Now it's working for me on Windows and Linux.
