### ISSUE TITLE
Model in wrong model state?

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#512]
What does this mean? Probably I need to do oms3_instantiate prior to setReal?

Sun Nov 18 21:14:38 2018 | error:   [setBoolean] Model "S" is in wrong model state
Sun Nov 18 21:14:38 2018 | error:   [setReal] Model "S" is in wrong model state

**Comment by lochel** [comment]
Yes, right now the model has to be instantiated in order to get/set values.
