### ISSUE TITLE
hierarchical buses

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#517]
Hierarchical buses would be very beneficial for large composite models. The system in the appended example is very hard to overview as a result of the many TLMbuses. However, the red boxes indicates a natural grouping of hierarchical buses grouping physical quantities for each interfacing system.

![example_buses](https://user-images.githubusercontent.com/38733290/48783856-af70c480-ece1-11e8-8e30-331a57896c9c.png)

**Comment by lochel** [comment]
@robbr48 Is that something we can or want to support? 😃

**Comment by meek1** [comment]
Current status is that hierarchical buses can be implemented is but not prioritized now.
