### ISSUE TITLE
oms3_instantiate()?

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#529]
Seems like an FMU can fail to instantiate due to for example bad start values, but start values for inputs cannot be changed/set prior to oms3_instantiate()?

I thought no "calculations" were performed in the FMU until oms3_initialize(), but it seems like things happen inside the FMU already at oms3_instantiate()?

In oms2, the same FMU initializes iff oms2_setReal() is done prior to initialization.

![image](https://user-images.githubusercontent.com/31110788/49333468-a2948080-f5bf-11e8-8b53-7551f66503ad.png)

**Comment by lochel** [comment]
@meek1 Can you please provide an example that can be used to investigate the differences between oms2 and oms3?

**Comment by lochel** [comment]
I am still not sure why oms2 and oms3 should behave differently. However, I fixed a problem with the initialization of FMU generated by OpenModelica which make them fail before start values could be specified. I consider this has been fixed. Please reopen it and provide more information if there is still some problem with your models.

**Comment by meek1** [comment]
@lochel Sorry for my slow response! The issue was discovered due to a Dymola bug (reported and will be corrected). Dymola FMU-CS with Dassl doesn't preserve input start values set prior to FMU generation. Looks good in modelDescription.xml but is probably 0 in the actual FMU.

See attached simple test model div.mo (y = 1/u). If input u happens to have start value 0, then oms3_instantiate() fails. Thus it should be possible to set this start value prior to instantiation. Try attached FMUs; div_Cvode.fmu works as expected but div_Dassl.fmu has probably 0 as start value.

[div.zip](https://github.com/OpenModelica/OMSimulator/files/2752423/div.zip)

**Comment by lochel** [comment]
Thanks for the example. Now, I could actually reproduce the problem. I will push a fix so that the following script works.

```Lua
oms3_newModel("test")
oms3_addSystem("test.root", oms_system_wc)

-- instantiate FMUs
oms3_addSubModel("test.root.div", "div_Dassl.fmu")

oms3_setReal("test.root.div.u", 1.0)

print("instantiate");
oms3_instantiate("test")
print(".. done");

oms3_initialize("test")
oms3_simulate("test")
oms3_terminate("test")
oms3_delete("test")
```

**Comment by lochel** [comment]
The example works now with the changes from #554.

**Comment by meek1** [comment]
@lochel can you document what is the effect and differences of setting start values i) prior to instantiate, ii) after instantiate but prior to initialize, iii) after initialize, iv) setting start values for the same variable both in i), ii), and iii) etc?
