### ISSUE TITLE
Question - How to install in a different folder?

### ISSUE THREAD

**Issue by mantielero** [OpenModelica/OMSimulator#537]
I am trying to put this in a flatpak. I am struggling compiling this.

It fails complaining about: FMILibrary_LIBRARY being NOT FOUND.

What I would like to do is to install everything under `/app/lib` and `/app/include`.

Regards,
José M.

**Comment by lochel** [comment]
I think I don't quite get the issue. Why doesn't it find FMIL? It is located in the submodule 3rdParty.
