### ISSUE TITLE
"Stopped working" after finished simulation

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#538]
Successful simulation ends with:

![image](https://user-images.githubusercontent.com/31110788/50047800-359fe100-00bd-11e9-8b32-307deb34faa5.png)

.mat result file opens successfulle. Using oms3 64-bit MSVC.

**Comment by meek1** [comment]
@lochel, is this problem only on Windows?

**Comment by lochel** [comment]
Yes, it seems to happen only on Windows.

**Comment by lochel** [comment]
Can you please test it again with the latest version?

**Comment by meek1** [comment]
Sorry, behavior seems to be composite model specific and maybe also a bit stochastic(?). In general, both old and new OMSimulator works as expected for: \WP6_Industrial Demonstrators\T6.3 Aircraft vehicle systems demonstrator\backToBasics_20181211\btb_reduced.lua

But both old and new OMSimulator give "Stopped working" for: \WP6_Industrial Demonstrators\T6.3 Aircraft vehicle systems demonstrator\M36_Benchmarking_native_FMI\AVSM36_64bit.lua (reduce stopTime to e.g. 0.01 when testing)

**Comment by meek1** [comment]
I'm 99% sure the AVSM36_64bit.lua worked as expected the first time I tested with the new OMSimulator, but not the second time. Tested again with removing temp folder and .log- and .mat files, to repeat the "fresh" conditions, but then fails anyway.

**Comment by lochel** [comment]
It seems to be a problem with Dymola FMUs, I tested some models with Dymola 2017 which crash in that way and then with Dymola 2019 which work just fine.

**Comment by meek1** [comment]
Same problem with Hopsan FMUs, test Modprod TLM example on Windows.

**Comment by lochel** [comment]
I close the issue, since it seems to be a problem of how the FMUs handle resources.

**Comment by meek1** [comment]
@lochel did you investigate gcc vs msvc? And lua vs python?
