### ISSUE TITLE
Multiple connections to the same "default" TLM bus

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#542]
The possibility for multiple connections to the same TLM bus (via the lua API) would simplify composite modelling significantly. For example

oms3_addTLMBus("Model.tlm.A.Delayed_1,oms_tlm_domain_output, 1, default)
oms3_addConnectorToTLMBus(..)

oms3_addTLMBus("Model.tlm.B.Delayed_1,oms_tlm_domain_output, 1, default)
oms3_addTLMBus("Model.tlm.B.Delayed_2,oms_tlm_domain_output, 1, default)
oms3_addConnectorToTLMBus(..)
oms3_addConnectorToTLMBus(..)

oms3_addTLMConnection(""Model.tlm.A.Delayed_1","Model.tlm.B.Delayed_1", ...)
oms3_addTLMConnection(""Model.tlm.A.Delayed_1","Model.tlm.B.Delayed_2", ...)

**Comment by robbr48** [comment]
It could be possible, for output signal type interfaces only. It requires a bit of coding though, since the current code assumes that each interface is connected to exactly one other interface. I will have a look at it.

**Comment by robbr48** [comment]
This should be kept open I believe.
