### ISSUE TITLE
Specification of initial values for physical connections

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#543]
Could the tlm connection intial values be specified directly in the connection statement in order to simplify specification of initial values?

For example:
oms3_addTLMConnection("A.P_1","B.P_1", Delay,Impedance, Initial Effort, Initial net flow)

where initial effort and initial net flow are optional arguments for physical connections. This would remove the need for an API command like oms3_setTLMInitialValues.

@robbr48

**Comment by robbr48** [comment]
Initial values are specified for each interface, not for each connection. It for example possible to have different initial pressure/flow on each side of a connection. Also, flow variables have opposite signs on each side, so it would be unclear for which interface in the connection it should be applied.

I believe the additional arguments could still be added to the oms3_addTLMBus function though.
