### ISSUE TITLE
Anti-aliasing filtering of FMU outputs

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#547]
@lochel, is it possible to add anti-aliasing on FMU outputs as a master feature, or does it have to be done on the modeling side prior to FMU generation?

**Comment by lochel** [comment]
I’m not quite sure. I need to do some research on this topic.

**Comment by meek1** [comment]
@lochel @robbr48 this should be open. With FMI3.0 Intermediate Variable Access (IVA) this should be a possible master functionality right? I.e. the master filters high resolution FMU output data prior to providing it to connected FMU inputs.

**Comment by robbr48** [comment]
@meek1 I agree. It should be possible, although only for FMUs that supports IVA of course.
