### ISSUE TITLE
”Continuous” output from interpolation table

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#564]
When feeding FMUs with outputs from the interpolation table component implemented in OMSimulator, it would be good to have something like output derivatives from the interpolation table.

In the interpolation table case the complete time series is available (i.e. also future values), so we should not be forced to use zero-order-hold sampling for each master step.

Good interpolation table functionality (.mat and .csv) is of high interest in Saab’s current application.

**Comment by meek1** [comment]
Escalate if possible. Functionality should be optional.

**Comment by meek1** [comment]
@lochel Any plans for this one?

**Comment by lochel** [comment]
Yes, should be one of the next fixes … How urgent is it for you?

**Comment by meek1** [comment]
Within two weeks would be good. How is the ouput derivatives and input interpolation functionality defined in the FMI-standard? Is it on individual signal level, or on FMU-level? For example, maybe you dont want all inputs to an FMU to be interpolated, but just a few. Maybe you have a mix of continuous and discrete signals in the .csv table. For example, control signals from a software FMU to a physical system FMU should normally be zoh with a specific sample time, but signals between two physical FMUs should use derivatives and interpolation.

**Comment by lochel** [comment]
The FMI standard just defines if a FMU is capable of interpolating (basically extrapolating) input signals.

We can think of defining a way to specify which signals should be extrapolated and which should be zoh. Right now, all available output derivative information will be used to extrapolate connected inputs.

**Comment by lochel** [comment]
@meek1 How should this be implemented? We could always use linear interpolation and provide the first derivative. (That would also support zoh signals.) Is that acceptable or do you need higher order derivatives?

**Comment by lochel** [comment]
This functionality is now available. Please let me know if works for you as expected.

**Comment by meek1** [comment]
@lochel could you provide some info in the documentation on what effects the derivative related flags have? According ti documentation the setInputDerivatives flag is obsolete?

Should these flags be used on FMU-level, on wc system level or something else?

**Comment by lochel** [comment]
`--setInputDerivatives` is now replaced by `--inputExtrapolation` and just kept as deprecated for now to not break older scripts. Lookup tables will always provide the actual signal value and its first derivative. Derivative information is only used to extrapolate inputs if `--inputExtrapolation=true` is used. I will add a section to the documentation for this.

**Comment by meek1** [comment]
OK, thanks. So the --inputExtrapolation flag is applicable to the model top level? Not for a specific wc system or a specific FMU?

**Comment by lochel** [comment]
The flag is global and used for the entire OMSimulator instance (all models).
