### ISSUE TITLE
Add ME/SC System support for adaptive step-size algorithm.

### ISSUE THREAD

**Issue by frape315** [OpenModelica/OMSimulator#603]
**Current issue.**
In the current implementation of the adaptive solver in SystemWC.cpp it does not work for any model with a SC system. It simply calls stepUntil on Strongly connected systems with whatever the step-size is in the current step. Should add coverage so that there is Rollback possibility on the Strongly connected systems. Currently if a rollback is attempted it will not work for Stronly connected systems.

NOTE: This implementation should work as long as no rollback is needed. Rollback support for the SystemSC models is all thats missing.

**Suggestion on implementation**
One way to solve this is to pass the FMU state vector in/out of the strongly connected systems. I suggest using sVect and fmuImportVect in exactly the same way as in the WC systems, and just passing these two vectors into the SC system with stepUntil.

Doing this implementation has the advantage of being able to reset the SystemSC inside the same rollback loop in the SystemWC. Do note that SystemSC tracks time, this probably needs to be adjusted when the FMUs are rollbacked aswell. (making a setTime method in SystemSC might be the way to solve this.)

**Comment by meek1** [comment]
@lochel @frape315 what’s the status of the variable step solver from the thesis?

**Comment by lochel** [comment]
It is already available. However, it is barely tested. It would be nice if you could provide some test cases.

Regarding #603 and #604: I will address both issue, but for now it has no priority.

_All the closed stale issues are still part of the backlog._
