### ISSUE TITLE
Change implementation of Algebraic loop solving for adaptive step-size

### ISSUE THREAD

**Issue by frape315** [OpenModelica/OMSimulator#604]
**Description.**
Currently there is a solution for algebraic loop solving for fixed step algorithms. But in the implementation of the variable step-size solver in SystemWC.cpp, it is disabled and throws an error.

**Considerations & Solutions**
There are two seperate algorithms, one that double steps, and one that single steps and allows for models which partly don't support rollbacks. 

In the adaptive solver in SystemWC.cpp there is two functions that interact with algebraic loops, updateInputs() and getInputAndOutput(). 

For the double step algorithm:
- 1 large step->getInputAndOutput() (for later error control)
- Reset FMU states
- 1 small step -> updateInputs().
-  1 small step ->getInputAndOutput(). (compare to earlier results for error control.

Single step algorithm:
- Do 1 step
- getInputAndOutput()
- error control 
- rollback if needed.
- updateInputs()

Currently updateInputs() covers algebraic loops, but if there is an algebraic loop getInputAndOutput() 
will throw an error, reasoning behind this can be seen below. 

An implementation needs to be made in getInputAndOutput() to remove the if (sortedConnections[i].size() == 1) case.

Instead just loop over both i<sortedConnections.size and j<sortedConnections[i].size(), and edit in a second index j into int output = sortedConnections[i][j].first; int input = sortedConnections[i][j].second;
 
Both algorithms work fine with this implementation. Double step algorithm simply doesn't care if the signals are in an algebraic loop or not and the single stepping algorithm only cares as long as both FMUs can get/set state, and thats already sorted inside getInputAndOutput().

**Additional Notes & Cleanup**
The reason this was implemented as it currently stands was that during implementations the functions 
- SystemWC::getOutput
- SystemWC::updateCanGetFMUs
- SystemWC::updateCantGetFMUs

were also used during different parts in the algorithms to allow for using FMUs that do not support get/set state for double stepping, and these became complicated with algebraic loops. 

### **OBS - READ THIS:**
As such these 3 functions **can be removed from SystemWC** when the team is confident we do not want to return to the old implementation. (It was realized during development that this was not an accurate implementation, even tho it should work. Since certain signals wouldn't communicate with each other in the middle small step. As such this was scrapped. And it wasn't needed for the single step algorithm.)

**Comment by meek1** [comment]
@lochel @frape315 what’s the status of the variable step solver from the thesis?
