### ISSUE TITLE
Cannot execute in path containing @

### ISSUE THREAD

**Issue by sjoelund** [OpenModelica/OMSimulator#627]
### Description

I am not sure if this is an OpenModelica or OMSimulator issue with resources.

### Steps to reproduce the behavior

* Install OMSimulator in a path containing @ (for example a btrfs subvolume).
* Run a test

```
[martin@mega tlm]$ ../../install/linux/bin/OMSimulator tlm1d.lua
assert            | debug   | Failed to open file /mnt/data/%40Mech/martin/dev/OMSimulator/testsuite/tlm/tlm1d-lua/model-0io41wrt/temp/mass/resources/tlm_massSpring_info.json for reading: No such file or directory
getBestJumpBuffer got mmc_jumper=(nil), globalJumpBuffer=(nil)
Aborted
```

**Comment by lochel** [comment]
It actually looks like an OpenModelica issue.

**Comment by lochel** [comment]
I tested it now on Windows and Linux with FMUs from Dymola and OpenModelica. OMSimulator works just fine for all the tests. It is just the OpenModelica FMUs which cannot import some of the resources if the path contains `@`. It is possible to circumvent the problem by using a different temp directory (e.g. `--tempDir=/tmp/omsimulator/`) if possible.

I’ve now opened an OpenModelica ticket for it: https://trac.openmodelica.org/OpenModelica/ticket/5379
