### ISSUE TITLE
Enable FMU specific tolerances

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#659]
Extend setTolerance() functionality to (optionally) enable FMU-specific tolerances for weakly coupled systems. This should be an option, i.e. should still be possible to set a common tolerance for all FMU-CS in a weakly coupled system.

**Comment by lochel** [comment]
### Proposal
By default, all simulation components (e.g. FMUs) inherit the tolerance from their parent system. It can be overwritten using `setTolerance`. Setting the tolerance to `0` means to again inherit it from the parent system, which is also the default behavior.
