### ISSUE TITLE
Documentation of initialization

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#663]
@lochel Please provide short documentation of how initialization and start values are handled for different cases, e.g. sc, wc, TLM.

For wc, can I expect that initial outputs from FMU A are automatically propagated as initial inputs to FMU B? Differences in start value handling with/without algebraic loops?

Do look up tables behave exactly as an FMU regarding initial value propagation?

**Comment by lochel** [comment]
> @lochel Please provide short documentation of how initialization and start values are handled for different cases, e.g. sc, wc, TLM.

I will add more information to the documentation. @robbr48 Can you add a section about TLM to the documentation?

> For wc, can I expect that initial outputs from FMU A are automatically propagated as initial inputs to FMU B? Differences in start value handling with/without algebraic loops?

Yes, and it is basically the same for WC and SC. Algebraic loops are a bit tricky, because one cannot know which signal is used to start the iteration. This will be addressed in the future.

> Do look up tables behave exactly as an FMU regarding initial value propagation?

Yes.

**Comment by meek1** [comment]
OK, thanks. We noticed that different things happen depending on where you set initial values, i.e. prior to instantiate(), after instantiate() but prior to initialize(), or after initialize(). What is the general recommendation? Always set all start values prior to instantiate()?

See attached simple test model with two low-pass filters. One start value for each filter. Only start values set prior to instantiate() gives expected behavior. Setting both start values after instantiate() but prior to initializa() gives unexpected behavior for both filters. Then moving one start value down to after initialize() "heals" the behavior of the filter with start value set prior to initialize(). 

If applicable, make this into a separate issue.

[filt.zip](https://github.com/OpenModelica/OMSimulator/files/3107548/filt.zip)

**Comment by lochel** [comment]
This sounds odd and should certainly be handled in a separate issue.

**Comment by lochel** [comment]
I added some explanations to the documentation, e.g. [here](https://openmodelica.org/doc/OMSimulator/master/html/OMSimulatorLua.html#setreal).
