### ISSUE TITLE
oms_setResultFile() to simultaneously provide both .csv and .mat

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#666]
Would be nice with an option to get both .csv and .mat files from the same simulation. Different file formats are good for different purposes, and running a simulation twice just to get both formats is not a good option for large/slow models.

For example, when post-processing simulation results in e.g. Matlab, csv-files are easy to work with (don't have to care about the special structure of the mat-files). But when plotting in e.g. Dymola or OpenModelica, mat-files are convenient.

**Comment by sjoelund** [comment]
We have for OpenModelica an API to convert from mat to csv: https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html#filtersimulationresults

**Comment by meek1** [comment]
OK, then one possible solution alternative might be to somehow reuse this conversion functionality in OMS and provide bindings to Lua and Python?

**Comment by meek1** [comment]
@lochel, any ideas on if/how this feature could be provided?

**Comment by lochel** [comment]
I think should be handled by post processing the simulation results. We have this functionality in OpenModelica and it should be pretty easy to bring it to OMSimulator once it is refactored and made independent - which it actually should be. Then we could reuse the implementation for all of our scripting integrations. @sjoelund What do you think?

**Comment by lochel** [comment]
We discussed this (already some weeks ago) in the regular OpenModelica dev meeting together with @adrpo, @sjoelund, and @adeas31. The plan is to make an independent c library that can be used for this by all OpenModelica clients. However, there isn't any timeline yet.
