### ISSUE TITLE
Sharp results on events

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#668]
**Is your feature request related to a problem? Please describe.**
Imprecise solution around events.
![Event](https://user-images.githubusercontent.com/38031952/57081914-f71a6400-6cf5-11e9-8456-61ad0a1588b5.png)
Blue: Solution computet from FMU with FMUComplianceChecker (Explicit Euler)
Green: Solution computet from Modelcia model with OMCompiler (DASSL)
Red: Solution computet from FMU with OMSimulator (Explicit Euler)

**Describe the solution you'd like**
To get a solution similar to the green (more or less correct) solution it should be enough to evaluate (and save) values right after the event iteration. So two values for the same time.

Is it a problem with real time applications and that's the reason the next computed step is saved?

**Comment by lochel** [comment]
It might be related to what I fixed in #677. Is this about CS or ME? Can you please also provide the test case?

**Comment by AnHeuermann** [comment]
I tested it again just now (with OMSimulator v2.1.0-dev-103-g9e04b31-mingw) and got the same results as previously.

MOS-Script:
```
loadString("
model simpleSampleEvent
  Real x(start=1,fixed=true);
  Real a(start=1,fixed=true);
equation
  when sample(0.5, 0.1) then
    a = pre(a)+0.1;
  end when;
  der(x)=a*x;
end simpleSampleEvent;
[simpleSampleEvent.zip](https://github.com/OpenModelica/OMSimulator/files/3173340/simpleSampleEvent.zip)


");
getErrorString();

buildModelFMU(simpleSampleEvent);
getErrorString();

system(getInstallationDirectoryPath() + "/bin/OMSimulator simpleSampleEvent.fmu --intervals=500 --resultFile=\"simpleSampleEvent_OMS_res.mat\" --suppressPath=true"); getErrorString();
```
ME FMU (for Windows): [simpleSampleEvent.zip](https://github.com/OpenModelica/OMSimulator/files/3173342/simpleSampleEvent.zip) (rename .zip to .fmu)

**Comment by lochel** [comment]
This is the result using the changes of #680:

![image](https://user-images.githubusercontent.com/8457302/57687771-581e3200-763c-11e9-9b28-cec9c653638a.png)

**Comment by AnHeuermann** [comment]
MOS-Script for a more complex example:
```
loadString("
model FMU_A
  output Real a_out(start=1,fixed=true);
equation
  when sample(0.5, 0.1) then
    a_out = pre(a_out)+0.1;
  end when;
end FMU_A;
"); getErrorString();

loadString("
model FMU_B
  input Real a_in;
  output Real a_out;
equation
  if (a_in >= 1.2) then
    a_out = a_in+1.0;
  else
    a_out = a_in;
  end if;
end FMU_B;
"); getErrorString();

loadString("
model FMU_C
  Real x(start=1,fixed=true);
  input Real a_in;
equation
  der(x)=a_in*x;
end FMU_C;
"); getErrorString();

// Build FMUs
setCommandLineOptions("--simCodeTarget=C"); getErrorString();
buildModelFMU(FMU_A, version="2.0", fmuType="me", platforms={"static"}); getErrorString();
buildModelFMU(FMU_B, version="2.0", fmuType="me", platforms={"static"}); getErrorString();
buildModelFMU(FMU_C, version="2.0", fmuType="me", platforms={"static"}); getErrorString();

// Write lua script
writeFile("CoSimEvent_cs.lua", "
oms_setCommandLineOption(\"--suppressPath=true\")
oms_setTempDirectory(\"./temp-CoSimEvent_cs/\")

oms_newModel(\"CoSimEvent\")
oms_addSystem(\"CoSimEvent.root\", oms_system_sc)
oms_addSubModel(\"CoSimEvent.root.system1\", \"FMU_A.fmu\")
oms_addSubModel(\"CoSimEvent.root.system2\", \"FMU_B.fmu\")
oms_addSubModel(\"CoSimEvent.root.system3\", \"FMU_C.fmu\")

oms_addConnection(\"CoSimEvent.root.system1.a_out\", \"CoSimEvent.root.system2.a_in\")
oms_addConnection(\"CoSimEvent.root.system2.a_out\", \"CoSimEvent.root.system3.a_in\")

oms_setResultFile(\"CoSimEvent\", \"CoSimEvent_OM_res.mat\")
oms_setStopTime(\"CoSimEvent\", 0.1)
oms_setFixedStepSize(\"CoSimEvent.root\", 1e-4)
oms_setTolerance(\"CoSimEvent.root\", 1e-6)

oms_instantiate(\"CoSimEvent\")
oms_initialize(\"CoSimEvent\")
oms_simulate(\"CoSimEvent\")

oms_terminate(\"CoSimEvent\")
oms_delete(\"CoSimEvent\")
"); getErrorString();

// Simulate with OMSimulator
system(getInstallationDirectoryPath() + "/bin/OMSimulator --ignoreInitialUnknowns=true CoSimEvent_cs.lua", "CoSimEvent_cs_systemCall.log"); getErrorString();
readFile("CoSimEvent_cs_systemCall.log");
```
Basicaly I want to connect the FMUs like fmuA->fmuB->fmuC
My results are completly wrong. Probably my lua-Script is wrong.

Expected Results:
![expectedResults](https://user-images.githubusercontent.com/38031952/57694708-b6eba780-764c-11e9-85db-c2496c834aca.png)

**Comment by lochel** [comment]
The lua script seems to be correct and I get identical results to the expected results. @AnHeuermann Can you verify it?

**Comment by AnHeuermann** [comment]
I overlooked `oms_setStopTime(\"CoSimEvent\", 0.1)` and was expecting to simulate up to 1. Yes I get also correct results.

**Comment by lochel** [comment]
The events are not "exact" because #680 isn't merged yet.

**Comment by AnHeuermann** [comment]
Tried it again with PR #680. Seem to work.
Around time=0.7 I get a small intermediate step. But that's to be expeected, since it's CoSimulation an thats the minimum step size, right?

**Comment by lochel** [comment]
> Tried it again with PR #680. Seem to work.
> Around time=0.7 I get a small intermediate step.

That's now fixed as well.
