### ISSUE TITLE
Maximum number of allowed event iterations on event.

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#669]
**Is your feature request related to a problem? Please describe.**
When creating a buggy FMU and testing it with OMSimulator I got caught in a loop for initialization at start time.
But also working FMUs could have event shattering at start time or an incredible amount of event iterations.

**Describe the solution you'd like**
A maximum number of allowed calls to `fmi2NewDiscreteStates` for one time step or a maximum number of allowed event iterations and a thrown error when reaching this limit.

**Describe alternatives you've considered**
OMSimulator already has a timeout flag. But reaching 1000 (or some other limit) of event iterations should in general be a lot faster then reaching a time limit for the whole simulation.

**Additional context**
[Buggy FMU](https://github.com/OpenModelica/OMSimulator/files/3138594/Modelica.Blocks.Examples.BusUsage.zip)  (for Windows, 64Bit, rename to .fmu)
Or create it with OMCompiler and `--simCodeTarget=omsic` for Modelica model `Modelica.Blocks.Examples.BusUsage`.

**Comment by lochel** [comment]
@AnHeuermann Is anything else requested than the flag `--maxEventIteration`? It is set to 100 by default. The counter is reset each time the event iteration converged.

**Comment by AnHeuermann** [comment]
Looks good to me! No I can test more broken FMUs ;-)
