### ISSUE TITLE
Not possible to import FMU 2.0 Co-Simulation model into OMSimulator

### ISSUE THREAD

**Issue by mememery** [OpenModelica/OMSimulator#670]
Hi all,

I am just getting started with Co-Simulation models, focusing on FMI/FMU. I want to use OMSimulator, which theoretically allows to import FMU 2.0 both for Co-Simulation and Model-Exchange.
I have exported a FMU 2.0 Co-Simulation from Matlab/Simulink (which is the only choice allowed), and tried to import it in OMSimulator. The next error appears:
The FMU version is 2.0 and FMU type is CoSimulation. Unsupported FMU type. **Only FMI 2.0 ModelExchange is supported**.

These are the specifications of both simulation tools:
Matlab R2019a (64-bit)
OpenModelica 1.13.2 (64-bit)
Specifically, my OMEdit is connected to OMSimulator v2.0.1 - mingw
And mi OS: Win 64-bit

I have tried with several models, but finally I decided to use one of the Simulink examples called power_microgrid (https://es.mathworks.com/help/physmod/sps/examples/simplified-model-of-a-small-scale-micro-grid.html). 

I have followed the steps from the Matlab help for creating a FMU: create a Simulink project for the model and then export the FMU file. I did it sucessfully.

After that, I openned OMEdit and I created a new OMSimulation model of type: Weakly coupled- Connected Co-Simulation FMUs Systems. 

Then, I selected "Import FMU" from the FMU menu and chose my power_microgrid.fmu file.

The aforementioned error appeared.

I was expecting to have a box in the editor containing my .fmu file, but this is not possible. 

![screenshot](https://user-images.githubusercontent.com/50234101/57137944-9d776f80-6db1-11e9-9469-20233f1aaaf4.PNG)

**Comment by lochel** [comment]
You are using the Modelica-based FMU import. That is completely independent from OMSimulator. Instead, you want to create an OMSimulator model. Go to the `OMSimulator` item in the menu bar and click `New OMSimulator Model`. The system type is important to select if cs or me FMUs should be imported.

After that, you can open the system in the Libraries Browser and click `OMSimulator` -> `Add SubModel` to import a FMU.

**Comment by lochel** [comment]
@adeas31 There is more documentation in the User's Guide needed for how to use OMSimulator from OMEdit.

**Comment by mememery** [comment]
Thank you very much, I could not find this information in the User's Guide but now it works.

**Comment by lochel** [comment]
We added now a chapter to the [documentation](https://openmodelica.org/doc/OMSimulator/master/html/OMEdit.html). It certainly needs to be improved, but it is at least something to start with. Thanks for your feedback.
