### ISSUE TITLE
mingw build doesn't work

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#674]
When running a simple test model I get the following error with mingw build, but works fine with msvc build:

![image](https://user-images.githubusercontent.com/31110788/57405398-a071c600-71de-11e9-91aa-6f0042469de3.png)

Using Windows 7 64-bit

**Comment by sjoelund** [comment]
Might be that MINGW uses dlclose or something and does not actually remove the dll handle? @lochel will make it give a warning instead of a crash in this case.

It could also be that an `atexit` could be used to remove the directories at the end of the process? That could remove temp-files also on an error, and maybe (but probably not) remove directories referenced by a dll.

**Comment by lochel** [comment]
@meek1 How did you generate the FMUs in this case? OM, Matlab, Dymola?

**Comment by meek1** [comment]
I think it was Dymola 2018 FD01 but 100% sure.

**Comment by lochel** [comment]
This is probably a problem with the FMUs. Could you please try to generate them with the latest Dymola version?

**Comment by lochel** [comment]
I think this can be closed. Please reopen it if there are still problems.

**Comment by lochel** [comment]
Instead of the execption, there will be now a warning like this one:
```
warning: working directory "\tmp\model-u2fprxnj\temp\B" couldn't be removed
         boost::filesystem::remove: åtkomst nekad: "\tmp\model-u2fprxnj\temp\B\binaries\win64\div.dll"
```

**Comment by meek1** [comment]
So it was not an FMU problem?

**Comment by sjoelund** [comment]
It's an FMU+MINGW problem. The file will not be deleted because the resource cannot be free'd while OMSimulator is running. So you need to remove it later.

**Comment by lochel** [comment]
@meek1 It would still be nice to know if the problem disappears using the latest Dymola version. Could you test it, or provide the Modelica model so that I can test it?

**Comment by meek1** [comment]
@lochel I think it's this one: [div.zip](https://github.com/OpenModelica/OMSimulator/files/3190393/div.zip)

**Comment by lochel** [comment]
Thanks. I tested it now (using Dymola Version 2017 FD01 and Version 2019 FD01) and it seems the issue has been fixed in the latest Dymola version.
