### ISSUE TITLE
Table component unexpected behaviors

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#675]
Observations from attached simple example [filt.zip](https://github.com/OpenModelica/OMSimulator/files/3159184/filt.zip) with a csv table A and a FMU B, with A.y connected to B.u. Plot A.y and B.u. The sample time in the csv table is 1s.

1) Communication interval = 1s and  --inputExtrapolation=false gives: B.u is delayed 1s (not expected).
2) Communication interval = 2s and  --inputExtrapolation=false gives: B.u is delayed 2s (not expected).
3) Communication interval = 2s and  --inputExtrapolation=true gives: B.u looks very strange (not expected).
4) Communication interval = 1s and  --inputExtrapolation=trie gives: B.u=A.y (expected).

**Comment by lochel** [comment]
Problem (1) is easy to fix by adding left and right limit to the sub-sampled output file.
Problem (2) and (3) are actually problems with the current table implementations.

**Comment by meek1** [comment]
OK, for case 4 (when it's working as expected) I can mention that our simulation is running twice as fast compared to case 1. When problems 2 and 3 are solved, this is a great feature!

**Comment by lochel** [comment]
I get now the following reasonable results for the different cases:

### (1) stepSize=1s, loggingInterval=1s, inputExtrapolation=false
![image](https://user-images.githubusercontent.com/8457302/57611549-6b18ff80-7573-11e9-8165-ef075484b075.png)

### (2) stepSize=2s, loggingInterval=1s, inputExtrapolation=false
![image](https://user-images.githubusercontent.com/8457302/57611656-a3b8d900-7573-11e9-9537-aab39c832806.png)

### (3) stepSize=2s, loggingInterval=1s, inputExtrapolation=true
![image](https://user-images.githubusercontent.com/8457302/57611697-b3382200-7573-11e9-8eac-cb8e11497d74.png)

### (3) stepSize=1s, loggingInterval=1s, inputExtrapolation=true
![image](https://user-images.githubusercontent.com/8457302/57611714-bdf2b700-7573-11e9-93ab-c33e83b669d7.png)

**Comment by meek1** [comment]
(1): OK
(2): B.u OK, but shouldn't A.y look as in (1)? Probably not?
(3): Not OK. This would probably make life harder for the internal solver in FMU B than in (2). It should not be a requirement that the communication step size is equal to the sample time in the csv file. It should be possible to utilize derivatives even though the communication step size is larger or lower than the sample time in the csv file.
(4): OK.

**Comment by lochel** [comment]
(2) I think the results are correct as they are. The thing is, that it is co-simulation and only the communication steps are part of the results. Whatever is calculated inside a simulation unit isn't exposed.

**Comment by meek1** [comment]
That seems fully reasonable. What about (3)?

**Comment by lochel** [comment]
Cases (2) and (3) are almost the same. In fact, they differ only in the method of input extrapolation. Therefore, `A.y` is identical in both cases. `B.u` uses linear extrapolation in (3) and is synchronised during communication steps. Due to the large step size, the extrapolation is quite off, but the results seem to be reasonable.

**Comment by meek1** [comment]
For (3) I insist that the derivative provided by the table component shall regard the communication step size. The derivative provided shall ensure that the linear extrapolation in B hits the value that will be provided by the table component at the next communication step.

**Comment by lochel** [comment]
The step size in usually unknown during communication. It will be calculated after the communication is done and before calling doStep of all slaves. Therefore, it cannot be used to calculate a reasonable output derivative. [The output derivative is only valid at a particular point in time, exactly as the output value itself.] This is especially true for adaptive step size methods. Obviously, the fixed step master could be treated as special case with a different implementation. But I’m not sure if that is a good idea or not. Therefore, I think the current behaviour is correct for an explicit master algorithm, which we are using right now. The situation could be improved by using a semi-implicit or implicit master algorithm instead. Then we could actually iterate and minimize the discrepancy at the next communication step.

**Comment by meek1** [comment]
Yes for normal FMUs, but for the csv table component we know the complete time series, also forward in time. So if information of the current step size (fixed or not) is made available to the table component, then it should be possible for the table component to provide a derivative so that the input extrapolation of the recieving FMUs hits the correct value at next communication point. Or did I miss something?

**Comment by lochel** [comment]
Yes, we know the entire time series. But we do not necessarily know the actual time step and therefore, we cannot fake the derivative to match the series in the next time step. 

However, it should be possible with implicit master algorithms which I am actually working on right now.

I think for explicit master algorithm (which we are using currently) the results are correct.

**Comment by meek1** [comment]
OK. So a "special" solution that provides the actual time step to the table component is not a good or possible idea? If not, I think this issue can be closed.

**Comment by lochel** [comment]
I discussed it today with @adeas31 to get another opinion. Sure, it would be possible to do something special for tables and fixed step master algorithms, but we do not think that it would be the best way doing it.

Instead we think implementing a semi-implicit master algorithm is a much better approach to get the results you want. It would automatically adjust the derivative based on the actual step taken if needed. It would work the same for tables and FMUs, but it would require rollback mechanism implemented in the FMUs. So there are pros and cons to consider…

I will probably have a first prototype for testing early next week.

**Comment by meek1** [comment]
OK, sounds reasonable. But for explicit master algorithms the table component will provide ”correct” derivative as long as the master step size is smaller than or equal to the sampling time in the csv-file, right? Would be good to note this in documentation of table component.

**Comment by lochel** [comment]
Yes, we should have more documentation for all of this. The derivative will always be correct for the explicit master algorithm, but it is only valid for the current point in time. Therefore, the extrapolated inputs will be probably quite off if the step size becomes to big. 

We can keep this issue open to discuss the results with the new semi-implicit master algorithm.

**Comment by meek1** [comment]
@lochel is there any option to enable/disable the storing of double data points per time step? The result csv files get twice as big. For example, in initial simulations or when you encounter stability problems, you want double data points to plot and study the exact communication between FMUs, but in other simulations you may prefer smaller file size.

**Comment by lochel** [comment]
I've now implemented the first prototype of the semi-implicit master algorithm. Since it requires input extrapolation, it can only be used for case 3 and 4. These are the results:

### (3) stepSize=2s, loggingInterval=1s, inputExtrapolation=true
using the semi-implicit master algorithm prototype
![image](https://user-images.githubusercontent.com/8457302/58552977-ff41c280-8213-11e9-8f32-e4d0a94f2c5d.png)



### (4) stepSize=1s, loggingInterval=1s, inputExtrapolation=true 
using the semi-implicit master algorithm prototype
![image](https://user-images.githubusercontent.com/8457302/58553058-2c8e7080-8214-11e9-8d7a-eb4ba576c8b5.png)

**Comment by meek1** [comment]
Conceptually, how does the semi-implicit solver work? Is it variable step, requires rollback?

**Comment by lochel** [comment]
The implicit master algorithm is analyzing the “error” in input signals after a step. If it is big, e.g. in case 3, it will rollback and adjust the derivative information to achieve a smaller error. In linear cases, this will lead to an error of 0 with one iteration.

The semi-implicit master is limited to a fixed number of iterations, instead of an advanced error control. The fixed number of iterations is one in the current prototype.

**Comment by lochel** [comment]
The new implicit master algorithm is now used by default if input extrapolation is enabled and all FMUs support rollback.
