### ISSUE TITLE
Missing .mos-files for several FMUs

### ISSUE THREAD

**Issue by bernhard-thiele** [OpenModelica/OMSimulator#691]
Previously there have been .mos-files for generating FMUs for the following models which are used by OMSysIdent examples:

- HelloWorld.mos
- HelloWorldWithInput.mos
- Lin2DimODE.mos

These .mos-files seems to be missing in the present repo. For `HelloWorld` and `HelloWorldWithInputs` the model binaries are available, but I think one should also keep the sources.

The `Lin2DimODE`-FMU is (currently) only used in the example src/OMSysIdentLib/test_Lin2DimODE_cs_Fit.cpp which has no CI test coming with it. I could create a CI example using this FMU, so that it is not overlooked in future updates and create a PR to bring the mos files back.

**Comment by lochel** [comment]
Thanks @bernhard-thiele! 👍
