### ISSUE TITLE
Supporting non-ASCII characters in paths

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#699]
### Description

There are some problems with non-ASCII characters. This is reported in [ticket:5192](https://trac.openmodelica.org/OpenModelica/ticket/5192) and solved for OMEdit, but not for OMSimulator.

**Comment by adeas31** [comment]
OMSimulator uses Boost. So we need to check how to handle this with Boost.

Other than that all the file operations should be done using the unicode version of Windows API. The OpenModelica compiler uses [omc_file](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/SimulationRuntime/c/util/omc_file.h) perhaps the same can be used by OMSimulator.
