### ISSUE TITLE
Reduce result file size

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#709]
On our test case, OMSimulator produces smaller .mat result files than the corresponding FMI composite model simulated in Dymola, which is good! Probably thanks to #509. No results filering, logging interval 1s in both cases.

However, the corresponding simulation with Modelica models in Dymola gives smaller result file size than OMSimulator. There is a Dymola option to store/not store protected variables, which can have a significant impact.

@lochel Could something similar be implemented in OMSimulator? Does OMSimulator know which variabels are proteced?

Any other ideas on features to reduce file size? (not varaible specific results filering or change of logging level)

**Comment by lochel** [comment]
No, OMSimulator doesn't know about protected variables. The tool generating the FMU can reduce the number of exported variables, which will have a direct impact on the result file size. We have plans to improve this in OpenModelica.

It depends on which variables are of interest for you. In OMSimulator, we could implement a filter based on properties like input/output/state/...
