### ISSUE TITLE
Enhanced warnings

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#713]
It would be benificial if a warning was communited in the command prompt if the simulation start time is set as smaller than the end time in a lua/python composite model description.

**Comment by lochel** [comment]
I've seen a few discussions on this topic. In general it might be intended to simulate a system backwards with startTime < stopTime. However, it might be a good idea to guard this in some way.

**Comment by robha67** [comment]
I believe a warning would be sufficient, that way it could be kept general but still inform of the possibly erronous setting
________________________________
Från: Lennart Ochel <notifications@github.com>
Skickat: den 13 januari 2020 10:50:11
Till: OpenModelica/OMSimulator <OMSimulator@noreply.github.com>
Kopia: Robert Hällqvist <robert.hallqvist@liu.se>; Author <author@noreply.github.com>
Ämne: Re: [OpenModelica/OMSimulator] Enhanced warnings (#713)


I've seen a few discussions on this topic. In general it might be intended to simulate a system backwards with startTime < stopTime. However, it might be a good idea to guard this in some way.
