### ISSUE TITLE
Simulaton progress bar

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#714]
It would be beneficial with a simulation progress bar in a log file (such as available in the TLMsimulator) in the OMSimulator. It would be even better to get this information during simulation in the command prompt. I believe that this feature was requested earlier.

**Comment by lochel** [comment]
There is a progress bar in the command prompt. It can be enabled with `--progressBar=true`.

https://openmodelica.org/doc/OMSimulator/master/html/OMSimulator.html
