### ISSUE TITLE
Monitoring and terminating simulation

### ISSUE THREAD

**Issue by meek1** [OpenModelica/OMSimulator#722]
It would be good with possibility to monitor and terminate simulation (in Python, Lua, and OMEdit):

A) Monitor selected variables, e.g. outputs or states (if not black box) of an FMU during simulation, and terminate simulation based on specific criterion.

B) Monitor and terminate based on simulation/solver progress, e.g. CPU-time, CPU-time per simulation time, solver iterations, solver step size etc.

Maybe A) and B) are already possible? If so, please point me to an example or documentation.

**Comment by lochel** [comment]
### Example of how to simulate until steady state is reached

The state `x` will eventually reach steady state (if p > 0):

```Modelica
model steady_state
  parameter Real p = 1;
  Real x(start=1.0, fixed=true);
equation
  der(x) = -p*x;
end steady_state;
```

The Lua script is going to simulate the model until the `der(x)` is smaller than `1e-5` and therewith reasonable close to steady state:

```Lua
oms_setCommandLineOption("--stripRoot=true")
oms_setTempDirectory("./temp/")
oms_newModel("model")
oms_addSystem("model.root", oms_system_sc)

-- instantiate FMUs
oms_addSubModel("model.root.steady_state", "steady_state.fmu")

-- simulation settings
oms_setResultFile("model", "results.mat")
oms_setFixedStepSize("model.root", 1e-4)

oms_instantiate("model")
oms_setReal("model.root.steady_state.p", 1.0)

oms_initialize("model")

time = 0.0
step_size = 0.1

der_x = oms_getReal("model.root.steady_state.der(x)")
error = math.abs(der_x)

while error > 1e-5
do
  oms_stepUntil("model", time+step_size)
  time = time + step_size

  der_x = oms_getReal("model.root.steady_state.der(x)")
  error = math.abs(der_x)
end

print("steady state reached at time=" .. time)

oms_terminate("model")
oms_delete("model")
```

The output shows that the simulation reaches steady state at time=11.6.
```bash
> OMSimulator steady_state.lua
info:    Set temp directory to    "/mnt/c/Users/Lennart/Repositories/steady_state"
info:    Set working directory to "/mnt/c/Users/Lennart/Repositories/steady_state"
info:    Set temp directory to    "/mnt/c/Users/Lennart/Repositories/steady_state/temp"
info:    New model "model" with corresponding temp directory "/mnt/c/Users/Lennart/Repositories/steady_state/temp/model-ioh6x6du"
info:    maximum step size for 'model.root': 0.100000
info:    Result file: results.mat (bufferSize=1)
steady state reached at time=11.6
info:    Final Statistics for 'model.root':
         NumSteps = 123 NumRhsEvals  = 130 NumLinSolvSetups = 11
         NumNonlinSolvIters = 129 NumNonlinSolvConvFails = 0 NumErrTestFails = 1
```

**Comment by meek1** [comment]
Thanks @lochel. FYI @robha67

**Comment by meek1** [comment]
Thanks @lochel! Your example is a solution to case A). Any comments on case B). How to access CPU-time, number of solver iterations, solver internal step size, etc?

**Comment by lochel** [comment]
I've no good solution to B) right now. However, it might be possible to make those attributes available by mapping it internal variables that one could access similar to model variables.
