### ISSUE TITLE
Add Parameter-Mapping support to Parameter-Bindings in SSP

### ISSUE THREAD

**Issue by arun3688** [OpenModelica/OMSimulator#735]
### Purpose
At present, We support inline Parameter binding in SSP, both at the top System Level and Component level, But without parameter mapping, This needs to be implemented, as with parameter mapping a user can set the top Level parameters to different components in the subSystem. This needs to be supported both inline and as well as through external file (.ssm)

**Comment by robha67** [comment]
Could such a mapping of parameters also be done directly to a Modelica model in OpenModelica and not only an FMU? I realize that this might be more of an OpenModelica feature but could the OMSimulator support for SSP somehow be used to establish this link?

**Comment by lochel** [comment]
This is still relevant.
