### ISSUE TITLE
Deleting a connector in a system doesn't delete its connection

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OMSimulator#748]
### Description

Deleting an element deletes the connection associated to it but deleting a connector doesn't delete the connection associated to it.

### Steps to reproduce the behavior

I have attached two cases. One is where element and its connection is deleted and we get the expected behavior and the other is where connector is deleted but its connection is left behind and the ssd becomes invalid.

[TestCases.zip](https://github.com/OpenModelica/OMSimulator/files/4751708/TestCases.zip)

### Expected behavior

The deletion of connector should also delete the connection.

### Version and OS

- Version: [`OMSimulator v2.1.0-dev-172-g8995b12-mingw`]
- OS: [Win10, 64bit]

**Comment by arun3688** [comment]
deleting the connector should also delete the startValues associated with the connector along with the connections

**Comment by lochel** [comment]
It works now 🎉
