### ISSUE TITLE
Save result file, logging and signal filter in ssp

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OMSimulator#750]
**Is your feature request related to a problem? Please describe.**
OMEdit allows setting result file name, result file buffer size, signal filters etc. via the Simulation setup dialog but these settings are not stored in the ssp so they are lost when you load the ssp next time.

**Describe the solution you'd like**
Store the values in the ssp with some vendor specific annotations.

**Comment by arun3688** [comment]
This is fixed with this commit https://github.com/OpenModelica/OMSimulator/commit/39d81c638dc0e6caf274ea63e54e9efbfd4457e9
