### ISSUE TITLE
Error running non-OM SSP from command line

### ISSUE THREAD

**Issue by markaren** [OpenModelica/OMSimulator#751]
### Description

I'm trying to load a .ssp (version 1.0) configuration using the OMSimulator command line. I have some issues. Now SSP 1.0 support is hard to come by and I'm not sure if OMSimulator suppports it? However, this SPP is valid in the two frameworks I've tested ([libcosim](https://github.com/open-simulation-platform/libcosim) and an still internal NTNU framework).

### Steps to reproduce the behavior

Run the attached SPP using OMSimulator

```
./OMSimulator.exe path/to/donfig.ssp
```

### Expected behavior

When `ssd:SystemStructureDescription name` includes the character "-" it will fail

E.g.
```
error:   [NewModel] "quarter-truck" is not a valid ident
Segmentation fault
```

Without the "-" in the name (attached file) another error appears:

```
error:   [NewSystem] internal error
```

### Version and OS

- Version:  v2.1.0-dev-172-g8995b12-win
- OS:  Win10, 64bit

[quarter-truck.zip](https://github.com/OpenModelica/OMSimulator/files/4792164/quarter-truck.zip)

**Comment by lochel** [comment]
Thanks for the feedback. Identifiers in OMSimulator are rather restricted for now and must not contain hyphens.

**Comment by markaren** [comment]
Just to add some more insight into this issue. I believe left out some important information I tried to run this as administrator in powershell as opposed to a bash shell as before. However, I still got the same error:

```
info:    Set temp directory to    "C:/Workspace"
info:    Set working directory to "C:/Workspace"
info:    New model "QuarterTruck" with corresponding temp directory "C:/Workspace\QuarterTruck-k0utd1kq"
info:    Set working directory to "C:/Workspace"
info:    Set working directory to "C:/Workspace\QuarterTruck-k0utd1kq"
error:   [NewSystem] internal error
info:    Set working directory to "C:/Workspace"
``` 

So it tries to create a folder `C:/Workspace\QuarterTruck-k0utd1kq`, but this folder is never created. I guess this is where the error lies.

**Comment by markaren** [comment]
Ok, so I tried running this using the MINGW64 version on Windows. Here it succeeds to create the `QuarterTruck-XXXX` folder, however it only contains empty dummy folders and fails with the same error as above. It then fails to delete the generated folder, but at least that tells me that it manages to create the folder and on the win64 build it probably creates it and then deletes it afterwards during cleanup.

**Comment by arun3688** [comment]
@markaren Thanks for the analysis, but the issue is not related to creating a temp folder, This issue is rather related to the ssd file. OMSimulator currently process the .ssd file  with a special openmodelica annotation tag at the top-level, and that causes the error

`error:   [NewSystem] internal error `

So I just recreated the "QuarterTruck.ssp" using OMSimulator API, similar to the ssp file provided by you, Now it is working. Please try the attached ssp file and see if it is working and also try to test the OMSimulator generated ssp in your internal framework.

[quartertruck.zip](https://github.com/OpenModelica/OMSimulator/files/4964531/quartertruck.zip)

I have also attached the "quartertruck.lua" in the above zip file which can generate the "QuarterTruck.ssp", Use this script as reference  and generate other ssp files the way you wanted.  For more info look into the documentation https://openmodelica.org/doc/OMSimulator/master/html/OMSimulatorLua.html 

You can just run , to generate the ssp file

`>>> OMSimulator quartertruck.lua `

But we need to fix OMSimulator to read ssp files generated from other tools as well, This is an ongoing work

**Comment by markaren** [comment]
Thanks!

> But we need to fix OMSimulator to read ssp files generated from other tools as well, This is an ongoing work

I assumed this was the case since I have not seen anything else stated.

Also a comment on your OM exported SSP. This SSP will not load in other tools that perform XML validation as the  XML namespaces are not bound.

**Comment by markaren** [comment]
Kinda unrelated, but when I change the export format to .csv, I get two outputs rows per time-step regardless of the `logginInterval` set. That is, it writes duplicate entries. Bug, or am I doing it worng?

**Comment by arun3688** [comment]
> Also a comment on your OM exported SSP. The SSD file will not load in other tools that perform XML validation as the XML namespaces are not bound.

I think it should work, can you try to run it with you internal framework, because annotations at the top level can be skipped by other tools i guess

**Comment by markaren** [comment]
> I think it should work, can you try to run it with you internal framework, because annotations at the top level can be skipped by other tools i guess

No, the issue isn't the annotations. It's the use of xml namespace prefixes (unsure about the correct term here). 
E.g. ssd, ssc and ssv are never defined in the document. Some XML parsers, like JAXB in Java will fail when parsing documents that do not define the namespaces used. Another tool that I know fails on the parsing because of this is FMPy.

**Comment by markaren** [comment]
> I think it should work, can you try to run it with you internal framework, because annotations at the top level can be skipped by other tools i guess

No, the issue isn't with the annotations, but the use of undeclared xml namespace prefixes (unsure about the correct lingo here).
E.g. `ssd`, `ssv` & friends are never declared in the document. Some XML parsers like JAXB for Java requires these to be declared. Another tool I know fails during parsing of such documents are FMPy and FMIGo!.

**Comment by lochel** [comment]
> No, the issue isn't with the annotations, but the use of undeclared xml namespace prefixes (unsure about the correct lingo here).
> E.g. `ssd`, `ssv` & friends are never declared in the document. Some XML parsers like JAXB for Java requires these to be declared. Other tools I know fails during parsing of such documents are FMPy and FMIGo!.

This should become a separate issue. Thanks for pointing it out though! 👍

**Comment by markaren** [comment]
> This should become a separate issue.

Indeed, see #760

**Comment by markaren** [comment]
Now that I'm able to run my SSP using OMSimulator with the help I got from @arun3688  I think we can close this issue.
What I needed to do was:

* Add top level annotation declaring the master
* Add `type="application/x-fmu-sharedlibrary"` attribute to Components
* Put resultFile annotation as the **first** annotation in the annotation list with multiple annotations for` DefaultExperiment` <-- otherwise the annotation is ignored, which I believe is a bug
