### ISSUE TITLE
SSD files generated by OMSimulator does note declare XML namespaces

### ISSUE THREAD

**Issue by markaren** [OpenModelica/OMSimulator#760]
SSD files generated by OMSimulator does not declare XML namespaces used within the document. This will make many XML parsers fail during parsing. This is naturally an issue when trying to load the SSP archive in another SSP compatible tool.

Copied this from [W3Scools](https://www.w3schools.com/xml/xml_namespaces.asp):

```
When using prefixes in XML, a namespace for the prefix must be defined.
The namespace can be defined by an xmlns attribute in the start tag of an element.
The namespace declaration has the following syntax. xmlns:prefix="URI".
...
Namespaces can also be declared in the XML root element.
```

**Comment by arun3688** [comment]
@this if fixed with https://github.com/OpenModelica/OMSimulator/commit/8ca2456766fd433fca72c3867b2f34dac4108bd5
