### ISSUE TITLE
No rule to make target following build instructions

### ISSUE THREAD

**Issue by superlou** [OpenModelica/OMSimulator#763]
### Description

"No rule to make target" when following compilation instructions.

### Steps to reproduce the behavior

1. `sudo apt-get install libxml2-dev`
2. Checkout master
3. cd to checkout
4. Run `make config-3rdParty`

```
lsimons@bestever:~/workspace/OMSimulator$ make config-3rdParty 
make: *** No rule to make target '3rdParty/FMIL/CMakeLists.txt', needed by '3rdParty/FMIL/build/linux/Makefile'.  Stop.
```

### Expected behavior

Provide configuration information.

### Screenshots

See problem description.

### Version and OS

- Version: Master 0d19b0d
- OS: Linux Mint 19.3, 64-bit

The reason I've been trying to compile from source is I get a segfault when trying to run the attached FMU ([ShipsWiringSim.fmu.zip](https://github.com/OpenModelica/OMSimulator/files/5004311/ShipsWiringSim.fmu.zip), remove the ".zip" from the filename). I have tried running by Python script, C program using libOMSimulator, and the pre-built OMSimulator binary for 64-bit linux. All methods receive a segfault. I have an older processor, an AMD Phenom II x6 which has an older instruction set, and am wondering if that is causing the segfault.

**Comment by adrpo** [comment]
Did you clone the repository using --recursive?
Do you have a 3rdParty directory?

**Comment by superlou** [comment]
@adrpo, sorry. I could've sworn I had, but I looked in the folder and there's nothing there. I did a fresh checkout with --recursive and it's building fine.

**Comment by lochel** [comment]
This happens quite often. I think we should add a check for it to `make config-3rdParty` and provide a better message than just `No rule to make target`.

**Comment by superlou** [comment]
I initially downloaded a snapshot rather the clone'd the repo, so I hadn't thought recursive repos. I agree a warning would be nice, though maybe just explicitly saying to clone recursive in the readme would be sufficient. I'm close to success, but even though I have libxml2-dev installed, `make` is failing to find the libxml headers. If I can compile successfully, I'll try to update the Linux readme instructions with what I've learned.
