### ISSUE TITLE
Did this #755 change how SSPs are imported?

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#773]
Did this PR change how SSPs are imported? 
Because I'm able to simulate my SSP using `OMSimulator-win64-v2.1.0-dev-174-gdbf5fae`, but not `OMSimulator-win64-v2.1.0-dev-176-g00f5648` and `OMSimulator-win64-v2.1.0-dev-180-ge53984d`

```
info:    Initialized thread pool for model QuarterTruck with 2 threads
error:   [setReal] Unknown signal "QuarterTruck.QuarterTruckSystem.wheel.dWheel"
error:   [instantiate] Failed to set start value for R.dWheel
error:   [initialize] Model "QuarterTruck" is in wrong model state
error:   [simulate] Model "QuarterTruck" is in wrong model state
error:   [terminate] Model "QuarterTruck" is in wrong model state
error:   [terminate] Model "QuarterTruck" is in wrong model state
./run.sh: line 2:  2020 Segmentation fault      OMSimulator -t=1000 --numProcs=2 ../QuarterTruck_10.ssp
```

_Originally posted by @markaren in https://github.com/OpenModelica/OMSimulator/pull/755#issuecomment-669920834_

**Comment by arun3688** [comment]
@the issue is related to this commit, https://github.com/OpenModelica/OMSimulator/pull/756, We need to support the older ParameterBindings as well

**Comment by markaren** [comment]
Attaching the SSP I use, as requested in the other thread

[QuarterTruck_10.zip](https://github.com/OpenModelica/OMSimulator/files/5035577/QuarterTruck_10.zip)

**Comment by arun3688** [comment]
@markaren the above parameterTagging are correct, there is problem with something else, i am debugging it

**Comment by arun3688** [comment]
@markaren  this PR should fix the above issue, the problem was with returning the variable names, when setting the startValues 
`C.mWheel => C.mWheel ` and it was returning as `mWheel` Please test it

**Comment by lochel** [comment]
Please reopen the issue if it still doesn't work for whatever reason.
