### ISSUE TITLE
Support non-real connection between CSV input and FMU

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#776]
## Description
When connecting an non-real input (boolean, integer) from a CSV to set as input to an FMU OMSimulator will issue errors and not connect the variables.

### Example Feedthrough.fmu
See e.g. the example FMU `Feedthrough` from https://github.com/modelica/fmi-cross-check/tree/master/fmus/2.0/cs/linux64/Test-FMUs/0.0.2/Feedthrough

```bash
$ OMSimulator \
    --deleteTempFiles=true \
    --stripRoot=true \
    --intervals=1500 \
    --suppressPath=true \
    --timeout=60 \
    Feedthrough.lua
```

```lua
-- Lua file for Feedthrough.fmu
oms_setTempDirectory("temp")
oms_newModel("model")
oms_addSystem("model.root", oms_system_wc)

-- instantiate FMU
oms_addSubModel("model.root.input", "Feedthrough_in.csv")
oms_addSubModel("model.root.fmu", "/Feedthrough.fmu")

-- Connect inputs to FMU
oms_addConnection("model.root.input.real_tunable_param", "model.root.fmu.real_tunable_param")
oms_addConnection("model.root.input.real_continuous_in", "model.root.fmu.real_continuous_in")
oms_addConnection("model.root.input.real_discrete_in", "model.root.fmu.real_discrete_in")
oms_addConnection("model.root.input.int_in", "model.root.fmu.int_in")
oms_addConnection("model.root.input.bool_in", "model.root.fmu.bool_in")

-- Simulation settings
oms_setResultFile("model", "Feedthrough_out.csv")
oms_setStartTime("model", 0.0)
oms_setStopTime("model", 2.0)
oms_setTolerance("model", 1e-05)

-- Instantiate, initialize and simulate
oms_instantiate("model")
oms_initialize("model")
oms_simulate("model")
oms_terminate("model")
oms_delete("model")
```

```bash
error:   [addConnection] Type mismatch in connection: input.int_in -> fmu.int_in
error:   [addConnection] Type mismatch in connection: input.bool_in -> fmu.bool_in
```

## Possible solution
If I understand it correctly all FMU inputs are always real.
So a typecast to real would be perfectly fine, as long booleans are still treated as booleans.
Using `setInteger` or `setBoolean` depending on variable type could be a solution as well.

## Alternative solutions
Inputs for FMUs can be non-real as well. Then everything should work as expected.

**Comment by AnHeuermann** [comment]
Would be nice to have for #739 .

**Comment by lochel** [comment]
We could implement an implicit type cast (for integers and booleans) in connections associated with result file signals.

**Comment by arun3688** [comment]
@AnHeuermann can you test this https://github.com/OpenModelica/OMSimulator/pull/785
