### ISSUE TITLE
Better non-linear solver for algebraic loops between components.

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#812]
**Is your feature request related to a problem? Please describe.**
Related to #808.

**Describe the solution you'd like**
Adding kinsol as alternative non-linear solver should be appropriate. It's already inside 3rdParty.

**Comment by lochel** [comment]
@AnHeuermann What is the status?

**Comment by AnHeuermann** [comment]
Kinsol was added with c8ec782983acc160271c0368afeb4b70ba861463. We need to verify and test some more, but this issue can be closed.
