### ISSUE TITLE
Generate SSM and SSV from Python/Lua Script

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#824]
This functionality may already be available but I am creating this feature request just in case

Case 1:  Functionality to generate SSV and SSM files from FMU model description files upon import in OMSimulator. For example, variables with variability="constant". The generated SSV could then serve as a template for later settings.

Case 2: Functionality to generate both the SSV and SSM files from the settings specified in scripted composite models (Python/Lua):  setReal, setInteger, etc. 

Case 3: Functionality to update the SSV generated in Case 1 by means of setReal, setInteger, etc.

Best regards
Robert Hällqvist

**Comment by lochel** [comment]
We can certainly generate a template for the ssv file based on the modelDescription files of the FMUs.

**Comment by arun3688** [comment]
@robha67 This feature is implemented now, you can test it, look into the example
https://github.com/OpenModelica/OMSimulator/blob/master/testsuite/OMSimulator/exportSSVTemplate.lua

**Comment by robha67** [comment]
Great! I will test it asap

**Comment by lochel** [comment]
@robha67 Does it work as expected or do we have to improve it somehow?

**Comment by robha67** [comment]
Sorry for the late response but I believe it works perfectly

**Comment by arun3688** [comment]
the issue is fixed
