### ISSUE TITLE
Issues with JVM based models when numProcs > 1

### ISSUE THREAD

**Issue by markaren** [OpenModelica/OMSimulator#858]
### Description

I'm using FMU-proxy (wraps any FMUs into a new client/server FMU) in order to support FMI 1.0 within OMSimulator and also in order to overcome internal issues with the FMUs such like the  `canBeInstantiatedOnlyOnce=true` capability flag. Thus, I have a number of FMUs that require the JVM.

The issue is that when loading the FMUs though OMSimulator with multiple threads, the FMUs are unable to boot or attach to the JVM. I reckon the reason is that FMI instantiate is called in separate threads? In such case, would it be possible to instantiate all FMUs in the same thread regardless of how many execution threads are used? If this is not the case then I have no idea what could cause it. The scenario runs fine in Vico and libcosim, which both calls instantiate in the same thread. 

### Steps to reproduce the behavior

Should be able to make demo SSP if required.

### Expected behavior

JVM based FMUs are able to run even when `numProcs>1`

### Version and OS

- Version: v2.1.0-dev-182-g3a70cfc-win
- OS:  Win10, 64bit

**Comment by markaren** [comment]
Found the code that I think causes this issue: https://github.com/OpenModelica/OMSimulator/blob/839c272aba25544cc4c533153a1115ccce166126/src/OMSimulatorLib/SystemWC.cpp#L157

**Comment by markaren** [comment]
Would it be possible to create a quick PR/build with the above if clause removed?

I was planning to use the test results in a Journal publication and I'm not able to build OMSimulator myself. Thanks.

**Comment by sjoelund** [comment]
Would it not make sense to either just set numProcs=1 or change the code calling the JVM to always use the same thread? Otherwise people will ask for things like "every operation except getReal should be done in parallel, because XXX crashes if getReal is called in parallel".

**Comment by lochel** [comment]
@markaren I'll create a PR later today with your changes.

**Comment by markaren** [comment]
> Would it not make sense to either just set numProcs=1 or change the code calling the JVM to always use the same thread? Otherwise people will ask for things like "every operation except getReal should be done in parallel, because XXX crashes if getReal is called in parallel".

For the properly implemented JVM FMUs at least, all other functions except for creating or attaching the JVM, which is done during `instantiate` can be called from different threads. 
Also there is hardly any performance benefits (if any at all) to perform FMI calls that are only called once in parallel. 

> I'll create a PR later today with your changes.

Awesome!

However, before such a change is actually considered to be merged, I will double check if it is possible to recover from the error during JVM creation in a parallel environment. However, as I pointed out. There is hardly any reason why e.g. instantiate should be performed in parallel.

**Comment by markaren** [comment]
In past I also had an issue with a system of three 20sim FMUs where `numProcs=3` would fail. 2 threads were ok. 
Perhaps related? We'll find out!

**Comment by lochel** [comment]
We are currently modifying the build pipeline in order to provide pre-compiled builds for pull requests.

**Comment by sjoelund** [comment]
> We are currently modifying the build pipeline in order to provide pre-compiled builds for pull requests.

Don't you already have that? https://test.openmodelica.org/jenkins/blue/organizations/jenkins/OMSimulator/detail/PR-855/7/artifacts

**Comment by lochel** [comment]
@markaren the builds for #861 are now available: https://build.openmodelica.org/omsimulator/experimental/pr-861/

**Comment by markaren** [comment]
Ok, I'm able to run the simulation regardless of the value of `numProcs` now. However, I see no performance improvements, or significant change at all vs. using `numProcs=1`. My simulation is also quite slow in general. It takes nearly two minutes to simulate 10 seconds. To compare, 2000s takes around a minute to simulate with Vico (including writing all variables to CSV).

The system has seven FMUs and 3000 variables. 

I'm simply using what I assume is default values.

`OMSimulator --numProcs=X -t=X path/to/file.spp`

and

```xml
<oms:SimulationInformation>
      <oms:FixedStepMaster description="oms-ma" stepSize="0.05" absoluteTolerance="0.05" relativeTolerance="0.05" />
</oms:SimulationInformation>
```

Am I misusing or misunderstanding something regarding OMSimulator?

**Comment by lochel** [comment]
We are very interested in identifying the bottleneck for your application and to improving OMSimulator. Thanks for your feedback.

You can try the falg `--wallTime=true` to get an idea where the simulation spends most of its time. I haven’t used the flag for quite some time though. It should export the wall time spend in each system/component of your composite model.

The alg. loop could explain the bad performance. We are currently working on providing support for kinsol for solving those loops (see #815) for cases in which the fixed-point iteration is converging too slow or not at all.

The csv export might also be sort of slow compared to writing the results to a mat-file.

Did you verify the simulation results or did you compare them to what you get from other tools?

**Comment by markaren** [comment]
I have not compared the results for this simulation yet. Will do it
tomorrow. Although I don't expect any differences as the system is quite
soft.
I did another test using a quarter-truck system (stiffer), where FMPy,
OMSimulator, FMI Go!, Vico and libcosim (thanks SSP!) provided pretty much
the same result.
However, FMPy and libcosim had some small initial oscillations not observed
in the other tools.

[image: image.png]

tir. 10. nov. 2020, 21:49 skrev Lennart Ochel <notifications@github.com>:

**Comment by markaren** [comment]
And now I remember that the simulation is a bit odd in that in provides no meaningful information before a reset signal is sent to one of the models after 50s. So there isn't really any meaningful data to compare.

In Vico and libcosim it is possible to specify a file with input actions to be executed at e.g. a specific point in time. I guess for OMSimulator, I need to add an FMU for that (when using the CLI)?

Sorry to clutter this issue with information unrelated to the original issue..

**Comment by markaren** [comment]
To update the original issue regarding parallel instantiation:

The PR attached to this issue resolves also issue with 20sim models (which are not JVM related). As such, this change should probably be applied regardless.

**Comment by markaren** [comment]
A bit unrelated to the issue, but I'd thought I share it anyway.
Attached is a performance benchmark of the quarter-truck system mentioned above, comparing the different (open-source) SSP compatible tools.

t=1000s, dt=0.001, numRuns=15

![image](https://user-images.githubusercontent.com/6005031/98916311-518ba780-24cb-11eb-8405-e8f07a1ae253.png)

* om is with .mat export (om runs with numProcs=1 as it is the most efficient for this system)
* vico and cosim results are with no time-series logging
* xxxCsv is with .csv export of ALL variables
* fmigo and fmpy exports a handful of variables to csv (no easy way of configuring this)

I'm in progress of creating a similar comparison using a more parallel friendly case, which is what triggered this issue.

**Comment by markaren** [comment]
I think I need to withdraw my statement of it now working with the 20sim model case.
Sure, it does not fail when `numProcs>2`.

I get the following output:

```
$ time OMSimulator -t=1000 --numProcs=3 ../QuarterTruck_1000hz_csv.ssp
info:    Set temp directory to    "E:/dev\QuarterTruck-benchmark\omsimulator"
info:    Set working directory to "E:/dev\QuarterTruck-benchmark\omsimulator"
info:    New model "QuarterTruck" with corresponding temp directory "E:/dev\QuarterTruck-benchmark\omsimulator\QuarterTruck-g5062ody"
info:    Set working directory to "E:/dev\QuarterTruck-benchmark\omsimulator"
info:    Set working directory to "E:/dev\QuarterTruck-benchmark\omsimulator\QuarterTruck-g5062ody"
info:    Set working directory to "E:/dev\QuarterTruck-benchmark\omsimulator"
info:    Initialized thread pool for model QuarterTruck with 3 threads
info:    Result file: ../results/omsimulator/results.csv (bufferSize=8192)

real    0m0,607s
user    0m0,000s
sys     0m0,015s

```

But this is actually a silent fail, as no csv is generated and seemingly no simulation is carried out. Setting `numProcs=2`, which also worked for that case before leads to a generated csv and a simulation that takes 7s. Not near the 0.6s reported above.

**Comment by lochel** [comment]
What happens if you set `bufferSize=1`?

**Comment by markaren** [comment]
What is meant by bufferSize in OMSimulator? Number of bytes in the file buffer right? I would assume 8192 is a good value.
I will try.

**Comment by lochel** [comment]
It refers to the number of time steps that are buffered before dumped to the result file. It actually should work fine with 8192 too. I just try to figure out why and where it crashes in this silent way.

**Comment by markaren** [comment]
Indeed, it is related to buffersize

```
$ time OMSimulator -t=1000 --numProcs=3 ../QuarterTruck_1000hz_csv.ssp
info:    Set temp directory to    "E:/dev\QuarterTruck-benchmark\omsimulator"
info:    Set working directory to "E:/dev\QuarterTruck-benchmark\omsimulator"
info:    New model "QuarterTruck" with corresponding temp directory "E:/dev\QuarterTruck-benchmark\omsimulator\QuarterTruck-tbwwz5t5"
info:    Set working directory to "E:/dev\QuarterTruck-benchmark\omsimulator"
info:    Set working directory to "E:/dev\QuarterTruck-benchmark\omsimulator\QuarterTruck-tbwwz5t5"
info:    Set working directory to "E:/dev\QuarterTruck-benchmark\omsimulator"
info:    Initialized thread pool for model QuarterTruck with 3 threads
info:    No result file will be created
warning: Alg. loop (size 4)
warning: temp directory "E:/dev\QuarterTruck-benchmark\omsimulator\QuarterTruck-tbwwz5t5" couldn't be removed
         boost::filesystem::remove: Prosessen f▒r ikke tilgang til filen fordi den brukes av en annen prosess: "E:/dev\QuarterTruck-benchmark\omsimulator\QuarterTruck-tbwwz5t5\temp\ground\binaries\win64"
info:    2 warnings
info:    0 errors

real    0m20,238s
user    0m0,000s
sys     0m0,015s

```

Norwegian error message. Translates to file in use by another process.

**Comment by lochel** [comment]
So this time it actually simulated fine, right? Probably difficult to tell without a result file.

**Comment by markaren** [comment]
Sorry, I made a mistake. I specified no result file. I did now and get the original silent error with buffersize=1.
The simulated time used when specifying no result file seems correct.

**Comment by lochel** [comment]
Can you share the ssp file so that we can debug it?

**Comment by markaren** [comment]
[QuarterTruck_1000hz_csv.zip](https://github.com/OpenModelica/OMSimulator/files/5529835/QuarterTruck_1000hz_csv.zip)

Rename .zip to .ssp.

**Comment by markaren** [comment]
Ok, it seems I ran the latest 20sim test on the main build and not the PR build.
It does indeed work fine with time-series export and `numProcs=3` with the patch you provided. Sorry about that.

**Comment by markaren** [comment]
As for the parallel benchmark test, I think I just have to leave out OMSimulator. I'm in a bit of a hurry and the current system is just to slow to simulate as is. Your handling of this is probably a good solution (trying to solve the alg. loop), but it's not needed/working for this system. The systems are using models highly relevant for our research, so I really want to use this specific benchmark. 
Setting the `--maxLoopIteration` value to 1 is not a solution either, as it prints a warning/error to the console at each timestep that it has been exceed, which kills any performance gain there.

**Comment by lochel** [comment]
Okay, thanks for the feedback. The step function representing the road is jumping from 0.5 to 0.6, right? I guess the algebraic loop is the reason for the differences in the simulation results you posted earlier.

**Comment by lochel** [comment]
It seems that the original issue of this ticket is only related to the visual studio build of OMSimulator. Your example works fine with the mingw build.

**Comment by arun3688** [comment]
I tested the  your `ssp`  with the `mingw` build, it worked with `numProcs=3`, but it has some random failures when trying to remove the `temp` directory , see the error message below

```
# ../../../install/mingw/bin/OMSimulator.exe --numProcs=3 Quartertruck.ssp
info:    Set temp directory to    "C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator"
info:    Set working directory to "C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator"
info:    New model "QuarterTruck" with corresponding temp directory "C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator\QuarterTruck-u7twfc0a"
info:    Set working directory to "C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator"
info:    Set working directory to "C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator\QuarterTruck-u7twfc0a"

 check signal filter: info:    Set working directory to "C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator"
info:    Initialized thread pool for model QuarterTruck with 3 threads
info:    Result file: test.csv (bufferSize=1)
warning: Alg. loop (size 4)
warning: temp directory "C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator\QuarterTruck-u7twfc0a" couldn't be removed
         filesystem error: cannot remove all: Input/output error [C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator\QuarterTruck-u7twfc0a] [C:\OPENMODELICAGIT\OpenModelica\OMSimulator\testsuite\OMSimulator\OMSimulator\QuarterTruck-u7twfc0a\temp\wheel\binaries\win64]
info:    2 warnings
info:    0 errors
```

**Comment by markaren** [comment]
> Okay, thanks for the feedback. The step function representing the road is jumping from 0.5 to 0.6, right?

The height value of the road changes at 1s.

The RMSE for the tools are as follows

![image](https://user-images.githubusercontent.com/6005031/98962131-9bde4a00-2506-11eb-82cb-5b6cf91c06ca.png)

I can't speak for FMIGo!, but Vico does not handle algebraic loops.

As for the performance, I was able to run OMSimulator without time-series export also.

![image](https://user-images.githubusercontent.com/6005031/98962482-f7103c80-2506-11eb-95eb-d1fa76e06298.png)

> It seems that the original issue of this ticket is only related to the visual studio build of OMSimulator. Your example works fine with the mingw build.

That is probably the case for the attached system using 20sim models. I believe it will fail with JVM models (original issue) regardless of the architecture. 

Again, sorry for cluttering this issue with what is really two issues, but that is solved using the same patch.

**Comment by lochel** [comment]
The changes are now in master. Can we close the issue or is there still something to do?

**Comment by markaren** [comment]
Closing, thanks :)
