### ISSUE TITLE
CSVWriter writes data for a single time-step twice

### ISSUE THREAD

**Issue by markaren** [OpenModelica/OMSimulator#863]
### Description

When selecting .csv as the preferred time-series output, data for each time-step is written twice (except for t=0.0).

### Steps to reproduce the behavior

Configure CSV time-series output in SSP

```xml
<ssd:DefaultExperiment>
    <ssd:Annotations>
           <ssc:Annotation type="org.openmodelica">
                <oms:SimulationInformation resultFile="results.csv" loggingInterval="0.0" bufferSize="8192" signalFilter="" />
            </ssc:Annotation>
        </ssd:Annotation>
    </ssd:Annotations>
</ssd:DefaultExperiment>
```

### Screenshots

![image](https://user-images.githubusercontent.com/6005031/98684044-0441f580-2366-11eb-98b7-772d191048f0.png)

### Version and OS

- Version:  OMSimulator v2.0.0.post241-g839c272-win
- OS:  Win10, 64bit

**Comment by lochel** [comment]
Communication points introduce discrete changes and therefore we export those time steps twice.

**Comment by markaren** [comment]
So this is intended behavior and not a bug.

Could you elaborate what OMSimulator is doing and why exporting twice is necessary in order for me to get a better understanding?

**Comment by lochel** [comment]
Signals do have two values on events/discrete changes. Therefore we output them twice, once with their left limit and once with their right limit.
This behavior can be disabled if needed using `--emitEvents=false`
