### ISSUE TITLE
Option to select which variables to export (.csv, .mat)

### ISSUE THREAD

**Issue by markaren** [OpenModelica/OMSimulator#865]
**Is your feature request related to a problem? Please describe.**
Some systems may contain a large number of variables, but the user may only care about a few.
Writing all variables (say many thousands), when the user only needs a handful is wasteful and impacts performance. It also makes it more difficult for the user to find the variables to plot after the fact.

**Describe the solution you'd like**
Make it possible to supply a configuration file (e.g. XML to make it consistent with SSP. Could also be a SSP annotation) with the variables to export. 

**Additional context**
Vico([example](https://github.com/NTNU-IHB/Vico/blob/master/examples/gunnerus/trajectory/LogConfig.xml)) and libcosim([example](https://github.com/open-simulation-platform/libcosim/blob/master/tests/data/LogConfig.xml)) allows this, with the additional option to specify how often variables from an individual model should be exported (e.g. each 10 time-step).
In these systems, no file means export everything, a file with no simulators/components means log nothing.

**Comment by lochel** [comment]
There is already the option to filter signals for the result file. This can in certain caises drastically improve performance. 
* [setSignalFilter](https://openmodelica.org/doc/OMSimulator/master/html/OMSimulatorPython.html#setsignalfilter)
* [addSignalsToResults](https://openmodelica.org/doc/OMSimulator/master/html/OMSimulatorPython.html#addsignalstoresults)
* [removeSignalsFromResults](https://openmodelica.org/doc/OMSimulator/master/html/OMSimulatorPython.html#removesignalsfromresults)

It is also possible to subsample signals to reduce the number of data point for a simulation:
* [setLoggingInterval](https://openmodelica.org/doc/OMSimulator/master/html/OMSimulatorPython.html#setlogginginterval)

We could also implement a xml-based filter as described above.

**Comment by lochel** [comment]
@robha67 This could also be of interest to you.

**Comment by markaren** [comment]
Thanks! Could you provide an example of a signalFilter string that would ignore everything?

**Comment by lochel** [comment]
An empty string should do it: `oms.setSignalFilter(<model>, "")`

**Comment by markaren** [comment]
I'm using the SSP interface :/

**Comment by lochel** [comment]
Of course you do 😄 

```xml
	<ssd:DefaultExperiment startTime="0.000000" stopTime="1.000000">
		<ssd:Annotations>
			<ssc:Annotation type="org.openmodelica">
				<oms:SimulationInformation resultFile="model_res.mat" loggingInterval="0.000000" bufferSize="10" signalFilter="" />
			</ssc:Annotation>
		</ssd:Annotations>
	</ssd:DefaultExperiment>
```

**Comment by markaren** [comment]
In SSP `signalFilter=""` has no effect. However, I tried setting the loggingInterval to a large number, which kinda works. At least to get the performance improvements.

**Comment by lochel** [comment]
I guess that is a bug then. You might open an issue for it.

You can also use an empty string for the `resultFile` attribute. In that case, there will be no result file.

**Comment by lochel** [comment]
The function `addSignalsToResults` and `removeSignalsFromResults` are now deprecated as they don’t play well with the GUI integration and SSP export. The issue with empty strings as signal filter is now fixed and the documentation got a slight update.

The remaining question is if we want to support the signal filter similar to vico and libcosim or if we think that the current approach is good enough.
@OpenModelica/omsimulator-developers @markaren @robha67 Any comments?

**Comment by markaren** [comment]
My initial reasoning for this issue was to be able to simulate without adding the overhead of variable export. This was possible by not specifying a result file. And if the signalFilter can be used to export only a subset, then that goes a long way. I hope also that it is possible to omit the signalFilter altogether (that it does not lead to a crash? I vaguely remember that it was not optional when I first tested the OM SSP support).

However, I do feel that stuff like logging should be specified outside the SSP, e.g. directly in the terminal because it requires changing the SSP for what is run-time options (which is tedious).
