### ISSUE TITLE
Import of non-OMSimulator SSP files

### ISSUE THREAD

**Issue by lochel** [OpenModelica/OMSimulator#872]
OMSimulator depends heavily on configuration for the master algorithm and other solvers needed to simulate a composite model. This prevents us currently from importing SSP files which were created with any other tool.

**Comment by markaren** [comment]
Using [sspgen](https://github.com/NTNU-IHB/sspgen) (I'm the author), it is easy to create SSP files that loads into several tools, including OMSimulator.
[This](https://github.com/NTNU-IHB/Vico/blob/master/examples/quarter-truck/quarter-truck.main.kts) is the source for the QuarterTruck system I shared in a different issue. 

However, it may lack some features that may become obvious as other people use it.
