### ISSUE TITLE
Cannot setBoolean after initialization for ME FMUs

### ISSUE THREAD

**Issue by superlou** [OpenModelica/OMSimulator#889]
### Description

Setting a boolean value after initialization results in `fmi2SetBoolean: Illegal call sequence. fmi2SetBoolean is not allowed in Continuous-Time Mode state`.

### Steps to reproduce the behavior

The following model was created in OpenModelica and exported to an FMU. The model, FMU, and code are attached: [oms_switch_test.zip](https://github.com/OpenModelica/OMSimulator/files/5596897/oms_switch_test.zip).

![image](https://user-images.githubusercontent.com/709695/100232348-433f8180-2ef6-11eb-9908-8778bed0d9d5.png)

The simulation code is:

```
from OMSimulator import OMSimulator


if __name__ == '__main__':
    oms = OMSimulator()
    oms.newModel('model')
    oms.addSystem('model.root', oms.system_sc)

    oms.addSubModel('model.root.system1', 'OMSSwitchTest.fmu')
    oms.instantiate('model')
    oms.setBoolean('model.root.system1.open', False)
    oms.initialize('model')
    oms.stepUntil('model', 1)

    i, status = oms.getReal('model.root.system1.resistor.i')
    print(f'Current = {i}')

    print('Opening switch...')
    oms.setBoolean('model.root.system1.open', True)
    oms.stepUntil('model', 2)

    i, status = oms.getReal('model.root.system1.resistor.i')
    print(f'Current = {i}')

    oms.terminate('model')
    oms.delete('model')
```

This results in the following messages:

```
info:    Set temp directory to    "C:/_projects\oms_switch_test"
info:    Set working directory to "C:/_projects\oms_switch_test"
info:    New model "model" with corresponding temp directory "C:/_projects\oms_switch_test\model-e0u2cmvi"
info:    model doesn't contain any continuous state
info:    Result file: model_res.mat (bufferSize=10)
error:   [fmi2logger] system1 (logStatusError): fmi2SetBoolean: Illegal call sequence. fmi2SetBoolean is not allowed in Continuous-Time Mode state.
error:   [fmi2logger] system1 (logStatusError): fmi2SetTime: Illegal call sequence. fmi2SetTime is not allowed in Error state.
error:   [stepUntil] fmi2_import_set_time failed for FMU "model.root.system1"
error:   [fmi2logger] system1 (logStatusError): fmi2CompletedIntegratorStep: Illegal call sequence. fmi2CompletedIntegratorStep is not allowed in Error state.
error:   [stepUntil] fmi2_import_completed_integrator_step failed for FMU "model.root.system1"
error:   [fmi2logger] system1 (logStatusError): fmi2Terminate: Illegal call sequence. fmi2Terminate is not allowed in Error state.
error:   [terminate] Termination of system "system1" failed
error:   [terminate] Termination of system "model.root" failed
error:   [fmi2logger] system1 (logStatusError): fmi2Terminate: Illegal call sequence. fmi2Terminate is not allowed in Error state.
error:   [terminate] Termination of system "system1" failed
error:   [terminate] Termination of system "model.root" failed
Current = 2.7999972000028
Opening switch...
Current = 2.7999972000028
info:    0 warnings
info:    11 errors
```

### Expected behavior

It was expected that the simulation would progress with no errors and the current at time 2 would be 0 amps.

### Screenshots

See above.

### Version and OS

- Version: 2.0.0.post267
- OS: Windows 10 x64 and Linux Mint 19.3 x64

**Comment by superlou** [comment]
If a real input is used to represent a boolean with 0 as false and 1 as true, the simulation is successful:

![image](https://user-images.githubusercontent.com/709695/100472118-9e65a580-30a9-11eb-95ea-7be79292a817.png)

The current is successfully reduced to almost nothing when the real input is set to 1, opening the switch:

```
Real input test:
info:    New model "model" with corresponding temp directory "/home/lsimons/workspace/oms_switch_test/model-ce7f2jq5"
info:    model doesn't contain any continuous state
info:    Result file: model_res.mat (bufferSize=10)
Current = 2.7999972000028
Opening switch...
Current = 0.00027997200279972006
info:    0 warnings
info:    11 errors
```

So, it looks like the solver is capable of working with boolean logic, it just looks like not when they are inputs. Is this expected? The full test script and models are attached: [oms_switch_test.zip](https://github.com/OpenModelica/OMSimulator/files/5608999/oms_switch_test.zip).

**Comment by AnHeuermann** [comment]
According to the FMI 2.0.1 Standard `fmi2SetBoolean` is only allowed to be call if the model is in one of the following states
  - instantiated
  - initialization mode
  - event mode

while `fmi2SetReal` is allowed in these states and in addition in continuous-time mode.

So why does your second example work: If you change `Real open` the `greaterThreshold` will trigger an event and in event mode the boolean is allowed to change.

So to change the value of a boolean you can call `fmi2SetBoolean` after `oms.instantiate('model')` and before `oms.initialize('model')` like you did.
But I think we don't have a function to enter event mode with some user callable function during simulation.

One would need to do something like:

1. fmi2EnterEventMode
2. fmi2SetBoolen / fmi2SetInteger
3. doEventIteration ( fmi2GetEventIndicators, fmi2NewDiscreteStates, ...)
4. fmi2EnterContinuousTimeMode

Adding API function for 1, 3 and 4 should be enough to do that.

**Comment by superlou** [comment]
With respect to 3, I think I found a [method for ME](https://github.com/OpenModelica/OMSimulator/blob/c8671bd24e18025abc80b650a9613ce33190f06b/src/OMSimulatorLib/ComponentFMUME.h#L88), though I don't see a corresponding one for CS FMUs. Is it just a matter of wrapping existing methods in the APIs, or will this require new functionality?

**Comment by AnHeuermann** [comment]
For CS the event handling has to be done by the FMU.

For co-simulation `fmi2SetBoolean `can be called ins states (see page 107 of the standard):

- instantiated
- Initialization Mode
- stepComplete

So I guess you can set the boolean after each completed step, but I never tried.

**Comment by superlou** [comment]
It looks like I've probably been exporting ME FMUs, since that's the default result of [translateModelFMU](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.translateModelFMU.html). I can try setting it to CS and see if that will let me setBoolean between simulation steps.

**Comment by AnHeuermann** [comment]
You have to use weakly coupled systems for CS
```lua
    oms.addSystem('model.root', oms.system_wc)
```
The FMUs exported by OpenModelica are probably ME and CS if you didn't specify it.

**Comment by superlou** [comment]
It looks like OpenModelica exports ME by default, which agrees with the [documentation](https://build.openmodelica.org/Documentation/OpenModelica.Scripting.translateModelFMU.html). I explicitly generated one for CS, and it worked! Weakly coupled system was required, and the output looks good:

```
Boolean input test (CS):
info:    Set temp directory to    "/home/lsimons/workspace/oms_switch_test"
info:    Set working directory to "/home/lsimons/workspace/oms_switch_test"
info:    New model "model" with corresponding temp directory "/home/lsimons/workspace/oms_switch_test/model-mxv9mhqx"
info:    Result file: model_res.mat (bufferSize=10)
Current = 2.7999972000028
Opening switch...
Current = 0.00027997200279972006
```

It would still be nice to have setBoolean handle events for ME FMUs. Is there a performance advantage one way or the other between ME and CS? My understanding is that if the OMS solvers are similar to those in OpenModelica, I wouldn't expect any differences in behavior? If I don't intend to combine my FMU with other FMUs, is it more straightforward to use CS?

**Comment by AnHeuermann** [comment]
`setBoolean` should only be allowed to call if `fmi2SetBoolean` is allowed.
Adding API functions for `fmi2EnterEventMode` and `fmi2EnterContinuousTimeMode` is probably no big deal.

**Comment by AnHeuermann** [comment]
I discussed a bit with @lochel and we plan to implement something like this:

The first call to `oms.setBoolean` or `oms.setInteger` will enter event mode if not already in event mode or initialization model.
The next call to `oms.stepUntil` will to the event iteration and enters continuous-time mode.

But it's getting quiet crowded on my todo-list. I'm not sure when this can be implemented.
But it shouldn't be very complicated to implement.

**Comment by superlou** [comment]
That sounds good to me. I'd also be ok with requiring explicit commands to switch modes and do the event iteration and could update the documentation. It's not a rush for me, since switching to CS FMUs has been working fine as far as I can tell.

**Comment by lochel** [comment]
@AnHeuermann is it still on your list? 👼

**Comment by AnHeuermann** [comment]
This one dropped off my list. Since there is a working way.
We could probably do it in a few hours though, but at the moment I'm busy with something else.
