### ISSUE TITLE
Problem when changing simulation start time via setStartTime()

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#891]
A working simulation breaks when I shift the start time to larger values than 0. This works with my single fmu composite models. It does however, not work when I have multiple connected FMUs (wc). The simulation runs in to some sort of idle without producing any result files or clear messages in the simulation log. I have tested with both fixed and adaptive step size master algorithms and run into the same problem regardless. 

@lochel

**Comment by robha67** [comment]
It seems like shifting the start time renders and unstable simulation. The example in the test-suite (https://github.com/OpenModelica/OMSimulator/tree/master/testsuite/AircraftVehicleDemonstrator) will likely suffer from these issues. I have not tested this yet though

**Comment by AnHeuermann** [comment]
Hey @robha67 
Do you have an working minimal example for your problem? Without it's very hard to give any feedback.

**Comment by lochel** [comment]
I am pretty sure that this has something to do with the initialization issues in Dymola FMUs. I don't think there is anything we can do about it. The startTime works just fine with all models I can test. Please reopen this issue if you can provide an example that we can use for testing.
