### ISSUE TITLE
Update OMSimulator graphical modeling documentation 

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#900]
### Description

The [documentation for graphical modeling with OMSimulator](https://openmodelica.org/doc/OMSimulator/master/html/OMEdit.html#new-omsimulator-model) from OMEdit is using old screenshots.
When using a recent nightly build of OMEdit you don't have a menu item `OMSimulator` to create a new OMSimulator model.

### Expected behavior

I only see an option to create new SSP models. So it should be described how to create some models with that.

### Screenshots

<img width="443" alt="Screenshot_OMEdit" src="https://user-images.githubusercontent.com/38031952/102611616-8aa0e280-412f-11eb-87c1-ea7371c64851.png">

### Version and OS

- Version: OMEdit connected to OpenModelica v1.17.0-dev-281-g1a53775ae8 (64-bit)
and to OMSimulator v2.0.0.post259-g2d9666d-mingw
- OS: Win10, 64bit

**Comment by AnHeuermann** [comment]
I'm going to update it today.

**Comment by lochel** [comment]
Thanks @AnHeuermann!

**Comment by AnHeuermann** [comment]
The changes are now life in the [OMSimulator User's Guide](https://openmodelica.org/doc/OMSimulator/master/html/OMEdit.html#), but not the OpenModelica User's Guide yet. But they will synchronize when the OMSimulator sub-repo is updated in OpenModelica/OpenModelica.
