### ISSUE TITLE
lib/OMSimulator directory contains duplicated files

### ISSUE THREAD

**Issue by adeas31** [OpenModelica/OMSimulator#947]
### Description

After installing the latest OpenModelica nightly build I noticed that there are around 700 MB of files duplicated inside `lib/OMSimulator` folder.

### Steps to reproduce the behavior

Install OpenModelica on Windows and take a look at lib/OMSimulator folder. The same files are also present in the bin folder as well.

### Expected behavior

lib/OMSimulator should only contain the OMSimulator binaries.

### Screenshots

![image](https://user-images.githubusercontent.com/4007231/107969250-cfba8700-6faf-11eb-94a3-40eb3f5b0246.png)

### Version and OS

- Version: [Doesn't matter]
- OS: [Win10, 64bit]

**Comment by lochel** [comment]
Unfortunately, we cannot just delete the duplicated files, because we depend on the path:

![image](https://user-images.githubusercontent.com/8457302/108049221-47d48b80-7048-11eb-8e5b-e8f89b1c98e7.png)

@AnHeuermann Do you see a way to solve this issue?

**Comment by AnHeuermann** [comment]
We could add a bunch of symbolic links

**Comment by lochel** [comment]
Changing the path when compiling from the super project sounds like the right thing to do 👍

**Comment by adeas31** [comment]
> Unfortunately, we cannot just delete the duplicated files, because we depend on the path:

> ### Expected behavior
> lib/OMSimulator should only contain the OMSimulator binaries.

For sure keep the binaries needed by OMSimulator but why there are folders for Qt plugins? I think the problem is you just make a copy of bin folder https://github.com/OpenModelica/OMSimulator/blob/master/src/OMSimulatorPython/CMakeLists.txt#L29

**Comment by lochel** [comment]
@adeas31 can this be closed or do we have to improve it further?

**Comment by adeas31** [comment]
Is better than before but would be nice to get rid of empty directories as well.

**Comment by lochel** [comment]
I didn't find a good solution to avoid the empty directories. @AnHeuermann do you have a idea for it?

**Comment by AnHeuermann** [comment]
We can just call `rm` on them in the Makefile calling the CMake stuff. Not a pretty solution but should work.

**Comment by adeas31** [comment]
@AnHeuermann solution is not so bad.

**Comment by adeas31** [comment]
Yes, it seems the build process has changed and this issue is not valid anymore.
