### ISSUE TITLE
Add getSSPInfo and add platforms to 

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#949]
**Is your feature request related to a problem? Please describe.**
I'd like to have an automated check in OMEdit if an SSP or FMU can run on my platform. For that two things would be needed:
1. Adding information about available platforms to [getFMUInfo](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omsimulator.html#getfmuinfo).
2. Adding a `getSSPinfo` similar to `getFMUInfo`.

**Describe the solution you'd like**
The functions would need to check the extracted FMU(s) binaries/ folder.
We could add a struct like
```C
typedef struct {
  bool hasWin32;
  bool hasWin64;
  bool hasLinux32;
  bool hasLinux64;
  bool hasDarwin32;
  bool hasDarwin64;

  bool hasOthers;
  unsigned int numOtherPlatforms;
  char** otherPlatformNames;
} oms_fmi_platforms_t
```
to `oms_fmu_info_t`.

**Additional context**
I opened a ticket on OpenModelica which (if accepted) would need this kind of feature: https://github.com/OpenModelica/OpenModelica/issues/7168

**Comment by lochel** [comment]
I agree to add such information to `oms_fmu_info_t`. Maybe just as a comma separated string with all platforms. `oms_fmi_platforms_t` from your proposal seems unnecessary complicated.

**Comment by AnHeuermann** [comment]
It is easy to use. If I know I want win64 binaries I can just do
```C
oms_getFMUInfo("myFMU", fmuInfo);
if (fmuInfo->plaforms->hasWin64)
  // Do stuff
```
Otherwise I would need to free memory for `cahr*` strings and parse all of the list to get the info I want.

**Comment by lochel** [comment]
The memory management isn't a problem. It will be allocated when creating a FMU object in OMSimulator and only freed when the fmu is deleted from the OMSimulator model. 

Your proposal contains strings to catch all the not-standardized (and other standardized platforms). Mixing two representations for the platforms looks to me a bit complicated.

Instead, we could just use a comma separated string that contain all available platforms. It wouldn't really make it that complicated to use 😉:
```c
status = oms_getFMUInfo("myFMU", &fmuInfo);
if (status == oms_status_ok && strstr(fmuInfo->plaforms, "\"win64\"") != NULL)
  // Do stuff
```
