### ISSUE TITLE
Functionality to update exsting SSV file with paramter values

### ISSUE THREAD

**Issue by robha67** [OpenModelica/OMSimulator#951]
Functionality enabling the modification of, and the generation of, separate SSV files. The functionality should allow the user to export parameter values specified via, for example, OMS.setReal without generating a complete SSP. 
Then, it should be possible to, via some API command, to invoke such an SSV file on an existing SSP i.e. add it to the resource folder and point to it in the SSD. When adding the "new" SSV file to the resources of the SSP, previously existing SSV files should not be overwritten. It should be possible to change between several SSV files (corresponding to the same model) located in the resources folder. @arun3688

**Comment by arun3688** [comment]
@robha67 I think the first feature, generating of SSV files with update start values, should look something like below

```
oms_exportSSVTemplate("model") // list of all default start values in modeldescription.xml
oms_setReal("model.root.A", 10) // set new start values
oms_setReal("model.root.B", 20) // set new start values
oms_exportSSVTemplate("model")  // should update the new start values in the generated ssv template 
```
The second feature , having a new API to insert the new ssv file in the `ssp` package is basically unzipping and zipping and i guess this can be done by yourself or we can do it via an API also @lochel  can you comment on this?

And the third feature, switching between different SSV files, I think this can be done via the `oms_importFile()` API with some modification like

```
oms_importFile("import_export_parameters_inline.ssp"); // default ssv files will be used 
oms_importFile("import_export_parameters_inline.ssp", "config1.ssv")  // while importing we can override the default file with config1.ssv if it exisits in the resource folder otherwise default `.ssv file` in ssd file will be used.
oms_importFile("import_export_parameters_inline.ssp", "config2.ssv") 
```

I hope you want something like this ? 

@lochel can you give some suggestions or comments ?

**Comment by robha67** [comment]
1)

**_I think the first feature, generating of SSV files with update start values, should look something like below

oms_exportSSVTemplate("model") // list of all default start values in modeldescription.xml
oms_setReal("model.root.A", 10) // set new start values
oms_setReal("model.root.B", 20) // set new start values
oms_exportSSVTemplate("model")  // should update the new start values in the generated ssv template_** 

Perfect solution, exactly what we need. 

2)
The second feature , having a new API to insert the new ssv file in the ssp package is basically unzipping and zipping and i guess this can be done by yourself or we can do it via an API

From my perspective, some API functionality of doing this would be nice. I guess I could do the un-zipping and zipping by myself but packaging functionality is already implemented in the OMSimulator so i guess it's a bit uneccessary. I think this functionality will be used by alot of users once the standard becomes well established. I guess there could be some collisions if an SSV with the same name already exists in the SSP. In that case I suggest that the saving of the ssv is not allowed. If you want to overwrite the values in a current SSV then Ihe functionality you suggest in 1) could be used?

3)
And the third feature, switching between different SSV files, I think this can be done via the oms_importFile() API with some modification like

oms_importFile("import_export_parameters_inline.ssp"); // default ssv files will be used 
oms_importFile("import_export_parameters_inline.ssp", "config1.ssv")  // while importing we can override the default file with config1.ssv if it exisits in the resource folder otherwise default `.ssv file` in ssd file will be used.
oms_importFile("import_export_parameters_inline.ssp", "config2.ssv") 

Perfect from my point of view

**Comment by arun3688** [comment]
@robha67 The first part is fixed updating the template file with this commit https://github.com/OpenModelica/OMSimulator/commit/0722da6addaa025a85bb2588ade25ae232caa68d, you can test it

**Comment by arun3688** [comment]
@robha67 this is fixed, i am closing this issue you can reopen if you find some problems
