### ISSUE TITLE
updateSignals is slow

### ISSUE THREAD

**Issue by AnHeuermann** [OpenModelica/OMSimulator#989]
### Description

When profiling OMSimulator with `gprof` I noticed that `oms::ResultWriter::updateSignal(unsigned int, oms::SignalValue_t)` and `oms::ComponentFMUME::updateSignals(oms::ResultWriter&)` are taking up a significant portion of the total simulation time (each around 7%).
A way to improve it is to not call `fmi2GetReal` for each variable alone but to call it with an array of all variables of interest.

### Steps to reproduce the behavior

Compile OMSimulator with `gcc`, use `-pg` flag and use `gprof` to generate a profile for a simulation of a FMU.

**Comment by lochel** [comment]
I am still not convinced that it will be much faster to call `fmi2GetReal` with an array, but let's hope you are right. Will be interessting to see a comparison ☺️

**Comment by AnHeuermann** [comment]
I did a small comparison of OMSimulator between the master branch and PR #993 for `ScalableTestSuite.Elementary.ParameterArrays.ScaledExperiments.Table_N_280_M_280` with `--tolerance=1e-8 --intervals=1000 --ignoreInitialUnknowns=true`.

After three runs each I can say that there is no big difference between the two. The new version is slightly faster (not a full second) with a total simulation time of around 57 seconds.

**Comment by lochel** [comment]
I'll close it for now. We might give it another go someday, but it isn't as crucial as anticipated.
